/** V3 Bank authoring: semantic architecture first, explicit props/security last. */
import type {StageDefinition,PropDef,PropKind,GuardDef} from '../../src/game/levels/StageDefinition';
import type {EnvironmentAssetId} from '../../src/assets/environmentKit';
import type {V3MissionDesign} from './v3DesignSchema';
import {compileStage,TILE} from '../../src/game/world/compileStage';
import {buildNavigation,findPath,clearSegment} from '../../src/game/world/navigation';
import {PROP_KIT} from '../../src/game/world/propKit';
import {BANK_PLANS,BANK_GUARD_PATROLS,BANK_V5_VOIDS,BANK_V5_OBJECTIVES} from './v5BankPlans';
import type {BankRoom,BankPlan} from './v3BankPlans';
export {BANK_PLANS};export type {BankRoom};
const ASSET:Partial<Record<PropKind,EnvironmentAssetId>>={objectiveCase:'bank_small_safe',bankWall:'bank_wall',bankStaffDoor:'bank_staff_door',bankSecurityGate:'bank_security_gate',bankVaultCorridorWall:'bank_vault_corridor_wall',bankTellerCounter:'bank_teller_counter',bankSecurityCheckpoint:'bank_security_checkpoint',bankDepositBoxWall:'bank_deposit_box_wall',bankCashProcessingTable:'bank_cash_processing_table',bankVaultDoor:'bank_vault_door',bankOfficeDesk:'bank_office_desk',bankFilingCabinet:'bank_filing_cabinet',bankCashCart:'bank_cash_cart',bankQueueBarrier:'bank_queue_barrier',bankSmallSafe:'bank_small_safe',bankMonitor:'bank_monitor',bankClock:'bank_clock',bankPaperwork:'bank_paperwork',bankFloorMarker:'bank_floor_marker',bankPlant:'bank_plant',bankMainVault:'bank_main_vault'};
const centre=(r:BankRoom)=>({x:r.x+Math.floor(r.w/2),y:r.y+Math.floor(r.h/2)});
const waypoint=(r:BankRoom,offset=0)=>({x:r.x+r.w/2+offset,y:r.y+r.h-1.5});
function portal(r:BankRoom,side:'left'|'right'|'top'|'bottom'){
 const c=centre(r);return {x:side==='left'?r.x+.5:side==='right'?r.x+r.w-.5:c.x,y:side==='top'?r.y+.5:side==='bottom'?r.y+r.h-.5:c.y};
}
function layout(plan:BankPlan){
 const cols=Math.max(...plan.rooms.map(r=>r.x+r.w))+2,rows=Math.max(...plan.rooms.map(r=>r.y+r.h))+2,floor=new Set<string>();
 const paint=(x:number,y:number,w:number,h:number)=>{for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)floor.add(`${xx},${yy}`);};
 for(const r of plan.rooms)paint(r.x,r.y,r.w,r.h);
 for(const [a,b]of plan.links){const from=centre(plan.rooms[a]),to=centre(plan.rooms[b]);if((plan.title==='Main Vault'&&((a===1&&b===2)||(a===5&&b===8)))||(plan.title==='Security Checkpoint'&&a===3&&b===2)){paint(from.x-1,Math.min(from.y,to.y)-1,2,Math.abs(to.y-from.y)+2);paint(Math.min(from.x,to.x)-1,to.y-1,Math.abs(to.x-from.x)+2,2);}else{paint(Math.min(from.x,to.x)-1,from.y-1,Math.abs(to.x-from.x)+2,2);paint(to.x-1,Math.min(from.y,to.y)-1,2,Math.abs(to.y-from.y)+2);}}
 for(const v of BANK_V5_VOIDS[BANK_PLANS.indexOf(plan)+1]??[])for(let y=v.y;y<v.y+v.h;y++)for(let x=v.x;x<v.x+v.w;x++)floor.delete(`${x},${y}`);
 return Array.from({length:rows},(_,y)=>Array.from({length:cols},(_,x)=>floor.has(`${x},${y}`)?'.':[-1,0,1].some(dy=>[-1,0,1].some(dx=>floor.has(`${x+dx},${y+dy}`)))?'#':' ').join(''));
}
function route(def:StageDefinition,points:{x:number;y:number}[],radius=18){
 const stage=compileStage(def),nav=buildNavigation(stage,radius),out=[points[0]];
 for(const b of points.slice(1)){const a=out.at(-1)!;
  if(clearSegment(a.x*TILE,a.y*TILE,b.x*TILE,b.y*TILE,nav.blockers,radius))out.push(b);
  else{const path=findPath(nav,a.x*TILE,a.y*TILE,b.x*TILE,b.y*TILE);if(path.length<2||Math.hypot(path.at(-2)!-b.x*TILE,path.at(-1)!-b.y*TILE)>.01)throw Error(`${def.id}: inaccessible authored point ${b.x},${b.y} from ${a.x},${a.y} radius ${radius} clearA=${clearSegment(a.x*TILE,a.y*TILE,a.x*TILE,a.y*TILE,nav.blockers,radius)} clearB=${clearSegment(b.x*TILE,b.y*TILE,b.x*TILE,b.y*TILE,nav.blockers,radius)}`);for(let i=0;i<path.length;i+=2){const q={x:path[i]/TILE,y:path[i+1]/TILE};if(Math.hypot(q.x-out.at(-1)!.x,q.y-out.at(-1)!.y)>.01)out.push(q);}}
 }
 return out;
}
export function createBankMission(mission:number):StageDefinition{
 const plan=BANK_PLANS[mission-1],id=`03-${String(mission).padStart(2,'0')}`,spawn=portal(plan.rooms[plan.entry.zone],plan.entry.side),exit=portal(plan.rooms[plan.exit.zone],plan.exit.side),goal=plan.rooms[plan.goal],objective=BANK_V5_OBJECTIVES[mission]??{x:goal.x+goal.w/2,y:goal.y+goal.h-2};
 const props:PropDef[]=plan.props.map(p=>({kind:p.kind,visualAssetId:ASSET[p.kind],x:plan.rooms[p.zone].x+p.dx,y:plan.rooms[p.zone].y+p.dy}));
 const guardDefs:GuardDef[]=plan.guardZones.map((zi,i)=>{const r=plan.rooms[zi],objectiveRole=zi===plan.goal,start=BANK_GUARD_PATROLS[mission-1][i][0],next=BANK_GUARD_PATROLS[mission-1][i][1];return{id:`${id}-g${i+1}`,x:r.x+start[0],y:r.y+start[1],facing:Math.atan2(next[1]-start[1],next[0]-start[0]),routeId:`${id}-route${i+1}`,pace:i%2?.85:.8,visionRange:objectiveRole||r.purpose.includes('security-check')?4.6:4.2,visionHalfAngle:Math.PI/6,startDelay:i*.65,role:objectiveRole?'objective':r.purpose.includes('junction')?'corridor':zi===plan.exit.zone?'exit':'room',theftRole:objectiveRole?'objective':r.purpose.includes('junction')?'corridor':zi===plan.exit.zone?'exit':'zone',theftPosts:[waypoint(r),waypoint(plan.rooms[plan.exit.zone])],theftSearchSectors:[{id:`${r.name}: initial assigned circuit`,anchors:[waypoint(r),waypoint(plan.rooms[(zi+1)%plan.rooms.length])]}, {id:`${r.name}: junction and exit sweep`,anchors:plan.rooms.map((_,j)=>waypoint(plan.rooms[(j+i)%plan.rooms.length]))}]};});

 const landmark=props[plan.landmark];
 const def:StageDefinition={id,number:20+mission,chapter:3,mission,title:plan.title,theme:'bank',structurePlan:plan.identity,layout:layout(plan),props,lights:[...plan.rooms.map((r,i)=>({...centre(r),radius:Math.max(3,Math.min(r.w,r.h)*.6),kind:i===plan.goal?'cyan' as const:'warm' as const,intensity:i===plan.goal?.48:.52})),{...objective,radius:2.8,kind:'cyan',intensity:.7}],ambientDarkness:.18,playerSpawn:{...spawn,facing:plan.entry.side==='left'?0:plan.entry.side==='right'?Math.PI:plan.entry.side==='top'?Math.PI/2:-Math.PI/2},objective:{kind:'vaultGem',...objective},exit:{x:exit.x-.5,y:exit.y-.5,w:1,h:1},entryEdge:plan.entry.side,exitEdge:plan.exit.side,entryPosition:spawn,exitPosition:exit,landmark:{name:plan.title,kind:landmark.kind,x:landmark.x,y:landmark.y},securityZones:plan.rooms.map((r,i)=>({name:r.name,...centre(r),radius:Math.min(r.w,r.h)/2,guardId:guardDefs.find((g,j)=>plan.guardZones[j]===i)?.id})),safeZones:[{...spawn,radius:.35}],guards:guardDefs,patrolRoutes:[],cameras:plan.cameras.map((zi,i)=>{const r=plan.rooms[zi];return{id:`${id}-cam${i+1}`,x:mission===10&&zi===8?r.x+.3:r.x+r.w-.3,y:r.y+.6,centerFacing:mission===10&&zi===8?Math.PI*.25:Math.PI*.75,sweepAngle:.55,sweepSpeed:.35,pauseAtEnds:.6,range:5,visionAngle:.65,suspicionRate:.4};})};
 // Guard routes use authored room perimeter corners, navigation only expands blocked links.
 for(const [i,g]of guardDefs.entries()){const r=plan.rooms[plan.guardZones[i]],authored=BANK_GUARD_PATROLS[mission-1][i].map(p=>({x:r.x+p[0],y:r.y+p[1]})),corners=[...authored,authored[0]],points=route(def,corners,8);def.patrolRoutes!.push({id:g.routeId!,mode:'loop',points:points.slice(0,-1).map(p=>({...p,wait:corners.some(c=>Math.hypot(c.x-p.x,c.y-p.y)<.01)?.6:0,look:plan.guardZones[i]===plan.goal&&corners.some(c=>Math.hypot(c.x-p.x,c.y-p.y)<.01)?Math.atan2(objective.y-p.y,objective.x-p.x):undefined}))});}
 const routes=[{name:'main',order:plan.main,offset:0},{name:'safe',order:plan.safe,offset:-1.25},{name:'risk',order:plan.risk,offset:1.25}];
 def.testRoutes=routes.map(r=>({name:`${r.name}: ${plan.identity}`,points:route(def,[spawn,...r.order.map(zi=>waypoint(plan.rooms[zi],r.offset)),objective])}));
 def.escapeRoutes=[{name:'escape: distinct service/security return',points:route(def,[objective,...(mission===10?[{x:goal.x+goal.w-1.5,y:goal.y+4}]:[]),...plan.escape.slice(1).map(zi=>waypoint(plan.rooms[zi])),exit])}];
 const stage=compileStage(def),nav=buildNavigation(stage,18);
 // Explicit safe-room candidates are accepted only with actual movement clearance/reachability.
 for(const r of plan.rooms.filter(r=>r.safeReason)){const point=waypoint(r,-Math.min(1.25,r.w/4)),path=findPath(nav,spawn.x*TILE,spawn.y*TILE,point.x*TILE,point.y*TILE);if(path.length&&clearSegment(point.x*TILE,point.y*TILE,point.x*TILE,point.y*TILE,stage.movementBlockers,18))def.safeZones!.push({...point,radius:.35});}
 return def;
}
export const BANK_PRODUCTION=Array.from({length:10},(_,i)=>createBankMission(i+1));
export const BANK_REQUIRED_ASSETS=Object.keys(PROP_KIT).filter(k=>k.startsWith('bank'));
export const BANK_V3_DESIGNS:V3MissionDesign[]=BANK_PRODUCTION.map((def,i)=>{const plan=BANK_PLANS[i],landmark=def.landmark!;return{id:def.id,missionFantasy:plan.fantasy,architecture:plan.identity,topology:{entrySide:plan.entry.side,objectiveRegion:plan.rooms[plan.goal].name,exitSide:plan.exit.side,routeShape:plan.shape,escapeDirection:plan.shape.split(' ').at(-1)!},entry:def.playerSpawn,objective:def.objective!,exit:def.exitPosition!,zones:plan.rooms.map((r,zi)=>({id:`${def.id}-z${zi+1}`,name:r.name,bounds:{x:r.x,y:r.y,w:r.w,h:r.h},purpose:r.purpose,features:r.features,guardIds:def.guards.filter((g,j)=>plan.guardZones[j]===zi).map(g=>g.id!),cameraIds:def.cameras!.filter((_,j)=>plan.cameras[j]===zi).map(c=>c.id),...(r.name==='Cash Workfloor'?{cells:[{name:'Sorting tables',purpose:'timing' as const,point:{x:r.x+6,y:r.y+5}},{name:'Dispatch tables and cart',purpose:'safe-risk-choice' as const,point:{x:r.x+12,y:r.y+9}},{name:'Cash audit bank',purpose:'chase-break' as const,point:{x:r.x+8.5,y:r.y+7.65}},{name:'Central patrol crossing',purpose:'junction' as const,point:{x:r.x+14.5,y:r.y+4.5}}]}:{}),...(r.safeReason?{intentionalSafeReason:r.safeReason,intentionalSafeBounds:{x:r.x,y:r.y,w:r.w,h:r.h}}:{})})),landmark:{name:landmark.name,point:landmark,relation:i===5?'checkpoint':'objective',reason:plan.props[plan.landmark].reason},coverChain:[...plan.main,...plan.escape.slice(1)].flatMap(zi=>def.props.filter((p,j)=>plan.props[j].zone===zi&&PROP_KIT[p.kind].cover).map(p=>({name:p.kind,point:p,reason:plan.props[def.props.indexOf(p)].reason}))),guardRoles:def.guards.map((g,j)=>({id:g.id!,role:g.theftRole!,zones:[plan.rooms[plan.guardZones[j]].name]})),cctv:def.cameras!.map((c,j)=>({id:c.id,mountContext:`Wall corner of ${plan.rooms[plan.cameras[j]].name}`,counterplay:'Fixed angular sweep and0.6s endpoint pauses; route-side cover or alternate staff branch'})),searchSectors:def.guards.map(g=>({guardId:g.id!,zones:plan.rooms.map(r=>r.name)})),structureReasons:def.props.map((p,j)=>({kind:p.kind,point:p,reason:plan.props[j].reason})),changes:['Rebuilt architecture and entry/exit relation before placing structures','Authored route purpose, central cells and role-specific security','Vault/target relation uses actual approved Bank structures'],baselineFailures:['Entry and Exit shared the same public room and side within3.5tiles','Repeated stacked rectangular rooms and center-prop/right-corner-Guard pattern','Safe/Risk distinction depended mainly on waypoint offset rather than spatial purpose']};});
