/**
 * Regenerates src/game/levels/missionBriefs.ts from the baked mission config
 * (src/game/levels/stages/campaignStages.json).
 *
 * Mission Select needs guard / objective counts, but must not import the 540 KB stage
 * JSON on the menu path (stage modules load lazily on Play). This keeps a tiny derived
 * index; src/ui/branding/missionSelect.test.ts fails if it drifts from the config.
 *
 *   npx tsx tools/campaign/buildMissionBriefs.ts
 */
import {readFileSync,writeFileSync} from 'node:fs';

interface Stage {id:string;guards:unknown[];objective?:unknown}
export function missionBriefsFromStages(stages:Stage[]) {
 const briefs:Record<string,{guards:number;objectives:number}>={};
 for(const stage of stages)briefs[stage.id]={guards:stage.guards.length,objectives:stage.objective?1:0};
 return briefs;
}
const stages=JSON.parse(readFileSync('src/game/levels/stages/campaignStages.json','utf8')) as Stage[];
const briefs=missionBriefsFromStages(stages);
const rows=Object.entries(briefs).map(([id,b])=>` '${id}':{guards:${b.guards},objectives:${b.objectives}},`).join('\n');
writeFileSync('src/game/levels/missionBriefs.ts',`// GENERATED by tools/campaign/buildMissionBriefs.ts from stages/campaignStages.json. Do not edit by hand.
// Guard / objective counts shown on Mission Select, without loading the stage JSON on the menu path.
export interface MissionBrief {guards:number;objectives:number}
export const MISSION_BRIEFS:Readonly<Record<string,MissionBrief>>={
${rows}
};
`);
console.log(`missionBriefs.ts: ${Object.keys(briefs).length} missions`);
