/** V9: four authored heists. Offline authoring only; never runs during mission loading. */
import type {StageDefinition,PropDef} from '../../src/game/levels/StageDefinition';
import type {EnvironmentAssetId} from '../../src/assets/environmentKit';
import {compileStage,TILE} from '../../src/game/world/compileStage';
import {buildNavigation,clearSegment,findPath,nodeX,nodeY} from '../../src/game/world/navigation';
import {BODY} from '../../src/game/guards/guardTuning';
export const V9_CORE_IDS=['02-06','02-10','03-08','03-10'] as const;
type Point={x:number;y:number};
type Zone={name:string;x:number;y:number;w:number;h:number;purpose:string};
type Item=PropDef&{reason:string};
type Guard={zone:number;role:NonNullable<StageDefinition['guards'][number]['role']>;points:Point[]};
type Plan={fantasy:string;zones:Zone[];links:number[][];entry:Point;goal:Point;exit:Point;entrySide:StageDefinition['entryEdge'];exitSide:StageDefinition['exitEdge'];items:Item[];guards:Guard[];cameras:{zone:number;x:number;y:number;look:number}[];main:Point[];safe:Point[];risk:Point[];escape:Point[];alternate:Point[]};
const p=(x:number,y:number):Point=>({x,y});
const z=(name:string,x:number,y:number,w:number,h:number,purpose:string):Zone=>({name,x,y,w,h,purpose});
const item=(kind:PropDef['kind'],asset:EnvironmentAssetId,x:number,y:number,scale:number,reason:string):Item=>({kind,visualAssetId:asset,x,y,scale,collisionScale:scale,reason});
const art=(x:number,y:number,s=1.8,reason='Exhibit screen terminates a sightline while leaving two viewing shoulders')=>item('partition','gallery_white_wall',x,y,s,reason);
const sculpture=(x:number,y:number,s=2,reason='Sculpture focal island provides two genuine movement/LOS shoulders')=>item('statue','gallery_sculpture_large',x,y,s,reason);
const installation=(x:number,y:number,s=2.4,reason='Installation island distinguishes an exposed viewing side from a sheltered side')=>item('statue','gallery_installation_art',x,y,s,reason);
const plinth=(x:number,y:number,s=1.3)=>item('table','gallery_central_plinth',x,y,s,'Low satellite plinth ties the exhibit together; collision BLOCK, LOS PASS');
const bench=(x:number,y:number)=>item('bench','gallery_modern_bench',x,y,1.4,'Visitor viewing bay and route soft divider, never full cover');
const bankAsset:Partial<Record<PropDef['kind'],EnvironmentAssetId>>={bankQueueBarrier:'bank_queue_barrier',bankTellerCounter:'bank_teller_counter',bankSecurityGate:'bank_security_gate',bankSecurityCheckpoint:'bank_security_checkpoint',bankOfficeDesk:'bank_office_desk',bankFilingCabinet:'bank_filing_cabinet',bankDepositBoxWall:'bank_deposit_box_wall',bankCashProcessingTable:'bank_cash_processing_table',bankCashCart:'bank_cash_cart',bankSmallSafe:'bank_small_safe',bankMainVault:'bank_main_vault',bankVaultDoor:'bank_vault_door',bankVaultCorridorWall:'bank_vault_corridor_wall',bankMonitor:'bank_monitor',bankPaperwork:'bank_paperwork',bankFloorMarker:'bank_floor_marker',bankPlant:'bank_plant'};
const bank=(kind:PropDef['kind'],x:number,y:number,reason:string,s=1)=>item(kind,bankAsset[kind]!,x,y,s,reason);
const g=(zone:number,role:Guard['role'],points:number[][]):Guard=>({zone,role,points:points.map(([x,y])=>p(x,y))});
export const V9_HEIST_PLANS:Record<string,Plan>={
 '02-06':{
 fantasy:'Approach the western glass studies, choose either side of the glazed installation court, steal the north featured study and escape via the separate east sculpture gallery.',
 zones:[z('Approach Gallery',1,19,8,8,'APPROACH: sheltered exhibit threshold and initial security read'),z('Glass Exhibition',1,6,8,11,'INFILTRATION: glass viewing architecture passes LOS, not bodies'),z('Central Installation',11,9,12,14,'SECURITY LAYER: two viewing shoulders around the glazed installation'),z('Sculpture Art Cell',25,10,8,13,'ESCAPE: artwork cells interrupt a direct pursuit'),z('Featured Study',12,1,11,6,'OBJECTIVE: named masterpiece study chamber')],
 links:[[3,16,3,4],[8,21,4,3],[8,10,4,3],[16,6,3,4],[22,18,4,3]],entry:p(1.6,24),goal:p(19,3.8),exit:p(32.4,20),entrySide:'left',exitSide:'right',
 items:[art(4.8,23,1.8,'Arrival screen protects the entry read and points toward the glass threshold'),bench(5.2,25.4),art(4.8,8.8),plinth(4.8,12.3),bench(6.6,15.4),installation(17,15.2,2.8),sculpture(13.3,20.7,1.7,'Opaque south shoulder before the exposed central crossing'),art(20.5,11.6,1.8,'North viewing shoulder is the last refuge before the study'),plinth(19.8,17.5),plinth(19.8,20.5),sculpture(28.6,15.8,2.4),plinth(30.3,18.4),bench(28.6,21.6),sculpture(14.7,4.8,1.7,'Study side sculpture frames objective approach without sealing it'),item('partition','gallery_masterpiece_wall',19,2.6,2,'Featured study back-wall directly supports the target'),
 {kind:'galleryGlassPanel',x:17,y:12.3,scale:4/1.4,collisionScale:4/1.4,reason:'North glazed enclosure edge; opaque end shoulders stay outside glass'},
 {kind:'galleryGlassPanel',x:17,y:18,scale:4/1.4,collisionScale:4/1.4,reason:'South glazed enclosure edge defines public viewing circulation'},
 {kind:'galleryGlassPanelVertical',x:15,y:18,scale:5.7/1.4,collisionScale:5.7/1.4,reason:'West glass architecture; bodies route around while cameras see through'},
 {kind:'galleryGlassPanelVertical',x:19,y:18,scale:5.7/1.4,collisionScale:5.7/1.4,reason:'East glass architecture separates two transparent viewing sides'}],
 guards:[g(1,'room',[[2.3,7.4],[7.5,7.4],[7.5,15.8],[2.3,15.8]]),g(2,'corridor',[[12.1,10.2],[21.6,10.2],[21.6,21.6],[12.1,21.6]]),g(4,'objective',[[13.1,2.1],[21.6,2.1],[21.6,5.7],[13.1,5.7]]),g(3,'exit',[[26.2,11.3],[31.7,11.3],[31.7,21.8],[26.2,21.8]])],
 cameras:[{zone:2,x:22.6,y:9.4,look:Math.PI*.75}],main:[p(9.5,22),p(12,19.3),p(12.4,11),p(17.5,8),p(21.6,5.8)],safe:[p(4.5,18),p(2.2,12),p(7.3,10.8),p(12.4,11),p(14,9.7),p(17.5,8),p(21.6,5.8)],risk:[p(9.5,22),p(21.5,21),p(21.5,14),p(17.5,8)],escape:[p(21.6,5.8),p(17.5,8),p(21.5,14),p(21.5,19.5),p(24,19.5),p(26.3,20)],alternate:[p(13.2,5.6),p(17.5,8),p(12,19.3),p(21.5,22),p(24,19.5),p(31.6,21.7)]},
 '02-10':{
 fantasy:'Infiltrate the grand arrival through a private exhibition choice, cross installation security into the dedicated masterpiece chamber, then escape through the portrait side galleries after the delayed high-security alarm.',
 zones:[z('Grand Arrival',15,25,11,7,'APPROACH: grand commissioned exhibit and comfortable read'),z('Private Exhibition',28,22,8,10,'INFILTRATION: longer sculpture bypass of direct crossing'),z('Security Crossing',12,14,14,9,'SECURITY LAYER: installation island, CCTV and timing choice'),z('Masterpiece Chamber',12,1,16,10,'OBJECTIVE: focused premium commissioned masterpiece'),z('Portrait Collection',1,2,9,10,'ESCAPE: intimate portrait collection breaks chamber LOS'),z('Side Gallery',1,14,9,9,'ESCAPE: second exhibition corner rather than an endless corridor'),z('Private Escape',1,25,11,7,'EXIT: final sheltered public viewing return')],
 links:[[19,22,3,4],[25,27,4,3],[25,20,7,3],[18,10,3,5],[9,5,4,3],[4,11,3,4],[5,22,3,4],[9,17,4,3]],entry:p(21,31.4),goal:p(23,4.5),exit:p(1.6,29),entrySide:'bottom',exitSide:'left',
 items:[sculpture(18.3,28.7,2.2,'Grand arrival landmark defines approach versus eastern private exhibition choice'),bench(23.6,29.5),installation(31.4,26.4,2.5),plinth(33.4,29.2),bench(30,30.6),installation(17.2,19.7,2.8),art(22.6,21.3,1.9,'Eastern junction shoulder supports a pause before camera crossing'),plinth(23.4,17),art(17,10,2.2,'Security threshold frames south entrance to commissioned chamber'),sculpture(15.5,7.6,2.4),sculpture(25.8,8.6,2),plinth(20.1,7.4),item('partition','gallery_masterpiece_wall',23,3.2,2.4,'Dedicated commissioned work behind cyan interaction case'),art(5,5.8,2,'Portrait exhibition spine is a real post-theft LOS break'),sculpture(6,10.3,1.8),bench(3.4,9.4),sculpture(5.8,18.8,2.4),plinth(7.5,21),art(8.8,28.4,2.2,'Final private-gallery screen permits timing the exit guard'),bench(5,30.6)],
 guards:[g(0,'room',[[16.4,26.4],[24.6,26.4],[24.6,30.9],[16.4,30.9]]),g(2,'corridor',[[13.2,15.3],[24.6,15.3],[24.6,21.8],[13.2,21.8]]),g(3,'objective',[[13.3,2.2],[26.5,2.2],[26.5,6.2],[23,6.5],[26.5,9.7],[13.3,9.7]]),g(4,'roaming',[[2.3,3.3],[8.7,3.3],[8.7,11],[5.5,12.5],[8.7,21.7],[2.3,21.7],[2.3,15.3],[5.5,12.5]]),g(6,'exit',[[2.3,26.3],[10.7,26.3],[10.7,30.8],[2.3,30.8]]),g(1,'roaming',[[29.2,23.3],[34.7,23.3],[34.7,30.8],[29.2,31.2]])],
 cameras:[{zone:3,x:27.6,y:1.4,look:Math.PI*.75},{zone:2,x:12.4,y:14.4,look:Math.PI*.25}],main:[p(20.5,24),p(20.5,18),p(19.5,12),p(23,8)],safe:[p(24.5,30.8),p(27,28),p(34.7,30.8),p(34.7,23.4),p(27,21),p(24.7,17),p(19.5,12),p(13.3,9.7)],risk:[p(20.5,24),p(20.5,16),p(19.5,12),p(23,8)],escape:[p(13.4,6.5),p(10.8,6.5),p(2.3,8),p(5.5,12.5),p(2.3,15.3),p(2.3,21.7),p(6.5,24),p(2.3,29)],alternate:[p(26.5,9.7),p(19.5,12),p(24.5,22),p(10.8,18.5),p(8.7,21.7),p(6.5,24),p(10.7,30.8)]},
 '03-08':{
 fantasy:'Read public access, infiltrate staff verification or the analyst bypass, cross a controlled security junction into monitoring command, then carry the command asset through the independent eastern audit exit.',
 zones:[z('Public Access',1,19,8,7,'APPROACH: bank arrival queue and initial planning'),z('Staff Checkpoint',11,19,9,7,'INFILTRATION: staffed credential gate'),z('Controlled Junction',11,9,12,8,'SECURITY LAYER: linked CCTV and command checkpoint'),z('Monitor Records Command',25,2,10,10,'OBJECTIVE: staffed security desks and monitored records'),z('East Verification',25,15,10,8,'ESCAPE: audit workcell and independent door'),z('Analysis Bypass',1,8,8,9,'INFILTRATION: longer cornered analyst route'),z('Restricted Observation',12,1,11,6,'SECURITY LAYER: reinforced northern access into command')],
 links:[[8,21,4,3],[3,16,3,4],[8,11,4,3],[14,16,3,4],[16,6,3,4],[22,4,4,3],[22,11,4,3],[29,11,3,5],[22,18,4,3]],entry:p(1.6,23),goal:p(30,8.8),exit:p(34.4,20),entrySide:'left',exitSide:'right',
 items:[bank('bankTellerCounter',5,22,'Public queue counter provides arrival read'),bank('bankQueueBarrier',5,24.7,'Queue establishes public/staff identity'),bank('bankSecurityGate',15.5,20.2,'Actual credential portal has passable center, opaque posts'),bank('bankOfficeDesk',15.5,23.5,'Verification desk watches the gateway'),bank('bankFilingCabinet',18,24.4,'Records refuge after access timing'),bank('bankSecurityCheckpoint',17,13.3,'Command island divides the hub into two clear junction shoulders'),bank('bankFilingCabinet',20.5,15.4,'East hub shelter before exposed camera crossing'),bank('bankFilingCabinet',21.3,15.4,'Joined hub record bank closes fake gap'),bank('bankOfficeDesk',4,11.3,'Analysis station supplies safer long access purpose'),bank('bankFilingCabinet',5.8,14.8,'Analyst records interrupt bypass sightline'),bank('bankVaultCorridorWall',17.5,4.3,'Restricted observation shoulder below security camera'),bank('bankSecurityCheckpoint',30,5.8,'Command monitoring island owns the restricted target'),bank('bankOfficeDesk',27.4,9.3,'West monitor analyst workcell'),bank('bankOfficeDesk',32.6,9.3,'East command analyst workcell'),bank('bankMonitor',27.7,3,'Wall-mounted monitoring ties CCTV to command room'),bank('bankMonitor',30,3,'Paired surveillance station links the objective to checkpoint monitoring'),bank('bankMonitor',32.3,3,'Records audit monitor gives the command desk a clear security subject'),bank('bankFilingCabinet',33.4,6.8,'Command secure-record bank flank'),bank('bankOfficeDesk',30,18.5,'East verification workstation'),bank('bankFilingCabinet',27.7,21.5,'Exit-side audit records chase break'),bank('bankCashCart',32.5,21.5,'Verified-record dispatch context')],
 guards:[g(1,'room',[[12.2,20.3],[18.8,20.3],[18.8,24.8],[12.2,24.8]]),g(2,'corridor',[[12.2,10.2],[21.6,10.2],[21.6,15.9],[12.2,15.9]]),g(3,'objective',[[26.2,3.2],[33.7,3.2],[33.7,10.7],[26.2,10.7]]),g(4,'exit',[[26.2,16.2],[33.7,16.2],[33.7,21.8],[26.2,21.8]]),g(6,'roaming',[[13.2,2.2],[21.7,2.2],[21.7,5.8],[13.2,5.8]])],
 cameras:[{zone:2,x:22.6,y:9.4,look:Math.PI*.75},{zone:4,x:34.6,y:15.4,look:Math.PI*.75}],main:[p(9.5,22.5),p(15.5,18),p(15.5,10.5),p(17.5,8),p(23.5,5.5),p(26,7.5)],safe:[p(3.5,18),p(2.2,14),p(8,12.5),p(12.2,11),p(23.5,12.5),p(26.3,10.7)],risk:[p(9.5,22.5),p(19,25.2),p(15.5,18),p(21.7,14),p(23.5,12.5)],escape:[p(33.7,10.7),p(30.5,13.5),p(33.7,16.3),p(33.7,20)],alternate:[p(26.3,10.7),p(23.5,12.5),p(21.8,16),p(23.5,19.5),p(26.3,20)]},
 '03-10':{
 fantasy:'Infiltrate staff access and the checkpoint, penetrate inner security and the reinforced antechamber into the actual Main Vault, then escape through a distinct eastern cash-processing and records-dispatch circuit after the delayed alarm.',
 zones:[z('Staff Access',1,24,8,7,'APPROACH: comfortable records planning pocket'),z('Security Checkpoint',11,24,10,7,'INFILTRATION: credential verification'),z('Inner Security',11,13,12,8,'SECURITY LAYER: staffed security junction'),z('Vault Antechamber',11,2,12,8,'SECURITY LAYER: reinforced entrance observation'),z('Main Vault',26,2,12,11,'OBJECTIVE: core asset inside actual vault chamber'),z('Cash Processing',28,16,10,9,'ESCAPE: operational alternate service circuit'),z('Dispatch Junction',23,28,15,7,'SECURITY ESCALATION: searched processing / records junction'),z('Records Evacuation',11,33,10,7,'EXIT: lateral records door, separate from staff entry')],
 links:[[8,26,4,3],[15,20,3,5],[16,9,3,5],[22,5,5,3],[31,12,3,5],[31,24,3,5],[20,34,4,3]],entry:p(1.6,28),goal:p(32,7.2),exit:p(11.6,37),entrySide:'left',exitSide:'left',
 items:[bank('bankOfficeDesk',5,27,'Staff authorization arrival desk and records planning pocket'),bank('bankFilingCabinet',7.1,29.5,'Entry records bank gives a sheltered planning pocket'),bank('bankSecurityGate',16,25.2,'Actual staff security portal'),bank('bankSecurityCheckpoint',16,28.4,'Credential verification island divides approach sides'),bank('bankSecurityCheckpoint',17,17.3,'Inner security hub with two pass directions'),bank('bankFilingCabinet',20.7,19.3,'Inner-security pause shoulder'),bank('bankFilingCabinet',21.5,19.3,'Connected record bank prevents fake gap'),bank('bankOfficeDesk',13.8,19.6,'Monitor analyst workstation explains the inner-security function'),bank('bankMonitor',17,14,'Wall monitoring linked to junction camera'),bank('bankVaultCorridorWall',17,6,'Reinforced antechamber island creates an observation decision'),bank('bankVaultDoor',22.3,5.7,'Reinforced threshold face makes vault passage readable without sealing gateway'),bank('bankMainVault',32,3.2,'Vault face against the northern architecture; objective is inside secure chamber'),bank('bankDepositBoxWall',28.7,7.1,'West vault deposit storage'),bank('bankDepositBoxWall',35.3,7.1,'East vault storage encloses the secure asset'),bank('bankSmallSafe',28.7,10.6,'West secure cell with approach clearance'),bank('bankSmallSafe',35.3,10.6,'East secure deposit cell belongs to the inner vault storage'),bank('bankCashProcessingTable',31,20.3,'Processing island west workstation'),bank('bankCashProcessingTable',33.1,20.3,'Connected east processing workstation'),bank('bankCashCart',35.8,22.5,'Sealed transfer context on service escape'),bank('bankFilingCabinet',29.2,23.4,'Processing corner interrupts pursuit'),bank('bankOfficeDesk',26.5,31,'Dispatch audit desk verifies the outbound cash-processing workflow'),bank('bankCashProcessingTable',31,31.5,'Cash dispatch checkpoint assembly'),bank('bankVaultCorridorWall',35.5,33.7,'Dispatch sheltered waiting shoulder before the exit dogleg'),bank('bankCashCart',33.9,29.6,'Escalation route belongs to cash dispatch'),bank('bankOfficeDesk',16,36,'Records evacuation approval workcell'),bank('bankFilingCabinet',18.3,38.5,'Final records bank offers a wait pocket before the exit guard'),bank('bankFilingCabinet',19.1,38.5,'Joined records refuge closes a deceptive cabinet gap'),bank('bankMonitor',16,34.3,'Dispatch monitoring connects the escape workroom to security')],
 guards:[g(1,'room',[[12.2,25.3],[19.7,25.3],[19.7,29.8],[12.2,29.8]]),g(2,'corridor',[[12.2,14.3],[21.7,14.3],[21.7,19.8],[12.2,19.8]]),g(3,'room',[[12.2,3.3],[21.7,3.3],[21.7,8.7],[12.2,8.7]]),g(4,'objective',[[27.3,4.8],[36.7,4.8],[36.7,11.8],[27.3,11.8]]),g(5,'room',[[29.2,17.3],[36.7,17.3],[36.7,23.8],[29.2,23.8]]),g(6,'corridor',[[24.2,29.3],[36.7,29.3],[36.7,34.4],[24.2,33.8]]),g(7,'exit',[[12.2,34.3],[19.7,34.3],[19.7,38.8],[12.2,38.8]])],
 cameras:[{zone:2,x:22.6,y:13.4,look:Math.PI*.75},{zone:3,x:11.4,y:2.4,look:Math.PI*.25},{zone:6,x:37.6,y:28.4,look:Math.PI*.75}],main:[p(9.5,27.5),p(16.5,22.5),p(16.5,12),p(21.7,8.5),p(24,6.5),p(27.3,8.8)],safe:[p(9.5,27.5),p(12.2,29.8),p(12.2,25.3),p(16.5,22.5),p(12.2,19.7),p(12.2,14.3),p(17.5,12),p(12.2,8.7),p(12.2,3.3),p(21.7,3.3),p(24,6.5),p(27.3,11.8)],risk:[p(9.5,27.5),p(16.5,22.5),p(16.5,12),p(16.5,8.3),p(24,6.5),p(32,10)],escape:[p(36.7,11.8),p(32.5,14.5),p(36.7,23.8),p(32.5,26.5),p(24.2,34),p(22,35.5),p(12.2,37)],alternate:[p(27.3,11.8),p(32.5,14.5),p(29.2,17.3),p(28.8,24.2),p(32.5,26.5),p(36.7,34.4),p(24.2,34),p(22,35.5),p(19.7,37)]},
};
// Joined workcells: physical roles are coherent assemblies, not isolated prop scatter.
V9_HEIST_PLANS['03-08'].items.push(
 bank('bankOfficeDesk',14.55,13.3,'West command workstation joined to the central security island'),bank('bankOfficeDesk',19.45,13.3,'East authorization workstation joined to the same island'),
 bank('bankOfficeDesk',27.55,5.8,'Command west workstation joined to monitoring checkpoint'),bank('bankOfficeDesk',32.45,5.8,'Command east workstation joined to monitoring checkpoint'),
 bank('bankOfficeDesk',6.2,11.3,'Second analyst station makes the bypass a real two-person analysis room'),bank('bankPaperwork',4,11.05,'Analyst desk record preparation'),bank('bankPaperwork',6.2,11.05,'Second analyst verification paperwork'),
 bank('bankMonitor',4,9,'Analysis office surveillance subject'),bank('bankMonitor',6.2,9,'Paired analyst terminal'),bank('bankFloorMarker',15.5,21.4,'Staff-only controlled access floor marking'),
 bank('bankOfficeDesk',32.1,18.5,'Paired eastern audit desk forms outbound verification workcell'),bank('bankPaperwork',30,18.25,'Verified document dispatch records'),bank('bankPaperwork',32.1,18.25,'Second outbound audit record'),bank('bankMonitor',30,16.1,'East verification monitoring point')
);
V9_HEIST_PLANS['03-10'].items.push(
 bank('bankOfficeDesk',13.55,28.4,'West credential station attached to staffed checkpoint'),bank('bankOfficeDesk',18.45,28.4,'East credential station attached to checkpoint assembly'),
 bank('bankOfficeDesk',14.55,17.3,'West operator bay joined to inner security command'),bank('bankOfficeDesk',19.45,17.3,'East operator bay joined to inner security command'),
 bank('bankOfficeDesk',14.65,6,'West vault authorization desk attached to reinforced antechamber island'),bank('bankOfficeDesk',19.35,6,'East inspection desk attached to the same reinforced island'),
 bank('bankDepositBoxWall',27.3,7.1,'Joined west vault deposit storage bank continues toward side wall'),bank('bankDepositBoxWall',36.7,7.1,'Joined east deposit bank completes the secure storage composition'),
 bank('bankOfficeDesk',31,18.2,'Cash reconciliation workstation above the processing assembly'),bank('bankOfficeDesk',33.1,18.2,'Paired outbound cash validation workstation'),
 bank('bankOfficeDesk',28.3,31,'Paired dispatch audit bay joins outgoing cash workflow'),bank('bankPaperwork',26.5,30.8,'Dispatch manifest lies on the authorization desk'),bank('bankPaperwork',28.3,30.8,'Paired manifest review at dispatch'),
 bank('bankMonitor',13.8,14.3,'Inner-security west wall terminal'),bank('bankMonitor',20.3,14.3,'Inner-security east wall terminal'),bank('bankMonitor',14,3.3,'Vault-antechamber authorization monitor'),bank('bankMonitor',20,3.3,'Vault-antechamber inspection terminal'),
 bank('bankFloorMarker',16,26.3,'Checkpoint access stripe'),bank('bankFloorMarker',32.5,15.5,'Cash service exit stripe'),bank('bankPaperwork',31,18,'Cash reconciliation records'),bank('bankPaperwork',33.1,18,'Outbound cash manifest'),bank('bankMonitor',31,16.7,'Processing supervisory terminal'),bank('bankMonitor',34.5,29.3,'Dispatch monitoring subject'),bank('bankPaperwork',16,35.8,'Final record authorization paperwork')
);
const GALLERY_WALL_COLLECTIONS:Record<string,{zone:number;asset:EnvironmentAssetId;x:number;y:number}[]>={
 '02-06':[
 {zone:0,asset:'gallery_abstract_frame_b',x:2.2,y:19.7},
 {zone:0,asset:'gallery_abstract_frame_c',x:7.3,y:19.7},
 {zone:1,asset:'gallery_abstract_frame',x:3,y:6.7},{zone:1,asset:'gallery_abstract_frame_d',x:6.8,y:6.7},
 {zone:2,asset:'gallery_abstract_frame_e',x:13,y:9.7},{zone:2,asset:'gallery_portrait_frame_c',x:20.5,y:9.7},
 {zone:3,asset:'gallery_portrait_frame_d',x:27,y:10.7},{zone:3,asset:'gallery_portrait_frame_e',x:31,y:10.7},
 {zone:4,asset:'gallery_portrait_frame_a',x:14,y:1.7},{zone:4,asset:'gallery_portrait_frame_b',x:21,y:1.7}],
 '02-10':[
 {zone:0,asset:'gallery_abstract_frame_c',x:17,y:25.7},{zone:0,asset:'gallery_abstract_frame_d',x:24,y:25.7},
 {zone:2,asset:'gallery_abstract_frame',x:24,y:14.7},{zone:1,asset:'gallery_abstract_frame_b',x:34,y:22.7},
 {zone:2,asset:'gallery_abstract_frame_e',x:14,y:14.7},
 {zone:3,asset:'gallery_portrait_frame_f',x:20.2,y:1.7},
 {zone:4,asset:'gallery_portrait_frame_a',x:3,y:2.7},{zone:4,asset:'gallery_portrait_frame_b',x:7.7,y:2.7},
 {zone:5,asset:'gallery_portrait_frame_c',x:3,y:14.7},{zone:5,asset:'gallery_portrait_frame_d',x:7.7,y:14.7},
 {zone:6,asset:'gallery_portrait_frame_e',x:3.5,y:25.7}],
};
function curateExhibits(def:StageDefinition,plan:Plan){
 if(def.chapter!==2)return;
 def.dressing=(GALLERY_WALL_COLLECTIONS[def.id]??[]).map((work,i)=>({id:`${def.id}: curated work ${i+1}`,zoneId:plan.zones[work.zone].name,identity:'Individually commissioned wall work and dedicated track light; no duplicate artwork in the mission',items:[{kind:'painting_wall',visualAssetId:work.asset,x:work.x,y:work.y,scale:work.asset.includes('portrait')?1.05:1.45},{kind:'spotlight_small',visualAssetId:'gallery_track_light',x:work.x,y:work.y-.1,scale:1.4},{kind:'plaque',x:work.x+1,y:work.y+.1}],light:{x:work.x,y:work.y+.5,radius:1.7,kind:'warm',intensity:.3}}));
}
function layout(plan:Plan){
 const rects=[...plan.zones.map(q=>[q.x,q.y,q.w,q.h]),...plan.links];const cols=Math.max(...rects.map(r=>r[0]+r[2]))+2,rows=Math.max(...rects.map(r=>r[1]+r[3]))+2,floor=new Set<string>();
 for(const[x,y,w,h]of rects)for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)floor.add(`${xx},${yy}`);
 return Array.from({length:rows},(_,y)=>Array.from({length:cols},(_,x)=>floor.has(`${x},${y}`)?'.':[-1,0,1].some(dy=>[-1,0,1].some(dx=>floor.has(`${x+dx},${y+dy}`)))?'#':' ').join(''));
}
export function authoredRoute(def:StageDefinition,via:Point[],radius=18){
 const stage=compileStage(def),nav=buildNavigation(stage,radius),out=[via[0]];
 for(const b of via.slice(1)){const a=out.at(-1)!;if(clearSegment(a.x*TILE,a.y*TILE,b.x*TILE,b.y*TILE,stage.movementBlockers,radius))out.push(b);else{const path=findPath(nav,a.x*TILE,a.y*TILE,b.x*TILE,b.y*TILE);if(path.length<2||Math.hypot(path.at(-2)!/TILE-b.x,path.at(-1)!/TILE-b.y)>.01)throw Error(`${def.id}: V9 unreachable ${b.x},${b.y} from ${a.x},${a.y} radius=${radius}`);for(let i=0;i<path.length;i+=2){const q=p(path[i]/TILE,path[i+1]/TILE);if(Math.hypot(q.x-out.at(-1)!.x,q.y-out.at(-1)!.y)>.01)out.push(q);}}}return out;
}
export function composeV9Heist(source:StageDefinition):StageDefinition{
 const plan=V9_HEIST_PLANS[source.id];if(!plan)return source;
 const def=structuredClone(source);def.layout=layout(plan);def.structurePlan=plan.fantasy+' | '+plan.zones.map(q=>q.name+': '+q.purpose).join(' → ');
 def.playerSpawn={...plan.entry,facing:plan.entrySide==='left'?0:plan.entrySide==='right'?Math.PI:plan.entrySide==='top'?Math.PI/2:-Math.PI/2};def.entryPosition={...plan.entry};def.exitPosition={...plan.exit};def.entryEdge=plan.entrySide;def.exitEdge=plan.exitSide;def.exit={x:plan.exit.x-.6,y:plan.exit.y-.6,w:1.2,h:1.2};def.objective={...source.objective!,...plan.goal};
 def.props=plan.items.map(({reason,...q})=>q);def.props.push({kind:'objectiveCase',visualAssetId:def.chapter===2?'gallery_low_pedestal':'bank_small_safe',...plan.goal,scale:1.8});def.dressing=[];def.carpets=[];def.patrolPlan=undefined;def.guards=[];def.patrolRoutes=[];
 def.lights=plan.items.filter(q=>['statue','partition','bankSecurityCheckpoint','bankCashProcessingTable','bankMainVault'].includes(q.kind)).map(q=>({x:q.x,y:q.y-1,radius:3,kind:'warm' as const,intensity:.44}));def.lights.push({...plan.goal,radius:2.7,kind:'cyan',intensity:.74},{x:plan.goal.x-1.2,y:plan.goal.y-1.4,radius:3.2,kind:'warm',intensity:.42});
 def.ambientDarkness=source.ambientDarkness;
 def.cameras=plan.cameras.map((q,i)=>({...source.cameras?.[Math.min(i,(source.cameras?.length??1)-1)]!,id:`${def.id}-cam${i+1}`,x:q.x,y:q.y,centerFacing:q.look,sweepAngle:.5,sweepSpeed:.35,pauseAtEnds:.6,range:5,visionAngle:.65,suspicionRate:.4}));
 const stage=compileStage(def),nav=buildNavigation(stage,BODY.guardRadius);
 const candidates=nav.walkable.flatMap((v,i)=>v?[p(nodeX(nav,i)/TILE,nodeY(nav,i)/TILE)]:[]).filter(q=>{const path=findPath(nav,plan.entry.x*TILE,plan.entry.y*TILE,q.x*TILE,q.y*TILE);return path.length>=2&&Math.hypot(path.at(-2)!/TILE-q.x,path.at(-1)!/TILE-q.y)<.01;});
 const anchors=plan.zones.map(zone=>candidates.filter(q=>q.x>zone.x+.8&&q.x<zone.x+zone.w-.8&&q.y>zone.y+.8&&q.y<zone.y+zone.h-.8).sort((a,b)=>Math.hypot(a.x-zone.x-zone.w/2,a.y-zone.y-zone.h/2)-Math.hypot(b.x-zone.x-zone.w/2,b.y-zone.y-zone.h/2))[0]);
 if(anchors.some(a=>!a))throw Error(def.id+': zone has no navigable security anchor');
 plan.guards.forEach((guard,i)=>{const inherited=source.guards[Math.min(i,source.guards.length-1)],id=`${def.id}-g${i+1}`,points=authoredRoute(def,[...guard.points,guard.points[0]],BODY.guardRadius).slice(0,-1),start=guard.points[0],next=guard.points[1];
 def.guards.push({...inherited,id,routeId:id,...start,role:guard.role,theftRole:guard.role==='room'?'zone':guard.role,facing:Math.atan2(next.y-start.y,next.x-start.x),initialFacing:Math.atan2(next.y-start.y,next.x-start.x),startDelay:i*.9,theftPosts:[anchors[guard.zone],anchors[(guard.zone+1)%anchors.length]],theftSearchSectors:[{id:`${id}: assigned ${plan.zones[guard.zone].name} circuit`,anchors:anchors.map((_,j)=>anchors[(j+i)%anchors.length])},{id:`${id}: objective and exit recheck`,anchors:[plan.goal,plan.exit]}]});
 def.patrolRoutes.push({id,mode:'loop',points:points.map(q=>({...q,waitDuration:guard.points.some(c=>Math.hypot(c.x-q.x,c.y-q.y)<.01)?guard.role==='objective'?1.5:.7:0,turnDuration:guard.points.some(c=>Math.hypot(c.x-q.x,c.y-q.y)<.01)?1.1:0,lookDirection:guard.role==='objective'?Math.atan2(plan.goal.y-q.y,plan.goal.x-q.x):undefined}))});});
 def.securityZones=plan.zones.map((q,i)=>({name:q.name,...anchors[i],radius:Math.min(q.w,q.h)/2,guardId:def.guards[plan.guards.findIndex(g=>g.zone===i)]?.id}));def.safeZones=[{...plan.entry,radius:.4}];def.objectiveZone={guardId:def.guards.find(g=>g.role==='objective')!.id,spotlight:true};
 def.testRoutes=[{name:'main: authored heist security sequence',points:authoredRoute(def,[plan.entry,...plan.main,plan.goal])},{name:'safe: longer exhibit / analyst shoulders',points:authoredRoute(def,[plan.entry,...plan.safe,plan.goal])},{name:'risk: exposed security crossings',points:authoredRoute(def,[plan.entry,...plan.risk,plan.goal])}];def.escapeRoutes=[{name:'escape: distinct post-theft exhibition / service circuit',points:authoredRoute(def,[plan.goal,...plan.escape,plan.exit])},{name:'escape: alternate security shoulders',points:authoredRoute(def,[plan.goal,...plan.alternate,plan.exit])}];
 const target=def.props.find(q=>q.visualAssetId===(def.chapter===2?'gallery_masterpiece_wall':'bank_main_vault'))??def.props.find(q=>q.kind==='bankMainVault')??def.props.find(q=>q.kind==='bankSecurityCheckpoint')!;def.landmark={name:plan.zones.find(q=>plan.goal.x>q.x&&plan.goal.x<q.x+q.w&&plan.goal.y>q.y&&plan.goal.y<q.y+q.h)!.name,kind:target.kind,x:target.x,y:target.y};
 curateExhibits(def,plan);
 return def;
}
