/** Clone-only probes. This runner never writes campaign maps. All values are [PLACEHOLDER] pending playtests. */
import fs from 'node:fs';
import type {StageDefinition} from '../../src/game/levels/StageDefinition';
import {auditDifficulty} from './chapterDifficultyAudit';
import {auditPressureMitigation} from './v101PressureMetrics';
const stages=JSON.parse(fs.readFileSync('Reports/V101/campaign-baseline.json','utf8')) as StageDefinition[];
const definitions=[
 {id:'02-05',name:'g2 Salon-to-Court crossing stop',reason:'Shift the existing Salon southern stop three tiles west to observe the shared crossing, leaving long periods when the guard walks the Salon loop.',edit:(d:StageDefinition)=>{const p=d.patrolRoutes[1].points[2];p.x=16.5;p.lookDirection=Math.PI/2;}},
 {id:'02-07',name:'g1 east shoulder crossing observation',reason:'Shift an existing moving eastern shoulder to observe the open crossing from its east side, with a brief periodic pause.',edit:(d:StageDefinition)=>{const p=d.patrolRoutes[0].points[2];p.x=19.5;p.y=16.5;p.waitDuration=.8;p.lookDirection=Math.PI;}},
 {id:'02-05',name:'g1 crossing stop moved west',reason:'Move the existing east stop two tiles into its own open Court crossing; observe west briefly, retain guard count and full southern circuit.',edit:(d:StageDefinition)=>{const p=d.patrolRoutes[0].points[1];p.x=17.5;p.lookDirection=Math.PI;}},
 {id:'02-07',name:'g1 modest crossing detour',reason:'The bottom leg makes one short detour toward the open approach, with a brief visible northward observation.',edit:(d:StageDefinition)=>{d.patrolRoutes[0].points.splice(4,0,{x:17.5,y:17.5,waitDuration:.8,lookDirection:-Math.PI/2,turnDuration:1.1});}},
 {id:'02-09',name:'g3 objective approach inspection shoulder',reason:'Move the existing moving shoulder to a collision-clear painting-side inspection position, with a short periodic pause; route then continues away.',edit:(d:StageDefinition)=>{const p=d.patrolRoutes[2].points[1];p.y=26.75;p.waitDuration=.8;p.lookDirection=Math.atan2(.25,-.75);}},
 {id:'01-04',name:'semantic g1 first pause face east',reason:'Adjust the actual semantic anchor so the lower-room guard looks across its room rather than dwelling on the narrow northern safe crossing.',edit:(d:StageDefinition)=>{d.patrolRoutes[0].points[0].lookDirection=0;d.patrolPlan!.anchors.find(a=>a.id==='0-0')!.look=0;d.guards[0].initialFacing=0;d.guards[0].facing=0;}},
 {id:'01-04',name:'semantic g2 second pause face north',reason:'The real upper-room semantic return pause stops dwelling across the western narrow approach while its travel still covers the junction.',edit:(d:StageDefinition)=>{d.patrolRoutes[1].points[1].lookDirection=-Math.PI/2;d.patrolPlan!.anchors.find(a=>a.id==='1-1')!.look=-Math.PI/2;}},
 {id:'02-05',name:'g1 west-facing crossing',reason:'The existing eastern stop observes the open Collector Court crossing before returning south.',edit:(d:StageDefinition)=>{d.patrolRoutes[0].points[1].lookDirection=Math.PI;}},
 {id:'02-05',name:'g1 west-facing crossing with brief observation',reason:'Same crossing, two short observations per patrol rather than a permanently exposed route.',edit:(d:StageDefinition)=>{d.patrolRoutes[0].points[1].lookDirection=Math.PI;d.patrolRoutes[0].points[1].waitDuration=1.6;}},
 {id:'02-07',name:'g1 bottom-leg north-facing observation',reason:'An existing patrol leg intersects the player crossing; one stop makes the guard visibly observe before passing.',edit:(d:StageDefinition)=>{const r=d.patrolRoutes[0];r.points.splice(4,0,{x:17.5,y:19,waitDuration:.8,lookDirection:-Math.PI/2,turnDuration:1.1});}},
 {id:'02-09',name:'g3 existing approach stop',reason:'The existing objective-side point already faces the approach, but has no pause. A brief pause creates an observable timing choice.',edit:(d:StageDefinition)=>{d.patrolRoutes[2].points[1].waitDuration=1.2;}},
 {id:'02-09',name:'g3 existing approach stop facing painting',reason:'Face the painting approach at a currently moving zero-wait point, rather than extending reach.',edit:(d:StageDefinition)=>{d.patrolRoutes[2].points[1].waitDuration=1.2;d.patrolRoutes[2].points[1].lookDirection=Math.atan2(27-24.75,18.5-19.25);}},
 {id:'01-04',name:'g1 first pause face east',reason:'The lower-room guard observes its room wall-side instead of holding the northern safe crossing during its long pause.',edit:(d:StageDefinition)=>{d.patrolRoutes[0].points[0].lookDirection=0;d.guards[0].initialFacing=0;d.guards[0].facing=0;}},
 {id:'01-04',name:'g2 second pause face north',reason:'The upper-room return pause stops sweeping west across the narrow approach; travel still observes the crossing.',edit:(d:StageDefinition)=>{d.patrolRoutes[1].points[1].lookDirection=-Math.PI/2;}},
 {id:'01-04',name:'g3 delay 4 to 6',reason:'Separate the objective guard startup phase without reducing reach or route patrol.',edit:(d:StageDefinition)=>{d.guards[2].startDelay=6;}},
 {id:'01-08',name:'g3 eastern pause face south',reason:'The objective-side guard keeps its patrol but observes the checkpoint approach during its eastern pause instead of dwelling on pickup.',edit:(d:StageDefinition)=>{d.patrolRoutes[2].points[1].lookDirection=Math.PI/2;}},
 {id:'01-08',name:'g3 western pause face south',reason:'A single pickup-facing dwell becomes a checkpoint-facing dwell; travel continues scanning the objective room.',edit:(d:StageDefinition)=>{d.patrolRoutes[2].points[0].lookDirection=Math.PI/2;}},
 {id:'01-08',name:'g3 startDelay 1.6 to 4.6',reason:'Offset objective/checkpoint patrol phase without changing permanent security reach.',edit:(d:StageDefinition)=>{d.guards[2].startDelay=4.6;}},
];
const baseline=new Map<string,ReturnType<typeof metrics>>();
function metrics(d:StageDefinition){const a=auditDifficulty(d),m=auditPressureMitigation(d);return{guardCoverage:a.guardCoverage,overlap:a.overlap,safeRouteExposure:a.safeRouteExposure,objectivePressure:a.objectivePressure,objectiveApproach:m.patrol.objectiveApproachExposure,searchObjectiveApproach:m.search.objectiveApproachExposure,guardCrossings:m.patrol.patrolCrossingsNearSafeRoutePerMinute,timingWindow:m.patrol.safeRouteMedianLongestWindowSeconds,escape:m.search.routes.map(r=>({name:r.name,exposure:r.exposure,collisionClear:r.collisionClear}))};}
function differences(a:unknown,b:unknown,p=''): {field:string;before:unknown;after:unknown}[]{if(JSON.stringify(a)===JSON.stringify(b))return[];if(a&&b&&typeof a==='object'&&typeof b==='object'){const keys=new Set([...Object.keys(a),...Object.keys(b)]);return [...keys].flatMap(k=>differences((a as Record<string,unknown>)[k],(b as Record<string,unknown>)[k],p?`${p}.${k}`:k));}return[{field:p,before:a??null,after:b??null}];}
const results=definitions.map(p=>{const source=stages.find(d=>d.id===p.id)!;if(!baseline.has(p.id))baseline.set(p.id,metrics(source));const clone=structuredClone(source);p.edit(clone);console.log(p.id,p.name);return{id:p.id,name:p.name,rationale:p.reason,changedFields:differences(source,clone),baseline:baseline.get(p.id),candidate:metrics(clone),status:'CLONE_PROPOSAL_NOT_APPLIED_OR_SIMULATOR_VERIFIED'};});
fs.writeFileSync('Reports/V101/pressure-proposals.json',JSON.stringify({method:'Same independent pressure metrics, frozen baseline, cloned data only. Values [PLACEHOLDER]. No weighted score or map writes. Search may be unchanged when patrol-only edits affect pre-theft behavior.',results},null,2)+'\n');
