/** Fixed matched whole-heist replay matrix. Uses the existing route runner unchanged. No tuning/weights/bot edits. */
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import type {StageDefinition} from '../../src/game/levels/StageDefinition';
import {exposureRun} from './cameraExposure';
const delays=[0,1,2,3,5,8] as const;
const modes=[1,2] as const;
const read=(p:string)=>(JSON.parse(fs.readFileSync(p,'utf8')) as StageDefinition[]).filter(d=>(d.chapter??0)>=1&&(d.chapter??0)<=3);
const baseline=read('Reports/V101/campaign-baseline.json'),final=read('src/game/levels/stages/campaignStages.json');
const hash=(d:StageDefinition)=>createHash('sha256').update(JSON.stringify(d)).digest('hex');
function cases(d:StageDefinition){const routes=(d.testRoutes??[]).flatMap((r,index)=>/^(main|safe):/.test(r.name)?[{index,name:r.name}]:[]);return routes.flatMap(r=>[0,1].filter(escape=>!!d.escapeRoutes?.[escape]).flatMap(escape=>modes.flatMap(mode=>delays.map(delay=>({route:r.index,routeName:r.name,escape,escapeName:d.escapeRoutes![escape].name,mode,delay})))));}
type Run=ReturnType<typeof exposureRun> & {route:number;routeName:string;escape:number;escapeName:string;mode:number;delay:number};
function aggregate(runs:Run[]){const n=runs.length;return{runs:n,clearRate:runs.filter(r=>r.clear).length/n,failureRate:runs.filter(r=>!r.clear).length/n,caughtRate:runs.filter(r=>r.caught).length/n,timeoutRate:runs.filter(r=>!r.clear&&!r.caught).length/n,spottedRate:runs.filter(r=>!!r.spottedBy).length/n,cctvAlertRate:runs.filter(r=>r.cameraAlertAt!==null).length/n,meanMaxContinuousCctvExposureSeconds:runs.reduce((sum,r)=>sum+Math.max(0,...r.cameras.map(c=>c.longest)),0)/n,meanTimeSeconds:runs.reduce((sum,r)=>sum+r.time,0)/n};}
type Aggregate=ReturnType<typeof aggregate>;
type Mission={id:string;chapter:number;sourceHash:string;aggregate:Aggregate;routes:{route:number;name:string;aggregate:Aggregate}[];runs:Run[];reusedIdenticalBaseline:boolean};
const result:{baseline:Mission[];final:Mission[]}={baseline:[],final:[]};
const method={matrix:{delays,modes:[{code:1,entry:'Sneak',escape:'Run'},{code:2,entry:'Walk',escape:'Run'}],routes:'All authored main: and safe: references only, no risk or new paths',escapes:[0,1],durationCapSeconds:150,dt:'1/60'},runner:'Existing cameraExposure.exposureRun, unchanged. It continuously follows authored waypoints, switches to Run for escape and supplies normal target input. No teleports, guards skipped, forced pickup or forced clear.',aggregation:'First average all fixed applicable route/escape/mode/delay cases within each mission; then equal-weight mission means/medians per chapter. Exact-identical final definitions reuse their baseline cases.',exposure:'Spotted-run and CCTV-alert incidence plus mean maximal continuous CCTV exposure. This runner does not return guard visible-time fraction.',limitations:'Scripted phase sensitivity and collision/waypoint timeouts are reported separately; timeout does not prove security difficulty. Includes only fixed initial waiting, not adaptive cover waits. Runtime replay is not native simulator certification.',weights:'No composite weighted score. Independent clear/failure/spotted/CCTV axes.'};
function chapters(missions:Mission[]){const keys=Object.keys(missions[0]?.aggregate??{}).filter(k=>k!=='runs') as (keyof Aggregate)[];return[1,2,3].map(chapter=>{const rows=missions.filter(m=>m.chapter===chapter);return{chapter,missions:rows.length,runs:rows.reduce((n,r)=>n+r.aggregate.runs,0),axes:Object.fromEntries(keys.map(k=>{const values=rows.map(r=>r.aggregate[k]).sort((a,b)=>a-b),mid=Math.floor(values.length/2);return[k,{mean:values.reduce((n,v)=>n+v,0)/values.length,median:values.length%2?values[mid]:(values[mid-1]+values[mid])/2}];}))};});}
function save(){fs.writeFileSync('Reports/V101/matched-heist-pressure.json',JSON.stringify({method,complete:result.final.length===final.length,baseline:{missions:result.baseline,chapters:chapters(result.baseline)},final:{missions:result.final,chapters:chapters(result.final)},humanSimulatorVerified:false},null,2)+'\n');}
for(const original of baseline){const current=final.find(d=>d.id===original.id)!;const attempts=cases(original);const runs=attempts.map(c=>({...c,...exposureRun(original,c.route,c.escape,c.mode,c.delay)}));const aggregateOriginal=aggregate(runs);const base={id:original.id,chapter:original.chapter!,sourceHash:hash(original),aggregate:aggregateOriginal,routes:[...new Set(runs.map(r=>r.route))].map(route=>({route,name:runs.find(r=>r.route===route)!.routeName,aggregate:aggregate(runs.filter(r=>r.route===route))})),runs,reusedIdenticalBaseline:false};result.baseline.push(base);
 const same=hash(original)===hash(current);const currentRuns=same?runs:cases(current).map(c=>({...c,...exposureRun(current,c.route,c.escape,c.mode,c.delay)}));result.final.push({...base,sourceHash:hash(current),aggregate:aggregate(currentRuns),routes:[...new Set(currentRuns.map(r=>r.route))].map(route=>({route,name:currentRuns.find(r=>r.route===route)!.routeName,aggregate:aggregate(currentRuns.filter(r=>r.route===route))})),runs:currentRuns,reusedIdenticalBaseline:same});save();console.log(JSON.stringify({id:original.id,baseline:aggregateOriginal,final:result.final.at(-1)!.aggregate,reused:same}));}
save();
