/** V13 Phase 2 — Chapter 3 Bank (MEDIUM). Layered security: public floor, staff floor, strong room. Guards are authored last. */
import type {V13Mission} from './v13Types';
import {phase7} from './v13Phase7';

/**
 * 03-01 Lobby / Teller — the counter line.
 * The teller wall splits the bank into the public hall and the staff floor. The staff gate at the east end
 * is the safe way behind the counters; the counter flap by the cash room is the short way, under the hall camera.
 */
const M0301:V13Mission={
 id:'03-01',title:'Lobby / Teller',family:'Bank',topology:'Counter line: one wall, two ways through',
 map:[
  '##########################',
  '#cc#cccc#mmmmmmm#rrrrrrrr#',
  '#cc#ccccmmmmmmmmrrrrrrrrr#',
  '#cccccccmmmmmmmmrrrrrrrrr#',
  '#cccccccmmmmmmmmrrrrrrrrr#',
  '#ccccccc#mmmmmmm#rrrrrrrr#',
  '#####ccc##############sss#',
  '#ttttttttttttttt#ssssssss#',
  '#tttttttttttttttsssssssss#',
  '#tttttttttttttttsssssssss#',
  '#tttttttttttttttsssssssss#',
  '#ttttttttttttttt#ssssssss#',
  '#####ttt####ttt###########',
  '#hhhhhhhhhhhhhhhhhhhhhhhh#',
  '#hhhhhhhhhhhhhhhhhhhhhhhh#',
  '#hhhhhhhhhhhhhhhhhhhhhhhh#',
  '#hhhhhhhhhhhhhhhhhhhhhhhh#',
  '#hhhhhhhhhhhhhhhhhhhhhhhh#',
  '#hhhhhhhhhhhhhhhhhhhhhhhh#',
  '#hhhhhhhhhhhhhhhhhhhhhhhh#',
  '##########################',
 ],
 zones:{
  h:{id:'hall',name:'Banking Hall',role:'public',purpose:'Arrival; the counter line and its two ways through are read from here',hub:{x:12.5,y:17.9}},
  t:{id:'tellerFloor',name:'Teller Floor',role:'restricted',purpose:'Staff side of the counters: north lane behind the partitions, south lane walked by the floor guard',hub:{x:12,y:8}},
  c:{id:'cashRoom',name:'Teller Cash Room',role:'objective',purpose:'Cash safe in the west bay behind the wall pier',hub:{x:5.5,y:3.5}},
  m:{id:'manager',name:'Manager Office',role:'escape',purpose:'Way out after lockdown; the cash room guard stands here between inspections',hub:{x:12,y:4.75}},
  r:{id:'records',name:'Deposit Records',role:'escape',purpose:'Way round to the staff exit behind the deposit box walls',hub:{x:18,y:3.5}},
  s:{id:'staffExit',name:'Staff Exit',role:'escape',purpose:'Exit; its door from the teller floor closes at lockdown',hub:{x:20,y:8.4}},
 },
 entry:{x:12.5,y:18.8},objective:{x:2,y:2.6},exit:{x:23.8,y:9.5},entryEdge:'bottom',exitEdge:'right',
 placement:['bottom-centre','top-left','right-centre'],
 edges:[
  {from:'hall',to:'tellerFloor',role:'approach',via:[{x:13.5,y:12.5},{x:13.5,y:8}]},
  {from:'tellerFloor',to:'cashRoom',role:'approach',door:{at:{x:6.5,y:6.5},orientation:'horizontal',style:'bankSecurity4c'}},
  {from:'hall',to:'tellerFloor',role:'risk',via:[{x:6.5,y:12.5},{x:6.5,y:8}]},
  {from:'tellerFloor',to:'staffExit',role:'quickEscape',via:[{x:14.6,y:8},{x:14.6,y:9.5},{x:16.5,y:9.5}],door:{at:{x:16.5,y:9.5},orientation:'vertical',lockdown:true}},
  {from:'cashRoom',to:'manager',role:'alternateEscape',via:[{x:8.5,y:3.5},{x:9.6,y:3.5},{x:9.6,y:4.75}]},
  {from:'manager',to:'records',role:'alternateEscape',via:[{x:14.8,y:4.75},{x:14.8,y:3.5},{x:16.5,y:3.5}]},
  {from:'records',to:'staffExit',role:'alternateEscape',via:[{x:18,y:4.9},{x:23.5,y:4.9},{x:23.5,y:6.5}]},
 ],
 approach:['hall','tellerFloor','cashRoom'],risk:['hall','tellerFloor','cashRoom'],
 quickEscape:['cashRoom','tellerFloor','staffExit'],alternateEscape:['cashRoom','manager','records','staffExit'],
 cover:{safe:['Hall Checkpoint','Teller Counter East','Teller Partition East','Teller Partition West'],risk:['Teller Counter West','Teller Partition West'],escape:['Cash Room Pier','Teller Partition East','Teller Counting Machine','Staff Exit Column','Manager Desk','Records Box Wall']},
 structures:[
  {name:'Teller Counter West',roles:['divider','losBreak'],kind:'bankTellerCounter',asset:'bank_teller_counter',x:2.95,y:13.553,scale:1.3},
  {name:'Teller Counter Mid',roles:['divider','losBreak'],kind:'bankTellerCounter',asset:'bank_teller_counter',x:10,y:13.553,scale:1.3},
  {name:'Teller Counter East',roles:['divider','losBreak','hiding'],kind:'bankTellerCounter',asset:'bank_teller_counter',x:16.95,y:13.553,scale:1.3},
  {name:'Teller Counter Far East',roles:['divider'],kind:'bankTellerCounter',asset:'bank_teller_counter',x:20.85,y:13.553,scale:1.3},
  {name:'Hall Checkpoint',roles:['hiding','losBreak'],kind:'bankSecurityCheckpoint',asset:'bank_security_checkpoint',x:18,y:17,scale:1.2},
  {name:'Hall Security Desk',roles:['hiding','losBreak','divider'],kind:'bankSecurityDesk',asset:'bank_security_desk',x:2.8,y:16.8,scale:1.2},
  {name:'Hall ATM Bank',roles:['hiding','losBreak','divider'],kind:'bankAtmBank',asset:'bank_atm_bank',x:23.7,y:16.3,scale:1.3},
  {name:'Hall Column',roles:['hiding','losBreak','divider'],kind:'bankMarbleColumn',asset:'bank_marble_column',x:8.5,y:17.2,scale:1},
  {name:'Entrance Gate',roles:['threshold','divider'],kind:'bankSecurityGate',asset:'bank_security_gate',x:13.5,y:14.39,scale:1.25},
  {name:'Staff Exit Plant',roles:['decor'],kind:'bankPlant',asset:'bank_plant',x:24.65,y:7.315,scale:1.4},
  {name:'Hall Plant',roles:['decor'],kind:'bankPlant',asset:'bank_plant',x:24.65,y:13.315,scale:1.4},
  {name:'Teller Partition East',roles:['losBreak','hiding'],kind:'bankWall',asset:'bank_wall',x:9.5,y:9.6,scale:1},
  {name:'Teller Partition West',roles:['losBreak','hiding'],kind:'bankWall',asset:'bank_wall',x:4.5,y:9.6,scale:1},
  {name:'Teller Counting Machine',roles:['hiding','losBreak','divider'],kind:'bankCountingMachine',asset:'bank_counting_machine',x:11.9,y:9.6,scale:1.2},
  {name:'Staff Exit Column',roles:['hiding','losBreak'],kind:'bankMarbleColumn',asset:'bank_marble_column',x:21.5,y:9.5,scale:1},
  {name:'Teller Floor Clock',roles:['decor'],kind:'bankClock',asset:'bank_clock',x:11,y:7.6,scale:1.4},
  {name:'Hall Floor Marker',roles:['decor'],kind:'bankFloorMarker',asset:'bank_floor_marker',x:12.5,y:17.75,scale:1.2},
  {name:'Manager Monitor',roles:['decor'],kind:'bankMonitor',asset:'bank_monitor',x:10.5,y:1.6,scale:1.4},
  {name:'Cash Room Box Wall',roles:['sightline'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:5.5,y:1.357,scale:1.3},
  {name:'Manager Desk',roles:['divider','hiding'],kind:'bankOfficeDesk',asset:'bank_office_desk',x:12,y:3.2,scale:1.5},
  {name:'Manager Cabinet',roles:['losBreak','decor'],kind:'bankFilingCabinet',asset:'bank_filing_cabinet',x:15.4,y:1.488,scale:1.5},
  {name:'Records Box Wall',roles:['hiding','losBreak'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:18.5,y:1.357,scale:1.3},
  {name:'Records Box Wall East',roles:['hiding'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:21,y:3.6,scale:1.3},
 ],
 walls:[{name:'Teller Wall',roles:['divider','losBreak'],at:'wall between the Banking Hall and the Teller Floor, with the counter flap and the staff gate'},{name:'Cash Room Pier',roles:['losBreak','hiding','divider'],at:'pier closing the safe bay of the Teller Cash Room'}],
 guards:[
  {role:'lobby',zone:'hall',watches:'The two ways through the counter line: the flap from the west post, the staff gate from the east post',
   stops:[{x:6.5,y:15.25,look:{x:6.5,y:12.5},wait:3},{x:13.5,y:15.25,look:{x:13.5,y:12.5},wait:3}]},
  {role:'restricted',zone:'tellerFloor',watches:'The south lane of the Teller Floor: the cash room door from the west post, the staff gate from the east post',
   stops:[{x:3,y:10.75,look:{x:6.5,y:7.5},wait:3},{x:9.5,y:10.75,look:{x:13.5,y:11},wait:3}]},
  {role:'escape',zone:'staffExit',watches:'The way out: the teller floor door from the Staff Exit post, then the south lane of Deposit Records',
   stops:[{x:19.5,y:10.6,look:{x:17.2,y:9.5},wait:2},{x:23.3,y:8,look:{x:23.3,y:5},wait:0},{x:23.3,y:4.7,look:{x:19,y:4.9},wait:6}]},
  {role:'objective',zone:'cashRoom',watches:'The cash safe; between inspections stands in the Manager Office',
   stops:[{x:2.75,y:4.25,look:{x:2,y:2.6},wait:2},{x:11,y:4.75,look:{x:15.5,y:4.5},wait:5}]},
 ],
 cameras:[{zone:'hall',at:{x:6.5,y:13.4},facing:1.5708,watches:'The hall floor in front of the counter flap'}],
 objectiveAsset:'bank_small_safe',objectiveScale:1.15,secureDoorStyle:'bankSecurity4c',
};

/**
 * 03-02 Staff Offices — cubicle zigzag.
 * The open office is a row of cubicles: a north lane behind the partitions and a south lane the office guard walks.
 * The short way drops through the staff pool under its camera; both end in the supervisor office above the records room.
 */
const M0302:V13Mission={
 id:'03-02',title:'Staff Offices',family:'Bank',topology:'Zigzag through cubicles',
 map:[
  '########################',
  '#eeeee#oooooooooooooooo#',
  '#eeeeeooooooooooooooooo#',
  '#eeeeeooooooooooooooooo#',
  '#eeeeeooooooooooooooooo#',
  '#eeeee#oooooooooooooooo#',
  '#######oooooooooooooooo#',
  '#######oooooooooooooooo#',
  '#########ppp#######sss##',
  '#ccccc#ppppppppp#ssssss#',
  '#cccccppppppppppsssssss#',
  '#cccccppppppppppsssssss#',
  '#cccccppppppppppsssssss#',
  '#ccccc#ppppppppp#ssssss#',
  '##xxx####fff#####vvv####',
  '#xxxxx#ffffffff#vvvvvvv#',
  '#xxxxx#ffffffff#vvvvvvv#',
  '#xxxxxxffffffffvvvvvvvv#',
  '#xxxxxxffffffffvvv#vvvv#',
  '#xxxxxxffffffffvvv#vvvv#',
  '#xxxxx#ffffffff#vv#vvvv#',
  '########################',
 ],
 zones:{
  e:{id:'entrance',name:'Staff Entrance',role:'public',purpose:'Arrival past the badge checkpoint'},
  o:{id:'office',name:'Open Office',role:'public',purpose:'Cubicle row: north lane behind the partitions, south lane walked by the office guard',hub:{x:12.4,y:2.9}},
  p:{id:'pool',name:'Staff Pool',role:'transition',purpose:'Short cut under the camera, across the pool guard\'s walk',hub:{x:13.9,y:9.75}},
  s:{id:'supervisor',name:'Supervisor Office',role:'restricted',purpose:'Both lanes meet here above the records room door',hub:{x:19.5,y:12.5}},
  v:{id:'records',name:'Records Room',role:'objective',purpose:'Records safe in the east bay behind the wall pier',hub:{x:16.75,y:16.5}},
  f:{id:'files',name:'File Corridor',role:'escape',purpose:'Quick way west to the stairs; its stair door closes at lockdown',hub:{x:12.5,y:16.5}},
  c:{id:'copy',name:'Copy Room',role:'escape',purpose:'Way round to the stairs after lockdown'},
  x:{id:'stairs',name:'Staff Stairs',role:'escape',purpose:'Exit',hub:{x:3,y:16.6}},
 },
 entry:{x:2.2,y:3.5},objective:{x:21.5,y:19.3},exit:{x:2.2,y:18.5},entryEdge:'left',exitEdge:'left',
 placement:['top-left','bottom-right','bottom-left'],
 edges:[
  {from:'entrance',to:'office',role:'approach',via:[{x:6.5,y:2.9}]},
  {from:'office',to:'supervisor',role:'approach',via:[{x:22.25,y:2.9},{x:22.25,y:6.25},{x:20.5,y:6.25},{x:20.5,y:8.5}]},
  {from:'supervisor',to:'records',role:'approach',door:{at:{x:18.5,y:14.5},orientation:'horizontal',style:'bankSecurity4c'}},
  {from:'office',to:'pool',role:'risk',via:[{x:12.4,y:6.25},{x:10.5,y:6.25},{x:10.5,y:9.75}]},
  {from:'pool',to:'supervisor',role:'risk',door:{at:{x:16.5,y:11.5},orientation:'vertical',lockdown:true}},
  {from:'records',to:'files',role:'quickEscape',via:[{x:15.5,y:18.5}]},
  {from:'files',to:'stairs',role:'quickEscape',via:[{x:6.5,y:18.5},{x:5.2,y:18.5},{x:5.2,y:16.6}],door:{at:{x:6.5,y:18.5},orientation:'vertical',lockdown:true}},
  {from:'records',to:'files',role:'alternateEscape',via:[{x:15.5,y:18.5}]},
  {from:'files',to:'pool',role:'alternateEscape',via:[{x:10.5,y:14.5},{x:10.5,y:13},{x:13.9,y:13}]},
  {from:'pool',to:'copy',role:'alternateEscape',via:[{x:6.5,y:11.5}]},
  {from:'copy',to:'stairs',role:'alternateEscape',via:[{x:3.5,y:14.5}]},
 ],
 approach:['entrance','office','supervisor','records'],risk:['entrance','office','pool','supervisor','records'],
 quickEscape:['records','files','stairs'],alternateEscape:['records','files','pool','copy','stairs'],
 cover:{safe:['Badge Checkpoint','Cubicle Partition West','Cubicle Partition East','Supervisor Desk'],risk:['Cubicle Partition West','Pool Deposit Island'],escape:['Records Pier','File Cabinet Row A','Stairs Column','Pool Deposit Island','Copy Table']},
 structures:[
  {name:'Badge Checkpoint',roles:['threshold','hiding'],kind:'bankSecurityCheckpoint',asset:'bank_security_checkpoint',x:2.92,y:1.51,scale:1.2},
  {name:'Cubicle Partition West',roles:['losBreak','hiding','divider'],kind:'bankWall',asset:'bank_wall',x:10,y:4.5,scale:1},
  {name:'Cubicle Brass Screen',roles:['divider','sightline'],kind:'bankBrassScreen',asset:'bank_brass_screen',x:14.75,y:4.5,scale:1.034},
  {name:'Cubicle Partition East',roles:['losBreak','hiding','divider'],kind:'bankWall',asset:'bank_wall',x:19.5,y:4.5,scale:1},
  {name:'Cubicle Desk West',roles:['losBreak','decor'],kind:'bankOfficeDesk',asset:'bank_office_desk',x:9.6,y:1.495,scale:1.1},
  {name:'Cubicle Cabinet A',roles:['losBreak','decor'],kind:'bankFilingCabinet',asset:'bank_filing_cabinet',x:14,y:1.488,scale:1.5},
  {name:'Cubicle Cabinet B',roles:['losBreak','decor'],kind:'bankFilingCabinet',asset:'bank_filing_cabinet',x:15.2,y:1.488,scale:1.5},
  {name:'Cubicle Desk East',roles:['losBreak','decor'],kind:'bankOfficeDesk',asset:'bank_office_desk',x:19.6,y:1.495,scale:1.1},
  {name:'Office Cabinet',roles:['losBreak','decor'],kind:'bankFilingCabinet',asset:'bank_filing_cabinet',x:22.4,y:1.488,scale:1.5},
  {name:'Office Clock',roles:['decor'],kind:'bankClock',asset:'bank_clock',x:12.1,y:1.6,scale:1.4},
  {name:'Pool Deposit Island',roles:['hiding','losBreak','divider'],kind:'bankDepositIsland',asset:'bank_deposit_island',x:11.3,y:12,scale:0.8},
  {name:'Supervisor Desk',roles:['hiding','divider'],kind:'bankOfficeDesk',asset:'bank_office_desk',x:18.275,y:9.675,scale:1.5},
  {name:'Supervisor Safe',roles:['losBreak','decor'],kind:'bankSmallSafe',asset:'bank_small_safe',x:22.44,y:9.455,scale:1.4},
  {name:'Records Box Wall',roles:['sightline'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:21.75,y:15.357,scale:1.3},
  {name:'File Box Wall',roles:['hiding'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:13.5,y:15.357,scale:1.3},
  {name:'File Cabinet Row A',roles:['hiding','losBreak','divider'],kind:'bankFilingCabinet',asset:'bank_filing_cabinet',x:9.9,y:18.5,scale:1.5},
  {name:'File Cabinet Row B',roles:['hiding','losBreak','divider'],kind:'bankFilingCabinet',asset:'bank_filing_cabinet',x:11.1,y:18.5,scale:1.5},
  {name:'Copy Table',roles:['divider'],kind:'bankCashProcessingTable',asset:'bank_cash_processing_table',x:3,y:9.7,scale:1.4},
  {name:'Stairs Plant',roles:['decor'],kind:'bankPlant',asset:'bank_plant',x:1.4,y:15.3,scale:1.4},
  {name:'Stairs Column',roles:['hiding','losBreak'],kind:'bankMarbleColumn',asset:'bank_marble_column',x:3.9,y:18.5,scale:1},
 ],
 walls:[{name:'Records Pier',roles:['losBreak','hiding','divider'],at:'pier closing the safe bay of the Records Room'}],
 guards:[
  {role:'lobby',zone:'office',watches:'The south lane of the Open Office: the pool opening from the west post, the supervisor opening from the east post',
   stops:[{x:8.5,y:6.25,look:{x:10.5,y:8.5},wait:3},{x:18,y:6.25,look:{x:20.5,y:8.5},wait:3}]},
  {role:'crossing',zone:'pool',watches:'The Staff Pool crossing: the office opening from the north post, the file corridor opening from the south post',
   stops:[{x:12.75,y:9.25,look:{x:10.5,y:8.75},wait:3},{x:12.75,y:13,look:{x:10.5,y:14},wait:3}]},
  {role:'escape',zone:'stairs',watches:'The way out: the file corridor door from the stair post, then the pool opening from the Copy Room',
   stops:[{x:3,y:16,look:{x:5.6,y:18.3},wait:3},{x:3,y:11.2,look:{x:5.6,y:11.2},wait:4}]},
  {role:'objective',zone:'records',watches:'The records safe; between inspections walks up to the Staff Pool',
   stops:[{x:21.25,y:17.25,look:{x:21.5,y:19.3},wait:2},{x:15.25,y:11.5,look:{x:11.5,y:11.5},wait:5}]},
 ],
 cameras:[{zone:'pool',at:{x:8,y:13.4},facing:-0.9,watches:'The pool floor below the office opening'}],
 objectiveAsset:'bank_small_safe',objectiveScale:1.15,secureDoorStyle:'bankSecurity4c',
};

/**
 * 03-03 Cash Processing — ring around the counting cage.
 * The cage door faces away from the entrance, so the thief goes round: the north half under the camera
 * behind the sorting partition, or the south half the floor guard walks.
 */
const M0303:V13Mission={
 id:'03-03',title:'Cash Processing',family:'Bank',topology:'Ring around a central cage',
 map:[
  '#########################',
  '#####nnnnnnnnnnnnnn#xxxx#',
  '#####nnnnnnnnnnnnnnxxxxx#',
  '#####nnnnnnnnnnnnnnxxxxx#',
  '#####nnnnnnnnnnnnnnxxxxx#',
  '#####www########ttt#kkkk#',
  '#####www#vvv#vv#ttt#kkkk#',
  '#####www#vvv#vv#ttt#kkkk#',
  '#eee#www#vvvvvvvttt#kkkk#',
  '#eeeewww#vvvvvvvttt#kkkk#',
  '#eeeewww#vvvvvvvttt#kkkk#',
  '#eeeewww#vvvvvv#ttt#kkkk#',
  '#eee#www########ttt#kkkk#',
  '#####ssssssssssssss#dddd#',
  '#####ssssssssssssssddddd#',
  '#####ssssssssssssssddddd#',
  '#####ssssssssssssssddddd#',
  '#####ssssssssssssss#dddd#',
  '#########################',
 ],
 zones:{
  e:{id:'entry',name:'Staff Lobby',role:'public',purpose:'Arrival on the west side of the processing floor'},
  w:{id:'westRing',name:'West Aisle',role:'public',purpose:'The choice of half-ring',hub:{x:7,y:8.5}},
  n:{id:'northRing',name:'Sorting Aisle',role:'transition',purpose:'Safe half: the sorting partition splits it between the camera\'s strip and the aisle guard\'s strip',hub:{x:16,y:2}},
  s:{id:'southRing',name:'Processing Aisle',role:'transition',purpose:'Risk half: open floor walked by the floor guard',hub:{x:14,y:16.9}},
  t:{id:'threshold',name:'Cage Threshold',role:'restricted',purpose:'Gated aisle in front of the cage door',hub:{x:17.5,y:9.5}},
  v:{id:'cage',name:'Counting Cage',role:'objective',purpose:'Cash safe in the west bay behind the wall pier',hub:{x:14.4,y:8.7}},
  d:{id:'dock',name:'Loading Dock',role:'escape',purpose:'Way out after lockdown, behind the dock table',hub:{x:21,y:14}},
  k:{id:'bay',name:'Armoured Car Bay',role:'escape',purpose:'Way north to the exit lobby after lockdown'},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit; its door from the Sorting Aisle closes at lockdown'},
 },
 entry:{x:2.2,y:10.5},objective:{x:10.5,y:7.5},exit:{x:22.8,y:3},entryEdge:'left',exitEdge:'right',
 placement:['left-centre','centre','top-right'],
 edges:[
  {from:'entry',to:'westRing',role:'approach',via:[{x:4.5,y:10.5}]},
  {from:'westRing',to:'northRing',role:'approach',via:[{x:7,y:2}]},
  {from:'northRing',to:'threshold',role:'approach',via:[{x:18.2,y:2},{x:18.2,y:4.4},{x:17.5,y:4.4}]},
  {from:'threshold',to:'cage',role:'approach',door:{at:{x:15.5,y:9.5},orientation:'vertical',style:'bankSecurity4c'}},
  {from:'westRing',to:'southRing',role:'risk',via:[{x:7,y:16.9}]},
  {from:'southRing',to:'threshold',role:'risk',via:[{x:18.25,y:16.9},{x:18.25,y:14},{x:17.5,y:14}]},
  {from:'northRing',to:'exitLobby',role:'quickEscape',via:[{x:18.2,y:2},{x:18.2,y:3},{x:19.5,y:3}],door:{at:{x:19.5,y:3},orientation:'vertical',lockdown:true}},
  {from:'cage',to:'threshold',role:'alternateEscape',via:[{x:15.5,y:9.5}]},
  {from:'threshold',to:'southRing',role:'alternateEscape',via:[{x:17.5,y:14},{x:18.25,y:14},{x:18.25,y:16.9}]},
  {from:'southRing',to:'dock',role:'alternateEscape',via:[{x:18.25,y:16.9},{x:18.25,y:15.5},{x:19.5,y:15.5}]},
  {from:'dock',to:'bay',role:'alternateEscape',via:[{x:22,y:12.5}]},
  {from:'bay',to:'exitLobby',role:'alternateEscape',via:[{x:22,y:5.5}]},
 ],
 approach:['entry','westRing','northRing','threshold','cage'],risk:['entry','westRing','southRing','threshold','cage'],
 quickEscape:['cage','threshold','northRing','exitLobby'],alternateEscape:['cage','threshold','southRing','dock','bay','exitLobby'],
 cover:{safe:['West Aisle Column','Sorting Partition','Threshold Gate North','Cage Deposit Island','Cage Pier'],risk:['Processing Table','Threshold Gate South','Cage Pier'],escape:['Cage Deposit Island','Cage Pier','Sorting Column','Cash Pallet','Dock Trolley']},
 structures:[
  {name:'Sorting Partition',roles:['losBreak','hiding','divider'],kind:'bankWall',asset:'bank_wall',x:9,y:3.08,scale:1},
  {name:'Sorting Partition East',roles:['losBreak','hiding','divider'],kind:'bankWall',asset:'bank_wall',x:13.5,y:3.08,scale:1},
  {name:'West Aisle Column',roles:['hiding','losBreak'],kind:'bankMarbleColumn',asset:'bank_marble_column',x:5.5,y:7,scale:1},
  {name:'Cage Deposit Island',roles:['hiding','losBreak','divider'],kind:'bankDepositIsland',asset:'bank_deposit_island',x:12.5,y:9.95,scale:0.8},
  {name:'Sorting Column',roles:['hiding','losBreak'],kind:'bankMarbleColumn',asset:'bank_marble_column',x:17,y:3.05,scale:1},
  {name:'Processing Table',roles:['divider','hiding'],kind:'bankCashProcessingTable',asset:'bank_cash_processing_table',x:11,y:15.5,scale:1.4},
  {name:'Cage Box Wall',roles:['losBreak','sightline'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:14,y:6.24,scale:0.87},
  {name:'Cash Pallet',roles:['hiding','losBreak','divider'],kind:'bankCashPallet',asset:'bank_cash_pallet',x:16.1,y:15.5,scale:1.3},
  {name:'Dock Trolley',roles:['hiding','divider'],kind:'bankCageTrolley',asset:'bank_cage_trolley',x:22.285,y:15.9,scale:1.3},
  {name:'Counting Machine',roles:['hiding','losBreak','divider'],kind:'bankCountingMachine',asset:'bank_counting_machine',x:8.7,y:15.5,scale:1.2},
  {name:'Threshold Gate North',roles:['threshold','divider'],kind:'bankSecurityGate',asset:'bank_security_gate',x:17.5,y:6.3,scale:1.25},
  {name:'Threshold Gate South',roles:['threshold','divider'],kind:'bankSecurityGate',asset:'bank_security_gate',x:17.5,y:12.3,scale:1.25},
  {name:'Bay Trolley',roles:['losBreak','divider'],kind:'bankCageTrolley',asset:'bank_cage_trolley',x:20.715,y:7.3,scale:1.3},
  {name:'Bay Cart South',roles:['divider'],kind:'bankCashCart',asset:'bank_cash_cart',x:23.37,y:9.6,scale:1.4},
  {name:'Aisle Clock',roles:['decor'],kind:'bankClock',asset:'bank_clock',x:8.5,y:1.6,scale:1.4},
  {name:'Exit Plant',roles:['decor'],kind:'bankPlant',asset:'bank_plant',x:20.35,y:1.315,scale:1.4},
 ],
 walls:[{name:'Counting Cage Wall',roles:['losBreak','divider'],at:'the walled cage in the middle of the floor'},{name:'Cage Pier',roles:['losBreak','hiding','divider'],at:'pier closing the safe bay inside the cage'}],
 guards:[
  {role:'lobby',zone:'northRing',watches:'The south strip of the Sorting Aisle: the West Aisle from the west post, the cage threshold from the east post',
   stops:[{x:7.5,y:4.25,look:{x:6.5,y:7.5},wait:3},{x:14.5,y:4.25,look:{x:17.5,y:4.75},wait:3}]},
  {role:'crossing',zone:'southRing',watches:'The Processing Aisle: the West Aisle from the west post, the dock opening from the east post',
   stops:[{x:8.5,y:13.75,look:{x:5.5,y:13.75},wait:2},{x:16,y:13.75,look:{x:19,y:15.5},wait:3}]},
  {role:'escape',zone:'exitLobby',watches:'The way out: the sorting aisle door from the lobby post, then the Armoured Car Bay down to the dock',
   stops:[{x:21.5,y:2,look:{x:19.7,y:3},wait:3},{x:22,y:4.6,look:{x:22,y:8},wait:0},{x:22,y:9.5,look:{x:22,y:12.5},wait:4}]},
  {role:'objective',zone:'cage',watches:'The cash safe; between inspections walks out to the Loading Dock',
   stops:[{x:9.75,y:9.25,look:{x:10.5,y:7.5},wait:2},{x:21,y:14.75,look:{x:22,y:12.75},wait:3}]},
 ],
 cameras:[{zone:'northRing',at:{x:7.5,y:1.4},facing:0.3,watches:'The north strip of the Sorting Aisle, along its length from the west end'}],
 objectiveAsset:'bank_small_safe',objectiveScale:1.15,secureDoorStyle:'bankSecurity4c',
};

/**
 * 03-04 Security Corridor — a chain of checkpoints.
 * Checkpoint hall, camera corridor, vault anteroom: one long hook round to the Deposit Vault, each room with
 * a covered lane and a guarded one. The way out after lockdown is the Monitor Room and the west stair.
 */
const M0304:V13Mission={
 id:'03-04',title:'Security Corridor',family:'Bank',topology:'Checkpoint chain',
 map:[
  '#########################',
  '#xxxxx#nnnnnnnnn#vvv#vvv#',
  '#xxxxxxnnnnnnnnnvvvv#vvv#',
  '#xxxxxxnnnnnnnnnvvvv#vvv#',
  '#xxxxxxnnnnnnnnnvvvvvvvv#',
  '#xxxxx#nnnnnnnnn#vvvvvvv#',
  '##www############ccc#####',
  '#wwwww#mmmmmmmmm#ccccccc#',
  '#wwwww#mmmmmmmmmcccccccc#',
  '#wwwwwmmmmmmmmmmcccccccc#',
  '#wwwwwmmmmmmmmmmcccccccc#',
  '#wwwwwmmmmmmmmmm#ccccccc#',
  '###################bbb###',
  '#################bbbbbbb#',
  '#eeeee#aaaaaaaaa#bbbbbbb#',
  '#eeeeeeaaaaaaaaabbbbbbbb#',
  '#eeeeeeaaaaaaaaabbbbbbbb#',
  '#eeeeeeaaaaaaaaabbbbbbbb#',
  '#eeeee#aaaaaaaaa#bbbbbbb#',
  '#########################',
 ],
 zones:{
  e:{id:'entry',name:'Service Entrance',role:'public',purpose:'Arrival below the checkpoint hall, behind the entrance column',hub:{x:3,y:17.6}},
  a:{id:'checkpoint',name:'Checkpoint Hall',role:'public',purpose:'South lane behind the scanner, north lane walked by the checkpoint guard; the lanes meet again at the corridor door',hub:{x:14.5,y:16.5}},
  b:{id:'corridor',name:'Camera Corridor',role:'transition',purpose:'Turn north under the camera, behind the corridor wall',hub:{x:22.25,y:16}},
  c:{id:'anteroom',name:'Vault Anteroom',role:'restricted',purpose:'Last room before the Deposit Vault door, split by the inner scanner',hub:{x:20.5,y:10.9}},
  v:{id:'vault',name:'Deposit Vault',role:'objective',purpose:'Deposit safe in the east bay behind the wall pier',hub:{x:18.5,y:4.5}},
  n:{id:'passage',name:'North Passage',role:'escape',purpose:'Quick way west to the exit lobby round the box wall; its lobby door closes at lockdown',hub:{x:11,y:4.9}},
  m:{id:'monitor',name:'Monitor Room',role:'escape',purpose:'Way out after lockdown, round the monitor desk; the vault guard stands here between inspections',hub:{x:11,y:10.6}},
  w:{id:'stair',name:'West Stair',role:'escape',purpose:'Way up to the exit lobby after lockdown'},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit',hub:{x:4.6,y:1.8}},
 },
 entry:{x:2.2,y:16.5},objective:{x:22.5,y:2.6},exit:{x:2.2,y:3},entryEdge:'left',exitEdge:'left',
 placement:['bottom-left','top-right','top-left'],
 edges:[
  {from:'entry',to:'checkpoint',role:'approach',via:[{x:5.3,y:17.6},{x:5.3,y:16.5},{x:6.5,y:16.5},{x:8,y:16.5},{x:8,y:17.9},{x:14.5,y:17.9}]},
  {from:'checkpoint',to:'corridor',role:'approach',via:[{x:16.5,y:16.5},{x:22.25,y:16.5}]},
  {from:'corridor',to:'anteroom',role:'approach',via:[{x:22.25,y:13.6},{x:20.5,y:13.6}]},
  {from:'anteroom',to:'vault',role:'approach',via:[{x:18.5,y:10.9}],door:{at:{x:18.5,y:6.5},orientation:'horizontal',style:'bankSecurity4c'}},
  {from:'entry',to:'checkpoint',role:'risk',via:[{x:5.3,y:17.6},{x:5.3,y:16.5},{x:6.5,y:16.5},{x:8,y:16.5},{x:8,y:14.9},{x:14.5,y:14.9}]},
  {from:'vault',to:'passage',role:'quickEscape',via:[{x:18.5,y:3},{x:16.5,y:3},{x:15.2,y:3},{x:15.2,y:4.9}]},
  {from:'passage',to:'exitLobby',role:'quickEscape',via:[{x:7.6,y:4.9},{x:7.6,y:3},{x:6.5,y:3},{x:5.4,y:3},{x:5.4,y:1.8}],door:{at:{x:6.5,y:3},orientation:'vertical',lockdown:true}},
  {from:'vault',to:'anteroom',role:'alternateEscape',via:[{x:18.5,y:6.5}]},
  {from:'anteroom',to:'monitor',role:'alternateEscape',via:[{x:17.75,y:10.9},{x:17.75,y:9.5},{x:16.5,y:9.5},{x:15,y:9.5},{x:15,y:10.6}]},
  {from:'monitor',to:'stair',role:'alternateEscape',via:[{x:6.5,y:10.25}]},
  {from:'stair',to:'exitLobby',role:'alternateEscape',via:[{x:3.5,y:6.5}]},
 ],
 approach:['entry','checkpoint','corridor','anteroom','vault'],risk:['entry','checkpoint','corridor','anteroom','vault'],
 quickEscape:['vault','passage','exitLobby'],alternateEscape:['vault','anteroom','monitor','stair','exitLobby'],
 cover:{safe:['Hall Scanner','Corridor Wall','Anteroom Scanner','Vault Pier'],risk:['Hall Scanner','Anteroom Scanner'],escape:['Vault Pier','Exit Column','Monitor Security Desk','Passage Deposit Island']},
 structures:[
  {name:'Hall Scanner',roles:['losBreak','hiding','divider'],kind:'bankSecurityCheckpoint',asset:'bank_security_checkpoint',x:11,y:16.4,scale:1.2},
  {name:'Entrance Column',roles:['hiding','losBreak'],kind:'bankMarbleColumn',asset:'bank_marble_column',x:4,y:16.5,scale:1},
  {name:'Entrance Guard Booth',roles:['losBreak','divider'],kind:'bankGuardBooth',asset:'bank_guard_booth',x:1.95,y:14.65,scale:1},
  {name:'Corridor Wall',roles:['losBreak','hiding','divider'],kind:'bankVaultCorridorWall',asset:'bank_vault_corridor_wall',x:20,y:15.3,scale:1},
  {name:'Anteroom Gate',roles:['threshold','divider'],kind:'bankSecurityGate',asset:'bank_security_gate',x:20.5,y:12.5,scale:1.2},
  {name:'Anteroom Scanner',roles:['losBreak','hiding','divider'],kind:'bankSecurityCheckpoint',asset:'bank_security_checkpoint',x:22.4,y:9.5,scale:1},
  {name:'Anteroom Column',roles:['hiding','losBreak','divider'],kind:'bankMarbleColumn',asset:'bank_marble_column',x:20.3,y:9.5,scale:1},
  {name:'Stair Trolley',roles:['hiding','losBreak'],kind:'bankCageTrolley',asset:'bank_cage_trolley',x:1.715,y:9.6,scale:1.3},
  {name:'Exit Column',roles:['hiding','losBreak'],kind:'bankMarbleColumn',asset:'bank_marble_column',x:4.2,y:3,scale:1},
  {name:'Vault Box Wall',roles:['sightline'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:22.5,y:1.36,scale:1.3},
  {name:'Vault Box Wall West',roles:['losBreak','sightline'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:18.5,y:1.36,scale:1.3},
  {name:'Passage Deposit Island',roles:['hiding','losBreak','divider'],kind:'bankDepositIsland',asset:'bank_deposit_island',x:11,y:3.4,scale:1.2},
  {name:'Passage Box Wall East',roles:['losBreak','decor'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:14.5,y:1.357,scale:1.3},
  {name:'Monitor Security Desk',roles:['hiding','losBreak','divider'],kind:'bankSecurityDesk',asset:'bank_security_desk',x:11,y:9.1,scale:1},
  {name:'Monitor Cabinet',roles:['losBreak','decor'],kind:'bankFilingCabinet',asset:'bank_filing_cabinet',x:15.4,y:7.487,scale:1.5},
  {name:'Monitor Screen West',roles:['decor'],kind:'bankMonitor',asset:'bank_monitor',x:9.5,y:7.6,scale:1.4},
  {name:'Monitor Screen East',roles:['decor'],kind:'bankMonitor',asset:'bank_monitor',x:12.5,y:7.6,scale:1.4},
  {name:'Hall Floor Marker',roles:['decor'],kind:'bankFloorMarker',asset:'bank_floor_marker',x:7.4,y:16.5,scale:1.2},
  {name:'Stair Plant',roles:['decor'],kind:'bankPlant',asset:'bank_plant',x:1.35,y:7.315,scale:1.4},
 ],
 walls:[{name:'Vault Pier',roles:['losBreak','hiding','divider'],at:'pier closing the safe bay of the Deposit Vault'}],
 guards:[
  {role:'lobby',zone:'checkpoint',watches:'The north lane of the Checkpoint Hall: the entrance door from the west post, the corridor door from the east post',
   stops:[{x:8.5,y:14.75,look:{x:6.5,y:16.25},wait:3},{x:13.75,y:14.75,look:{x:16.5,y:16.25},wait:3}]},
  {role:'restricted',zone:'anteroom',watches:'The north lane of the Vault Anteroom: the west side below the vault door from the west post, the corridor gate from the east post',
   stops:[{x:21.2,y:7.75,look:{x:18.6,y:8.8},wait:2},{x:22.9,y:7.75,look:{x:21,y:11.75},wait:4}]},
  {role:'escape',zone:'exitLobby',watches:'The way out: the passage door from the lobby post, then the monitor room opening from the West Stair',
   stops:[{x:3.6,y:4.3,look:{x:5.6,y:3.2},wait:2},{x:3,y:6.5,look:{x:3,y:9},wait:0},{x:3,y:9.5,look:{x:5.6,y:10},wait:6}]},
  {role:'objective',zone:'vault',watches:'The deposit safe; between inspections stands in the Monitor Room',
   stops:[{x:22.75,y:4.4,look:{x:22.5,y:2.6},wait:2},{x:13.5,y:10.6,look:{x:9.5,y:10.6},wait:5}]},
 ],
 cameras:[{zone:'corridor',at:{x:23.4,y:13.4},facing:2.5,watches:'The Camera Corridor from the hall door to the anteroom opening'}],
 objectiveAsset:'bank_small_safe',objectiveScale:1.15,secureDoorStyle:'bankSecurity4c',
};

/**
 * 03-05 Main Vault — deep in, loop out.
 * Lobby, security hall, vault corridor, Main Vault, straight up the middle. The east stair is the quick way
 * down to the exit; when the alarm closes it, and the hall door behind, the way out is the west deposit room.
 */
const M0305:V13Mission={
 id:'03-05',title:'Main Vault',family:'Bank',topology:'Deep in, loop out',
 map:[
  '###########################',
  '#ddddd#vvvvvvvv#vvvv#sssss#',
  '#dddddvvvvvvvvv#vvvvvsssss#',
  '#dddddvvvvvvvvv#vvvvvsssss#',
  '#dddddvvvvvvvvvvvvvvvsssss#',
  '#ddddd#vvvvvvvvvvvvv#sssss#',
  '#ddddd###ccc#########sssss#',
  '#ddddd#ccccccccccccc#sssss#',
  '#ddddd#ccccccccccccc#sssss#',
  '#ddddd#ccccccccccccc#sssss#',
  '##www##ccccccccccccc#sssss#',
  '#wwwww##hhh#####hhh##sssss#',
  '#wwwww#hhhhhhhhhhhhh#sssss#',
  '#wwwww#hhhhhhhhhhhhh#sssss#',
  '#wwwww#hhhhhhhhhhhhh#sssss#',
  '#wwwww#hhhhhhhhhhhhh##xxx##',
  '#wwwww#hhhhhhhhhhhhh#xxxxx#',
  '#wwwww######lll######xxxxx#',
  '#wwwwwlllllllllllllllxxxxx#',
  '#wwwwwlllllllllllllllxxxxx#',
  '#wwwwwlllllllllllllllxxxxx#',
  '###########################',
 ],
 zones:{
  l:{id:'lobby',name:'Vault Lobby',role:'public',purpose:'Arrival below the security hall door',hub:{x:11,y:19.9}},
  h:{id:'hall',name:'Security Hall',role:'transition',purpose:'Round the scanner to one of two ways up: the watched west opening or the east one',hub:{x:13.5,y:12.6}},
  c:{id:'corridor',name:'Vault Corridor',role:'restricted',purpose:'South lane behind the corridor walls, north lane walked by the corridor guard',hub:{x:13,y:10.25}},
  v:{id:'vault',name:'Main Vault',role:'objective',purpose:'Vault gem in the east bay behind the wall pier',hub:{x:10.5,y:4.25}},
  s:{id:'eastStair',name:'East Stair',role:'escape',purpose:'Quick way down to the exit; its exit door closes at lockdown',hub:{x:24.9,y:7}},
  d:{id:'deposit',name:'West Deposit Room',role:'escape',purpose:'Way out after lockdown; the vault guard checks it between inspections'},
  w:{id:'westStair',name:'West Stair',role:'escape',purpose:'Way down to the lobby after lockdown'},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit'},
 },
 entry:{x:13.5,y:19.8},objective:{x:17.5,y:2.2},exit:{x:24.8,y:18.5},entryEdge:'bottom',exitEdge:'right',
 placement:['bottom-centre','top-centre','bottom-right'],
 edges:[
  {from:'lobby',to:'hall',role:'approach',door:{at:{x:13.5,y:17.5},orientation:'horizontal',lockdown:true}},
  {from:'hall',to:'corridor',role:'approach',via:[{x:17.5,y:12.6},{x:17.5,y:10.25}]},
  {from:'corridor',to:'vault',role:'approach',door:{at:{x:10.5,y:6.5},orientation:'horizontal',style:'bankSecurity4c'}},
  {from:'hall',to:'corridor',role:'risk',via:[{x:9.5,y:12.6},{x:9.5,y:10.25}]},
  {from:'vault',to:'eastStair',role:'quickEscape',via:[{x:20.5,y:4.25},{x:20.5,y:3},{x:24.9,y:3}]},
  {from:'eastStair',to:'exitLobby',role:'quickEscape',via:[{x:21.9,y:7},{x:21.9,y:10.4},{x:24.9,y:10.4},{x:24.9,y:14.2},{x:23.5,y:14.2},{x:23.5,y:15.5}],door:{at:{x:23.5,y:15.5},orientation:'horizontal',lockdown:true}},
  {from:'vault',to:'deposit',role:'alternateEscape',via:[{x:6.5,y:4.25},{x:6.5,y:3}]},
  {from:'deposit',to:'westStair',role:'alternateEscape',via:[{x:3.5,y:10.5}]},
  {from:'westStair',to:'lobby',role:'alternateEscape',via:[{x:6.5,y:19.9}]},
  {from:'lobby',to:'exitLobby',role:'alternateEscape',via:[{x:20.5,y:19.9}]},
 ],
 approach:['lobby','hall','corridor','vault'],risk:['lobby','hall','corridor','vault'],
 quickEscape:['vault','eastStair','exitLobby'],alternateEscape:['vault','deposit','westStair','lobby','exitLobby'],
 cover:{safe:['Lobby Counter West','Hall Scanner','Corridor Wall East','Corridor Wall West'],risk:['Hall Scanner','Corridor Wall West'],escape:['Vault Island East','Vault Pier','Stair Wall North','Stair Counting Machine','Stair Wall South','Exit Column','Deposit Table','West Stair Trolley','Lobby Bench']},
 structures:[
  {name:'Main Vault Door',roles:['sightline'],kind:'bankMainVault',asset:'bank_main_vault',x:10.5,y:1.24,scale:0.8},
  {name:'Vault Box Wall',roles:['sightline'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:17.85,y:1.28,scale:1},
  {name:'Vault Island West',roles:['hiding','losBreak','divider'],kind:'bankDepositIsland',asset:'bank_deposit_island',x:8.9,y:3.33,scale:0.7},
  {name:'Vault Island East',roles:['hiding','losBreak','divider'],kind:'bankDepositIsland',asset:'bank_deposit_island',x:12.3,y:3.3,scale:0.9},
  {name:'Corridor Wall West',roles:['losBreak','hiding','divider'],kind:'bankVaultCorridorWall',asset:'bank_vault_corridor_wall',x:10,y:9,scale:1},
  {name:'Corridor Wall East',roles:['losBreak','hiding','divider'],kind:'bankVaultCorridorWall',asset:'bank_vault_corridor_wall',x:16,y:9,scale:1},
  {name:'Hall Scanner',roles:['losBreak','hiding','divider'],kind:'bankSecurityCheckpoint',asset:'bank_security_checkpoint',x:13.5,y:14.4,scale:1.2},
  {name:'Hall Clock',roles:['decor'],kind:'bankClock',asset:'bank_clock',x:14.5,y:12.6,scale:1.4},
  {name:'Lobby Floor Marker',roles:['decor'],kind:'bankFloorMarker',asset:'bank_floor_marker',x:13.5,y:18.7,scale:1.2},
  {name:'Lobby Counter West',roles:['hiding','divider'],kind:'bankTellerCounter',asset:'bank_teller_counter',x:9,y:18.552,scale:1.3},
  {name:'Lobby Bench',roles:['hiding','divider'],kind:'bankWaitingBench',asset:'bank_waiting_bench',x:18,y:18.455,scale:1.3},
  {name:'Deposit Box Wall',roles:['hiding'],kind:'bankDepositBoxWall',asset:'bank_deposit_box_wall',x:2.725,y:1.4125,scale:1.5},
  {name:'Deposit Table',roles:['divider','hiding'],kind:'bankCashProcessingTable',asset:'bank_cash_processing_table',x:3.5,y:6,scale:1},
  {name:'West Stair Plant',roles:['decor'],kind:'bankPlant',asset:'bank_plant',x:1.35,y:11.315,scale:1.4},
  {name:'Exit Plant',roles:['decor'],kind:'bankPlant',asset:'bank_plant',x:25.65,y:16.315,scale:1.4},
  {name:'Stair Wall North',roles:['hiding','losBreak','divider'],kind:'bankVaultCorridorWall',asset:'bank_vault_corridor_wall',x:22.5,y:5.5,scale:1},
  {name:'Stair Counting Machine',roles:['hiding','losBreak','divider'],kind:'bankCountingMachine',asset:'bank_counting_machine',x:23.85,y:8.8,scale:1.2},
  {name:'Stair Trolley',roles:['hiding','losBreak','divider'],kind:'bankCageTrolley',asset:'bank_cage_trolley',x:25.285,y:8.8,scale:1.3},
  {name:'Stair Wall South',roles:['hiding','losBreak','divider'],kind:'bankVaultCorridorWall',asset:'bank_vault_corridor_wall',x:22.5,y:12,scale:1},
  {name:'Exit Column',roles:['hiding','losBreak'],kind:'bankMarbleColumn',asset:'bank_marble_column',x:23.5,y:18,scale:1},
  {name:'West Stair Trolley',roles:['hiding','losBreak','divider'],kind:'bankCageTrolley',asset:'bank_cage_trolley',x:1.715,y:13.2,scale:1.3},
  {name:'West Stair Counter',roles:['hiding','losBreak','divider'],kind:'bankCountingMachine',asset:'bank_counting_machine',x:4.92,y:16.6,scale:1.2},
 ],
 walls:[{name:'Vault Pier',roles:['losBreak','hiding','divider'],at:'pier closing the gem bay of the Main Vault'}],
 guards:[
  {role:'lobby',zone:'hall',watches:'The Security Hall: the west opening from the west post, the lobby door from the east post',
   stops:[{x:9.5,y:13,look:{x:9.5,y:10.75},wait:4},{x:17.5,y:15.5,look:{x:13.5,y:17},wait:3}]},
  {role:'restricted',zone:'corridor',watches:'The north lane of the Vault Corridor: the vault door from the west post, the length of the lane from the east post',
   stops:[{x:12.75,y:7.75,look:{x:10.5,y:6.75},wait:3},{x:18,y:7.75,look:{x:14,y:7.75},wait:3}]},
  {role:'escape',zone:'eastStair',watches:'The foot of the East Stair: up the west lane from the west post, the exit lobby door from the east post',
   stops:[{x:22,y:13.3,look:{x:22,y:10.5},wait:5},{x:22.4,y:14.3,look:{x:23.5,y:15.4},wait:2}]},
  {role:'objective',zone:'vault',watches:'The vault gem; between inspections walks out west to check the deposit room',
   stops:[{x:18.25,y:4,look:{x:17.5,y:2.2},wait:2},{x:3.5,y:8,look:{x:3.5,y:10.5},wait:6}]},
 ],
 cameras:[{zone:'hall',at:{x:11.4,y:12.3},facing:2.2,watches:'The west side of the Security Hall, in front of the watched west opening'}],
 objectiveAsset:'bank_small_safe',objectiveScale:1.15,secureDoorStyle:'bankSecurity4c',highSecurity:false,
};
export const V13_BANK:V13Mission[]=[M0301,M0302,M0303,M0304,M0305].map(phase7);
