/** V13 Phase 1 — Chapter 2 Gallery (EASY+). Longer sightlines and open crossings; guards are authored last. */
import type {V13Mission} from './v13Types';
import {phase7} from './v13Phase7';

/**
 * 02-01 Portrait Hall — diagonal.
 * Two staggered portrait walls turn the hall into a diagonal from the reception (left) to the Private
 * Gallery (top right). The safe lane goes north behind the first wall; the risk lane crosses the Viewing Island.
 */
const M0201:V13Mission={
 id:'02-01',title:'Portrait Hall',family:'Gallery',topology:'Diagonal',
 map:[
  '###########################',
  '#######hhhhiiiiicccc#gg#gg#',
  '#######hhhhiiiiiccccggg#gg#',
  '#######hhh#iiiiiccccggg#gg#',
  '#######hhh#iiiiiccccgggggg#',
  '#######hhh#iiiiicccc#ggggg#',
  '#######hhh#iiiiicccc#ggggg#',
  '#rrrrr#hhhhiiiiicccc##eee##',
  '#rrrrrrhhhhiiiii#ccc#eeeee#',
  '#rrrrrrhhhhiiiii#ccc#eeeee#',
  '#rrrrrrhhhhiiiii#ccc#eeeee#',
  '#rrrrr#hhhhiiiii#ccc#eeeee#',
  '#rrrrr#hhhhiiiiicccc#eeeee#',
  '#######hhhhiiiiicccc#eeeee#',
  '###########sss########xxx##',
  '#######ssssssskkkkkkxxxxxx#',
  '#######ssssssskkkkkkxxxxxx#',
  '#######ssssssskkkkkkxxxxxx#',
  '#######ssssssskkkkkk#xxxxx#',
  '###########################',
 ],
 zones:{
  r:{id:'reception',name:'Reception',role:'public',purpose:'Arrival; long view into the Portrait Hall'},
  h:{id:'portraitHall',name:'Portrait Hall',role:'public',purpose:'West aisle: north behind the first portrait wall (safe) or east through the gap (risk)',hub:{x:8.5,y:9.5}},
  i:{id:'viewingIsland',name:'Viewing Island',role:'transition',purpose:'Open crossing around the sculpture, on the hall guard\'s long north-south walk',hub:{x:13.5,y:2.5}},
  c:{id:'curatorAisle',name:'Curator Aisle',role:'restricted',purpose:'East aisle behind the second portrait wall, in front of the Private Gallery door',hub:{x:19,y:3.5}},
  g:{id:'privateGallery',name:'Private Gallery',role:'objective',purpose:'Painting in the bay behind the wall pier',hub:{x:22,y:5.5}},
  e:{id:'eastGallery',name:'East Gallery',role:'escape',purpose:'Quick way down to the side exit; its door into the side exit closes at lockdown'},
  s:{id:'southGallery',name:'South Gallery',role:'escape',purpose:'Escape after lockdown, south of the hall',hub:{x:11.5,y:16.5}},
  k:{id:'loading',name:'Loading Passage',role:'escape',purpose:'Escape east to the side exit',hub:{x:18.5,y:16.5}},
  x:{id:'sideExit',name:'Side Exit',role:'escape',purpose:'Exit; the East Gallery door closes at lockdown, the Loading Passage stays open'},
 },
 entry:{x:2.2,y:9.5},objective:{x:24.9,y:2.2},exit:{x:23.8,y:16.5},entryEdge:'left',exitEdge:'right',
 placement:['left-centre','top-right','bottom-right'],
 edges:[
  {from:'reception',to:'portraitHall',role:'approach',via:[{x:6.5,y:9.5}]},
  {from:'portraitHall',to:'viewingIsland',role:'approach',via:[{x:8.5,y:2.5}]},
  {from:'viewingIsland',to:'curatorAisle',role:'approach',via:[{x:19,y:2.5}]},
  {from:'curatorAisle',to:'privateGallery',role:'approach',door:{at:{x:20.5,y:3.5},orientation:'vertical'}},
  {from:'portraitHall',to:'viewingIsland',role:'risk',via:[{x:11.75,y:9.5},{x:11.75,y:2.5}]},
  {from:'privateGallery',to:'eastGallery',role:'quickEscape',door:{at:{x:23.5,y:7.5},orientation:'horizontal'}},
  {from:'eastGallery',to:'sideExit',role:'quickEscape',door:{at:{x:23.5,y:14.5},orientation:'horizontal',lockdown:true}},
  {from:'privateGallery',to:'curatorAisle',role:'alternateEscape',via:[{x:22,y:3.5},{x:20.5,y:3.5}]},
  {from:'curatorAisle',to:'viewingIsland',role:'alternateEscape',via:[{x:19,y:12.5},{x:15.25,y:12.5},{x:15.25,y:2.5}]},
  {from:'viewingIsland',to:'southGallery',role:'alternateEscape',via:[{x:15.25,y:2.5},{x:15.25,y:12.5},{x:12.5,y:12.5},{x:12.5,y:14.5}]},
  {from:'southGallery',to:'loading',role:'alternateEscape'},
  {from:'loading',to:'sideExit',role:'alternateEscape',via:[{x:20.5,y:16.5}]},
 ],
 approach:['reception','portraitHall','viewingIsland','curatorAisle','privateGallery'],risk:['reception','portraitHall','viewingIsland','curatorAisle','privateGallery'],
 quickEscape:['privateGallery','eastGallery','sideExit'],alternateEscape:['privateGallery','curatorAisle','viewingIsland','southGallery','loading','sideExit'],
 cover:{safe:['West Portrait Wall','Curator Sculpture','Gallery Pier'],risk:['Hall Art Wall','Island Sculpture'],escape:['Island Sculpture','South Art Wall','East Gallery Art Wall']},
 structures:[
  {name:'Reception Bench',roles:['decor'],kind:'bench',asset:'gallery_modern_bench',x:3.5,y:7.35,scale:1.4},
  {name:'Hall Art Wall',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:8.54,y:12.1,scale:2.2},
  {name:'Curator Plinth',roles:['divider'],kind:'table',asset:'gallery_central_plinth',x:18.92,y:5.73,scale:1.8},
  {name:'Portrait North West',roles:['decor'],kind:'painting',asset:'gallery_portrait_frame_a',x:8.5,y:1.6,scale:1.7},
  {name:'Portrait North Centre',roles:['decor'],kind:'painting',asset:'gallery_portrait_frame_c',x:12,y:1.6,scale:1.7},
  {name:'Portrait North East',roles:['decor'],kind:'painting',asset:'gallery_portrait_frame_e',x:14.6,y:1.6,scale:1.7},
  {name:'Island Sculpture',roles:['losBreak','divider','hiding'],kind:'statue',asset:'gallery_sculpture_large',x:13.5,y:7.4,scale:2.2},
  {name:'Island Bench North',roles:['divider'],kind:'bench',asset:'gallery_modern_bench',x:13.5,y:3.9,scale:1.4},
  {name:'Island Bench South',roles:['divider'],kind:'bench',asset:'gallery_modern_bench',x:13.5,y:10.4,scale:1.4},
  {name:'Curator Sculpture',roles:['losBreak','hiding'],kind:'statue',asset:'gallery_sculpture_large',x:16.99,y:1.77,scale:2.2},
  {name:'East Gallery Art Wall',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:24.6,y:11.4,scale:2},
  {name:'South Art Wall',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:8.4,y:16.9,scale:2},
  {name:'Loading Plinth',roles:['divider'],kind:'table',asset:'gallery_central_plinth',x:15.8,y:15.7,scale:2},
 ],
 walls:[{name:'West Portrait Wall',roles:['losBreak','divider','hiding'],at:'wall between the Portrait Hall aisle and the Viewing Island, north half'},{name:'East Portrait Wall',roles:['losBreak','divider','hiding'],at:'wall between the Viewing Island and the Curator Aisle, south half'},{name:'Gallery Pier',roles:['losBreak','hiding','divider'],at:'pier closing the painting bay of the Private Gallery'}],
 guards:[
  {role:'crossing',zone:'viewingIsland',watches:'The Viewing Island crossing on a long north-south walk: the island benches from the north post, the south gap from the south post',
   stops:[{x:15.25,y:4.75,look:{x:11.5,y:4.75},wait:3},{x:15.25,y:12.25,look:{x:11,y:12.25},wait:3}]},
  {role:'objective',zone:'privateGallery',watches:'The painting; between inspections steps out into the Curator Aisle and looks down it',
   stops:[{x:25,y:3.5,look:{x:24.9,y:2.2},wait:2},{x:18.5,y:10.5,look:{x:18.5,y:13},wait:5}]},
 ],
 cameras:[],
};

/**
 * 02-02 Sculpture Studio — central island.
 * One hall wraps a solid core dressed with sculptures. The hall guard circles it, so the thief chooses
 * clockwise (short, past the studio guard's forecourt post) or counter-clockwise (long, behind the island).
 */
const M0202:V13Mission={
 id:'02-02',title:'Sculpture Studio',family:'Gallery',topology:'Central island',
 map:[
  '#########################',
  '########ttttt#ttt#kkkkkk#',
  '########ttttt#tttkkkkkkk#',
  '########tttttttttkkkkkkk#',
  '########tttttttttkkkkkkk#',
  '#########fff########xxx##',
  '######fffffffffffff#xxxx#',
  '######fffffffffffff#xxxx#',
  '######fffffffffffff#xxxx#',
  '######fffffffffffff#xxxx#',
  '######fffffffffffff#xxxx#',
  '######wwwww###eeeee#xxxx#',
  '######wwwww###eeeee#xxxx#',
  '######wwwww###eeeee#qqq##',
  '#llll#sssssssssssss#qqqq#',
  '#lllllsssssssssssssqqqqq#',
  '#lllllsssssssssssssqqqqq#',
  '#lllllsssssssssssssqqqqq#',
  '#llll#sssssssssssss#qqqq#',
  '#########################',
 ],
 zones:{
  l:{id:'dock',name:'Loading Dock',role:'public',purpose:'Arrival; the island and the circling guard are read from here'},
  s:{id:'southRing',name:'South Ring',role:'public',purpose:'Start of both directions, in front of the colossus',hub:{x:12.5,y:16.9}},
  w:{id:'westRing',name:'West Ring',role:'transition',purpose:'Clockwise lane: short, ends under the studio guard\'s forecourt post',hub:{x:7.5,y:12.5}},
  e:{id:'eastRing',name:'East Ring',role:'transition',purpose:'Counter-clockwise lane: long, hidden from the forecourt post by the island',hub:{x:17.5,y:12.5}},
  f:{id:'forecourt',name:'Studio Forecourt',role:'restricted',purpose:'Open floor before the studio door, screened by the studio screen',hub:{x:13.25,y:7}},
  t:{id:'studio',name:'Studio',role:'objective',purpose:'Painting in the east bay behind the wall pier',hub:{x:10.5,y:3.5}},
  k:{id:'passage',name:'North Passage',role:'escape',purpose:'Quick way to the exit; its door down into the exit hall closes at lockdown'},
  q:{id:'annex',name:'South Annex',role:'escape',purpose:'Way round to the exit after lockdown'},
  x:{id:'exitHall',name:'Exit Hall',role:'escape',purpose:'Exit; the North Passage door closes at lockdown, the South Annex stays open'},
 },
 entry:{x:2.2,y:16.5},objective:{x:15.5,y:1.9},exit:{x:22.8,y:9.5},entryEdge:'left',exitEdge:'right',
 placement:['bottom-left','top-centre','right-centre'],
 edges:[
  {from:'dock',to:'southRing',role:'approach',via:[{x:5.5,y:16.9}]},
  {from:'southRing',to:'eastRing',role:'approach'},
  {from:'eastRing',to:'forecourt',role:'approach'},
  {from:'forecourt',to:'studio',role:'approach',door:{at:{x:10.5,y:5.5},orientation:'horizontal'}},
  {from:'southRing',to:'westRing',role:'risk',via:[{x:6.75,y:16.9},{x:6.75,y:12.5}]},
  {from:'westRing',to:'forecourt',role:'risk'},
  {from:'studio',to:'passage',role:'quickEscape',door:{at:{x:17.5,y:3.5},orientation:'vertical'}},
  {from:'passage',to:'exitHall',role:'quickEscape',door:{at:{x:21.5,y:5.5},orientation:'horizontal',lockdown:true}},
  {from:'studio',to:'forecourt',role:'alternateEscape',via:[{x:10.5,y:5.5}]},
  {from:'forecourt',to:'eastRing',role:'alternateEscape'},
  {from:'eastRing',to:'southRing',role:'alternateEscape'},
  {from:'southRing',to:'annex',role:'alternateEscape',via:[{x:19.5,y:16.9}]},
  {from:'annex',to:'exitHall',role:'alternateEscape',via:[{x:21.5,y:13.5}]},
 ],
 approach:['dock','southRing','eastRing','forecourt','studio'],risk:['dock','southRing','westRing','forecourt','studio'],
 quickEscape:['studio','passage','exitHall'],alternateEscape:['studio','forecourt','eastRing','southRing','annex','exitHall'],
 cover:{safe:['Dock Art Wall','Studio Colossus','Island Sculpture East','Studio Screen'],risk:['Dock Art Wall','Island Sculpture West','Studio Screen'],escape:['Studio Pier','Studio Screen','Island Sculpture East','Annex Plinth']},
 structures:[
  {name:'Studio Colossus',roles:['losBreak','divider','hiding'],kind:'statue',asset:'gallery_sculpture_large',x:12.5,y:15.05,scale:3},
  {name:'Island Sculpture West',roles:['losBreak','hiding'],kind:'statue',asset:'gallery_sculpture_large',x:10.1,y:12.5,scale:2},
  {name:'Island Sculpture East',roles:['losBreak','hiding'],kind:'statue',asset:'gallery_sculpture_large',x:14.9,y:12.5,scale:2},
  {name:'Dock Art Wall',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:9.18,y:16.62,scale:2.4},
  {name:'Studio Screen',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:10.5,y:8.7,scale:2.4},
  {name:'Forecourt Plinth',roles:['divider'],kind:'table',asset:'gallery_central_plinth',x:17.8,y:8.6,scale:2},
  {name:'Studio Work Plinth',roles:['decor'],kind:'table',asset:'gallery_central_plinth',x:10,y:1.63,scale:1.8},
  {name:'Dock Bench',roles:['decor'],kind:'bench',asset:'gallery_modern_bench',x:3,y:14.35,scale:1.4},
  {name:'Annex Plinth',roles:['divider','hiding'],kind:'table',asset:'gallery_central_plinth',x:23.1,y:16.5,scale:1.5},
  {name:'Passage Bench',roles:['decor'],kind:'bench',asset:'gallery_modern_bench',x:21.5,y:1.35,scale:1.4},
 ],
 walls:[{name:'Island Core',roles:['losBreak','divider'],at:'solid core of the central island'},{name:'Studio Pier',roles:['losBreak','hiding','divider'],at:'pier closing the painting bay of the Studio'}],
 guards:[
  {role:'crossing',zone:'westRing',loop:true,watches:'The ring around the island, walked counter-clockwise: each side in turn, always looking ahead along the next side',
   stops:[{x:7.25,y:12.5,look:{x:7.25,y:16},wait:1.5},{x:12.5,y:17.9,look:{x:16,y:17.9},wait:1.5},{x:15.75,y:17.25,look:{x:17.75,y:12.5},wait:0},{x:17.75,y:12.5,look:{x:17.75,y:9},wait:1.5},{x:13,y:10,look:{x:9.5,y:10},wait:1.5}]},
  {role:'objective',zone:'studio',watches:'The painting; between inspections walks out to the west end of the forecourt and looks down the West Ring',
   stops:[{x:16.25,y:3.25,look:{x:15.5,y:1.9},wait:5},{x:6.75,y:7.5,look:{x:7,y:11},wait:3}]},
 ],
 cameras:[],
};

/**
 * 02-03 Glass Gallery — zigzag.
 * Two glass lines fold the hall into three lanes. Glass stops the thief but not a guard's eyes, so the long
 * zigzag is only safe behind the opaque art wall and sculpture; the short cut is the west gap under the hall guard.
 */
const M0203:V13Mission={
 id:'02-03',title:'Glass Gallery',family:'Gallery',topology:'Zigzag',
 map:[
  '#########################',
  '#ppppp#ttttt#nnnnnnnnnnn#',
  '#ppppp#tttttnnnnnnnnnnnn#',
  '#pppppptttttnnnnnnnnnnnn#',
  '#pppppptttttnnnnnnnnnnnn#',
  '#ppppppttttt#nnnnnnnnnnn#',
  '#ppppp#ttttt#mmmmmmmeeee#',
  '##www##ccc###mmmmmmmeeee#',
  '#wwwww#ccccc#mmmmmmmeeee#',
  '#wwwww#ccccc#mmmmmmmeeee#',
  '#wwwww#ccccc#sssssssssss#',
  '#wwwww#ccccc#sssssssssss#',
  '#wwwww#ccccc#sssssssssss#',
  '##xxx###bbb##aaa#########',
  '#xxxxx#bbbbb#aaaaaaaaaaa#',
  '#xxxxxbbbbbb#aaaaaaaaaaa#',
  '#xxxxxbbbbbb#aaaaaaaaaaa#',
  '#xxxxxbbbbbb#aaaaaaaaaaa#',
  '#xxxxx#bbbbb#aaaaaaaaaaa#',
  '#########################',
 ],
 zones:{
  a:{id:'entrance',name:'Entrance Gallery',role:'public',purpose:'Arrival; the glass hall is entered at its west end',hub:{x:14.5,y:16.5}},
  s:{id:'southLane',name:'Glass Hall South Lane',role:'public',purpose:'First leg of the zigzag, watched through the glass from the west column',hub:{x:14.5,y:11.75}},
  e:{id:'eastTurn',name:'Glass Hall East Turn',role:'transition',purpose:'Zigzag turn through both glass gaps, under the sweeping camera',hub:{x:22.5,y:7.5}},
  m:{id:'westColumn',name:'Glass Hall West Column',role:'transition',purpose:'Short cut through the west gaps, on the hall guard\'s own walk',hub:{x:14.25,y:8.5}},
  n:{id:'northLane',name:'Glass Hall North Lane',role:'transition',purpose:'Last leg west to the threshold; the bay sculpture is the waiting place',hub:{x:13.75,y:3.5}},
  t:{id:'threshold',name:'Glass Threshold',role:'restricted',purpose:'Solid door jamb to wait behind before the Private Glass Room',hub:{x:9.5,y:4.5}},
  p:{id:'privateGlass',name:'Private Glass Room',role:'objective',purpose:'Painting behind a glass screen: seen from the door, reached round the screen',hub:{x:4.9,y:5.4}},
  w:{id:'westStair',name:'West Stair',role:'escape',purpose:'Quick way down to the exit; its door into the exit lobby closes at lockdown',hub:{x:2,y:9.25}},
  c:{id:'lab',name:'Conservation Lab',role:'escape',purpose:'Way down after lockdown, past the work plinth',hub:{x:8.5,y:11.5}},
  b:{id:'store',name:'Art Store',role:'escape',purpose:'Last room before the exit lobby, behind the stored art wall',hub:{x:8,y:16.9}},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit; the West Stair door closes at lockdown, the Art Store stays open'},
 },
 entry:{x:22.8,y:16.5},objective:{x:1.9,y:3.4},exit:{x:2.2,y:16.5},entryEdge:'right',exitEdge:'left',
 placement:['bottom-right','top-left','bottom-left'],
 edges:[
  {from:'entrance',to:'southLane',role:'approach',via:[{x:14.5,y:13.5}]},
  {from:'southLane',to:'eastTurn',role:'approach',via:[{x:22.5,y:11.75}]},
  {from:'eastTurn',to:'northLane',role:'approach',via:[{x:23,y:7.5},{x:23,y:3.5}]},
  {from:'northLane',to:'threshold',role:'approach',via:[{x:12.5,y:3.5},{x:9.5,y:3.5}]},
  {from:'threshold',to:'privateGlass',role:'approach',door:{at:{x:6.5,y:4.5},orientation:'vertical'}},
  {from:'southLane',to:'westColumn',role:'risk',via:[{x:14.25,y:11.75}]},
  {from:'westColumn',to:'northLane',role:'risk',via:[{x:14.25,y:3.5}]},
  {from:'privateGlass',to:'westStair',role:'quickEscape',door:{at:{x:3.5,y:7.5},orientation:'horizontal'}},
  {from:'westStair',to:'exitLobby',role:'quickEscape',door:{at:{x:3.5,y:13.5},orientation:'horizontal',lockdown:true}},
  {from:'privateGlass',to:'threshold',role:'alternateEscape',via:[{x:4.9,y:4.5},{x:6.5,y:4.5}]},
  {from:'threshold',to:'lab',role:'alternateEscape',via:[{x:8.5,y:7.5}]},
  {from:'lab',to:'store',role:'alternateEscape',via:[{x:9,y:13.5}]},
  {from:'store',to:'exitLobby',role:'alternateEscape',via:[{x:6.5,y:16.5}]},
 ],
 approach:['entrance','southLane','eastTurn','northLane','threshold','privateGlass'],risk:['entrance','southLane','westColumn','northLane','threshold','privateGlass'],
 quickEscape:['privateGlass','westStair','exitLobby'],alternateEscape:['privateGlass','threshold','lab','store','exitLobby'],
 cover:{safe:['Entrance Sculpture','South Lane Art Wall','Bay Sculpture','Threshold Jamb'],risk:['South Lane Art Wall','Middle Lane Sculpture'],escape:['Lab Plinth North','Stored Art Wall']},
 structures:[
  {name:'Lower Glass West',roles:['divider','sightline'],kind:'galleryGlassPanel',x:16.26,y:9.75,scale:1.8},
  {name:'Lower Glass East',roles:['divider','sightline'],kind:'galleryGlassPanel',x:18.78,y:9.75,scale:1.8},
  {name:'Upper Glass West',roles:['divider','sightline'],kind:'galleryGlassPanel',x:16.75,y:5.25,scale:2.5},
  {name:'Upper Glass East',roles:['divider','sightline'],kind:'galleryGlassPanel',x:20.25,y:5.25,scale:2.5},
  {name:'South Lane Art Wall',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:16.6,y:10.3,scale:2.2},
  {name:'Middle Lane Sculpture',roles:['losBreak','sightline'],kind:'statue',asset:'gallery_sculpture_large',x:19,y:8.75,scale:2.4},
  {name:'Bay Sculpture',roles:['hiding','losBreak'],kind:'statue',asset:'gallery_sculpture_large',x:19.5,y:1.98,scale:2.8},
  {name:'Entrance Sculpture',roles:['losBreak','hiding'],kind:'statue',asset:'gallery_sculpture_large',x:19.5,y:14.91,scale:2.6},
  {name:'Entrance Bench',roles:['decor'],kind:'bench',asset:'gallery_modern_bench',x:22.95,y:14.35,scale:1.4},
  {name:'Private Glass Screen',roles:['divider','sightline'],kind:'galleryGlassPanelVertical',x:3.6,y:2.54,scale:2.2},
  {name:'Threshold Plinth',roles:['hiding','divider'],kind:'table',asset:'gallery_central_plinth',x:9.5,y:1.63,scale:1.8},
  {name:'Lab Plinth North',roles:['divider'],kind:'table',asset:'gallery_central_plinth',x:8.08,y:9.9,scale:1.8},
  {name:'Stored Art Wall',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:10.6,y:15.9,scale:2},
  {name:'Stair Bench',roles:['decor'],kind:'bench',asset:'gallery_modern_bench',x:4.95,y:10.5,scale:1.4},
 ],
 walls:[{name:'Threshold Jamb',roles:['hiding','losBreak'],at:'solid wall either side of the Private Glass Room door'}],
 guards:[
  {role:'crossing',zone:'westColumn',watches:'The west column: through the glass gap the hall entrance from the south post, the north lane toward the bay from the north post',
   stops:[{x:14.25,y:7.5,look:{x:14.25,y:11},wait:3},{x:14.25,y:3,look:{x:18,y:3},wait:3}]},
  {role:'objective',zone:'privateGlass',watches:'The painting; between inspections steps into the threshold and watches the Conservation Lab door',
   stops:[{x:2.5,y:2,look:{x:1.9,y:3.4},wait:2},{x:9.5,y:6.1,look:{x:8.5,y:9},wait:5}]},
 ],
 cameras:[{zone:'eastTurn',at:{x:20.25,y:6.1},facing:0.9,watches:'The east turn of the zigzag between the two glass gaps'}],
};

/**
 * 02-04 Grand Atrium — outer ring, inner crossing.
 * Four cells around a central installation: sculpture island, movable walls, art wall, sculpture.
 * The ring goes round through the west cells; the crossing runs straight past the installation under the camera.
 */
const M0204:V13Mission={
 id:'02-04',title:'Grand Atrium',family:'Gallery',topology:'Outer ring with inner crossing',
 map:[
  '###########################',
  '########fffffff#xxxxxx#kkk#',
  '########fffffff#xxxxxxkkkk#',
  '########fffffff#xxxxxxkkkk#',
  '########fffffff#xxxxxxkkkk#',
  '##########ccc######ggg#kkk#',
  '#aaa##aacccccccggggggg#kkk#',
  '#aaa##aacccccccggggggg#kkk#',
  '#aaaaaaacccccccggggggg#kkk#',
  '#aaaaaaacccccccggggggg#kkk#',
  '#aaaaaaacccccccggggggg#kkk#',
  '#wwwwwwwssssssseeeeeee#kkk#',
  '#wwwwwwwssssssseeeeeeekkkk#',
  '#wwwwwwwssssssseeeeeeekkkk#',
  '#wwwwwwwssssssseeeeeeekkkk#',
  '#wwwwwwwssssssseeeeeee#kkk#',
  '##########ppp##############',
  '#######pppppp#pp###########',
  '#######pppppp#pp###########',
  '#######ppppppppp###########',
  '#######ppppppppp###########',
  '###########################',
 ],
 zones:{
  f:{id:'foyer',name:'North Foyer',role:'public',purpose:'Arrival above the atrium'},
  c:{id:'northAisle',name:'Central Aisle',role:'transition',purpose:'Inner crossing: straight to the installation, under the camera',hub:{x:11.5,y:6.75}},
  a:{id:'sculptureCell',name:'Sculpture Island Cell',role:'transition',purpose:'Ring lane round the sculpture island, behind the camera',hub:{x:7.25,y:9}},
  w:{id:'westCell',name:'Art Wall Cell',role:'transition',purpose:'Ring lane behind the west art wall, across the atrium guard\'s long walk',hub:{x:2.25,y:15}},
  s:{id:'forecourt',name:'Private Forecourt',role:'restricted',purpose:'Floor between the installation and the Private Atrium door',hub:{x:11.5,y:13.5}},
  p:{id:'private',name:'Private Atrium',role:'objective',purpose:'Painting in the east bay behind the wall pier',hub:{x:11.5,y:18.5}},
  e:{id:'eastCell',name:'East Sculpture Cell',role:'escape',purpose:'Escape east of the forecourt, behind the east sculpture',hub:{x:18.5,y:11.5}},
  g:{id:'wallCell',name:'Movable Wall Cell',role:'escape',purpose:'Quick way to the exit between the movable walls; its exit door closes at lockdown',hub:{x:20.5,y:7.6}},
  k:{id:'service',name:'East Service Corridor',role:'escape',purpose:'Way round to the exit after lockdown',hub:{x:24,y:13}},
  x:{id:'exitGallery',name:'Exit Gallery',role:'escape',purpose:'Exit'},
 },
 entry:{x:11.5,y:2.2},objective:{x:15,y:17.9},exit:{x:20,y:2.2},entryEdge:'top',exitEdge:'top',
 placement:['top-centre','bottom-centre','top-right'],
 edges:[
  {from:'foyer',to:'northAisle',role:'approach',via:[{x:11.5,y:5.5}]},
  {from:'northAisle',to:'sculptureCell',role:'approach'},
  {from:'sculptureCell',to:'westCell',role:'approach'},
  {from:'westCell',to:'forecourt',role:'approach'},
  {from:'forecourt',to:'private',role:'approach',door:{at:{x:11.5,y:16.5},orientation:'horizontal'}},
  {from:'northAisle',to:'forecourt',role:'risk',via:[{x:9,y:6.75},{x:9,y:13.5}]},
  {from:'forecourt',to:'eastCell',role:'quickEscape',via:[{x:16,y:13.5},{x:16,y:11.5}]},
  {from:'eastCell',to:'wallCell',role:'quickEscape'},
  {from:'wallCell',to:'exitGallery',role:'quickEscape',door:{at:{x:20.5,y:5.5},orientation:'horizontal',lockdown:true}},
  {from:'private',to:'forecourt',role:'alternateEscape',via:[{x:11.5,y:16.5}]},
  {from:'forecourt',to:'eastCell',role:'alternateEscape',via:[{x:16,y:13.5},{x:16,y:11.5}]},
  {from:'eastCell',to:'service',role:'alternateEscape',via:[{x:21.25,y:11.5},{x:21.25,y:13},{x:22.5,y:13}]},
  {from:'service',to:'exitGallery',role:'alternateEscape',via:[{x:24,y:3},{x:22.5,y:3}]},
 ],
 approach:['foyer','northAisle','sculptureCell','westCell','forecourt','private'],risk:['foyer','northAisle','forecourt','private'],
 quickEscape:['private','forecourt','eastCell','wallCell','exitGallery'],alternateEscape:['private','forecourt','eastCell','service','exitGallery'],
 cover:{safe:['Island Sculpture','West Art Wall','Central Installation'],risk:['Central Installation'],escape:['Atrium Pier','East Sculpture','Movable Wall South','Movable Wall North','Service Pedestal']},
 structures:[
  {name:'Central Installation',roles:['losBreak','divider','hiding'],kind:'equipment',asset:'gallery_installation_art',x:11.5,y:10.5,scale:3},
  {name:'Island Sculpture',roles:['losBreak','divider','hiding'],kind:'statue',asset:'gallery_sculpture_large',x:5,y:8.98,scale:2.8},
  {name:'Movable Wall North',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:17.2,y:6.42,scale:2.4},
  {name:'Movable Wall South',roles:['losBreak','divider','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:18.9,y:9.4,scale:2.2},
  {name:'West Art Wall',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:4.5,y:13.6,scale:2.4},
  {name:'East Sculpture',roles:['losBreak','hiding'],kind:'statue',asset:'gallery_sculpture_large',x:18.5,y:13.5,scale:2.2},
  {name:'Foyer Bench',roles:['decor'],kind:'bench',asset:'gallery_modern_bench',x:9.05,y:1.35,scale:1.4},
  {name:'Exit Plinth',roles:['decor'],kind:'table',asset:'gallery_central_plinth',x:17.08,y:1.63,scale:1.8},
  {name:'Atrium Plinth',roles:['decor'],kind:'table',asset:'gallery_central_plinth',x:8.08,y:17.63,scale:1.8},
  {name:'Service Pedestal',roles:['hiding'],kind:'statuePedestal',asset:'gallery_low_pedestal',x:25.36,y:8,scale:1.6},
 ],
 walls:[{name:'Island Core',roles:['losBreak'],at:'wall block behind the Island Sculpture'},{name:'Atrium Pier',roles:['losBreak','hiding','divider'],at:'pier closing the painting bay of the Private Atrium'}],
 guards:[
  {role:'crossing',zone:'forecourt',watches:'The whole width of the atrium on one long walk below the installation: the west ring from the west post, the east ring from the east post',
   stops:[{x:2.25,y:12.1,look:{x:2.25,y:8.5},wait:3},{x:20.75,y:12.1,look:{x:20.75,y:8.5},wait:3}]},
  {role:'objective',zone:'private',watches:'The painting; between inspections walks to the west end of the Private Atrium to check the plinth display',
   stops:[{x:15.25,y:19.25,look:{x:15,y:17.9},wait:2},{x:8.25,y:19.75,look:{x:8.1,y:18},wait:4.5}]},
 ],
 cameras:[{zone:'northAisle',at:{x:11.5,y:7.5},facing:1.5708,watches:'The two lanes either side of the installation on the inner crossing'}],
};

/**
 * 02-05 Masterpiece — deep in, alternate out.
 * Public Gallery → Main Installation → Curator Wing → Private Exhibition → Masterpiece Chamber, clockwise.
 * Once a guard finds the stand empty the door from the loading corridor into the exit shuts, and the way out is the
 * Preparation Room and the Service Gallery to the loading exit.
 */
const M0205:V13Mission={
 id:'02-05',title:'Masterpiece',family:'Gallery',topology:'Deep in, alternate out',
 map:[
  '##########################',
  '#gggggggg#mmmmmmmmm#ccccc#',
  '#ggggggggmmmmmmmmmmcccccc#',
  '#ggggggggmmmmmmmmmmcccccc#',
  '#ggggggggmmmmmmmmmmcccccc#',
  '#gggggggg#mmmmmmmmm#ccccc#',
  '#gggggggg#mmmmmmmmm##eee##',
  '#gggggggg#mmmmmmmmm#eeeee#',
  '#gggggggg#mmmmmmmmmeeeeee#',
  '#gggggggg#mmmmmmmmmeeeeee#',
  '#gggggggg#mmmmmmmmmeeeeee#',
  '#gggggggg#mmmmmmmmm#eeeee#',
  '#####################vvv##',
  '#xxxx#kkkkkk#rrrrrr#vvvvv#',
  '#xxxxkkkkkkkrrrrrrrvvvvvv#',
  '#xxxxkkkkkkkrrrrrrrvvvvvv#',
  '#xxxxkkkkkkkrrrrrrrvvvvvv#',
  '#xxxx###############vv####',
  '#xxxxddddddddddddddvvvvvv#',
  '#xxxxddddddddddddddvvvvvv#',
  '#xxxxddddddddddddddvvvvvv#',
  '##########################',
 ],
 zones:{
  g:{id:'publicGallery',name:'Public Gallery',role:'public',purpose:'Arrival; long view down the gallery and across to the Main Installation',hub:{x:7,y:3.5}},
  m:{id:'mainHall',name:'Main Installation',role:'public',purpose:'The installation splits the hall: north lane to the Curator Wing, east lane to the exhibition under the camera',hub:{x:11,y:3.5}},
  c:{id:'curatorWing',name:'Curator Wing',role:'transition',purpose:'Safe lane: an unwatched room to wait in above the Private Exhibition',hub:{x:22.5,y:4.25}},
  e:{id:'privateExhibition',name:'Private Exhibition',role:'restricted',purpose:'Both lanes meet here in front of the chamber door',hub:{x:22.5,y:9.5}},
  v:{id:'chamber',name:'Masterpiece Chamber',role:'objective',purpose:'Masterpiece in the south bay behind the wall stub',hub:{x:21,y:15.5}},
  d:{id:'loadingCorridor',name:'Loading Corridor',role:'escape',purpose:'Straight run to the loading exit; its door into the loading exit closes at lockdown'},
  r:{id:'prepRoom',name:'Preparation Room',role:'escape',purpose:'Way out after lockdown, past the preparation table'},
  k:{id:'serviceGallery',name:'Service Gallery',role:'escape',purpose:'Last room before the loading exit'},
  x:{id:'loadingExit',name:'Loading Exit',role:'escape',purpose:'Exit; the Loading Corridor door closes at lockdown, the Service Gallery stays open'},
 },
 entry:{x:2.2,y:2.5},objective:{x:24,y:19.6},exit:{x:2.2,y:17},entryEdge:'left',exitEdge:'left',
 placement:['top-left','bottom-right','bottom-left'],
 edges:[
  {from:'publicGallery',to:'mainHall',role:'approach',via:[{x:9.5,y:3.5}]},
  {from:'mainHall',to:'curatorWing',role:'approach',via:[{x:19.5,y:3.5}]},
  {from:'curatorWing',to:'privateExhibition',role:'approach',via:[{x:22.5,y:6.5}]},
  {from:'privateExhibition',to:'chamber',role:'approach',door:{at:{x:22.5,y:12.5},orientation:'horizontal'}},
  {from:'mainHall',to:'privateExhibition',role:'risk',via:[{x:17.5,y:3.5},{x:17.5,y:9.5},{x:19.5,y:9.5}]},
  {from:'chamber',to:'loadingCorridor',role:'quickEscape',door:{at:{x:19.5,y:19.5},orientation:'vertical'}},
  {from:'loadingCorridor',to:'loadingExit',role:'quickEscape',door:{at:{x:5.5,y:19.5},orientation:'vertical',lockdown:true}},
  {from:'chamber',to:'prepRoom',role:'alternateEscape',via:[{x:19.5,y:15.5}]},
  {from:'prepRoom',to:'serviceGallery',role:'alternateEscape',via:[{x:12.5,y:15.5}]},
  {from:'serviceGallery',to:'loadingExit',role:'alternateEscape',via:[{x:5.5,y:15.5}]},
 ],
 approach:['publicGallery','mainHall','curatorWing','privateExhibition','chamber'],risk:['publicGallery','mainHall','privateExhibition','chamber'],
 quickEscape:['chamber','loadingCorridor','loadingExit'],alternateEscape:['chamber','prepRoom','serviceGallery','loadingExit'],
 cover:{safe:['Gallery Art Wall','Main Installation'],risk:['Main Installation','Hall Art Wall'],escape:['Chamber Stub','Preparation Table','Service Art Wall']},
 structures:[
  {name:'Main Installation',roles:['losBreak','divider','hiding'],kind:'equipment',asset:'gallery_installation_art',x:14.5,y:5.2,scale:3.4},
  {name:'Hall Art Wall',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:14.5,y:9.9,scale:2.4},
  {name:'Gallery Sculpture',roles:['divider','sightline'],kind:'statue',asset:'gallery_sculpture_large',x:4.5,y:9.3,scale:2.8},
  {name:'Gallery Art Wall',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:5.5,y:5.2,scale:2.4},
  {name:'Curator Plinth',roles:['decor'],kind:'table',asset:'gallery_central_plinth',x:22.5,y:1.63,scale:1.8},
  {name:'Preparation Table',roles:['divider','hiding'],kind:'table',asset:'gallery_central_plinth',x:15.5,y:13.7,scale:2},
  {name:'Service Art Wall',roles:['losBreak','hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:8.5,y:13.35,scale:2},
  {name:'Loading Art Wall',roles:['hiding'],kind:'partition',asset:'gallery_movable_art_wall',x:11,y:18.35,scale:2},
  {name:'Loading Bench',roles:['decor'],kind:'bench',asset:'gallery_modern_bench',x:2.05,y:13.35,scale:1.4},
  {name:'Masterpiece Wall',roles:['decor'],kind:'painting',asset:'gallery_masterpiece_wall',x:23.5,y:18.6,scale:2.2},
 ],
 walls:[{name:'Hall Divider',roles:['divider','losBreak'],at:'wall between the Public Gallery and the Main Installation'},{name:'Chamber Stub',roles:['losBreak','hiding','divider'],at:'wall stub above the masterpiece bay'}],
 guards:[
  {role:'crossing',zone:'mainHall',watches:'The west side of the Main Installation: the north lane from the north post, the south lane from the south post',
   stops:[{x:11.25,y:3,look:{x:15,y:2.75},wait:3},{x:11.25,y:10.75,look:{x:15,y:10.9},wait:3}]},
  {role:'restricted',zone:'privateExhibition',watches:'The Private Exhibition: the hall opening from the west post, the chamber door from the east post',
   stops:[{x:20.75,y:8.5,look:{x:17.5,y:8.9},wait:3},{x:23.75,y:10.25,look:{x:22.5,y:12.5},wait:3}]},
  {role:'objective',zone:'chamber',watches:'The masterpiece; between inspections walks into the Preparation Room',
   stops:[{x:22.75,y:19.75,look:{x:24,y:19.6},wait:2},{x:15.5,y:15.75,look:{x:12.5,y:15.5},wait:4}]},
 ],
 cameras:[{zone:'mainHall',at:{x:18.4,y:6.5},facing:1.5708,watches:'The east lane of the hall down to the Private Exhibition opening'}],
 // The alarm waits for a guard to see the empty stand, like every other Chapter 1–2 mission.
 highSecurity:false,
};
export const V13_GALLERY:V13Mission[]=[M0201,M0202,M0203,M0204,M0205].map(phase7);
