/**
 * V13 Phase 2 — Chapter 4 Lab (MEDIUM+). Glass is the venue rule: it stops the thief and not a guard's eyes, so cover
 * is whatever is opaque (consoles, cryo units, wall screens, piers). Guards are authored last.
 * Only the front-facing Lab art is used; the skewed glass / partition / rack sprites are left out.
 */
import type {V13Mission} from './v13Types';
import {phase7} from './v13Phase7';

const SAMPLE={objectiveAsset:'lab_sample_case',objectiveScale:1.5,secureDoorStyle:'labPrototypeSecurity4c'} as const;

/**
 * 04-01 Research Reception — the glass front.
 * The open lab looks into the reception through its glass front, so the lobby is crossed under the lab guard's eyes.
 * Short way: in through the gap in the glass and across the lab. Safe way: along the reception to the west corridor.
 */
const M0401:V13Mission={
 id:'04-01',title:'Research Reception',family:'Lab',topology:'Glass front: through the lab or round it',
 map:[
  '##########################',
  '#ss#sss#aaa#aaaaaaa#xxxxx#',
  '#ss#sss#aaa#aaaaaaa#xxxxx#',
  '#ss#sssaaaa#aaa#aaaxxxxxx#',
  '#ss#sssaaaa#aaa#aaaxxxxxx#',
  '#ssssssaaaaaaaa#aaaxxxxxx#',
  '#ssssss#aaaaaaa#aaa#xxxxx#',
  '###www##########eee##eee##',
  '#wwwwww#ooooooo#eeeeeeeee#',
  '#wwwwwwoooooooo#eeeeeeeee#',
  '#wwwwwwoooooooo#eeeeeeeee#',
  '#wwwwwwoooooooo#eeeeeeeee#',
  '#wwwwww#ooooooo#eeeeeeeee#',
  '##www###ooooooo###########',
  '#rrrrrrrrrrrrrrrrrrrrrrrr#',
  '#rrrrrrrrrrrrrrrrrrrrrrrr#',
  '#rrrrrrrrrrrrrrrrrrrrrrrr#',
  '#rrrrrrrrrrrrrrrrrrrrrrrr#',
  '#rrrrrrrrrrrrrrrrrrrrrrrr#',
  '##########################',
 ],
 zones:{
  r:{id:'reception',name:'Reception',role:'public',purpose:'Arrival; crossed in view of the open lab through its glass front',hub:{x:13,y:17.25}},
  o:{id:'openLab',name:'Open Lab',role:'transition',purpose:'Short way: north lane behind the lab console while the lab guard walks the south lane',hub:{x:14,y:9.75}},
  w:{id:'westCorridor',name:'West Corridor',role:'restricted',purpose:'Both ways meet here; the corridor console splits it into the guard lane and the thief lane',hub:{x:6.1,y:10.5}},
  s:{id:'sampleRoom',name:'Sample Room',role:'objective',purpose:'Sample case in the west bay behind the wall pier',hub:{x:4.5,y:5.75}},
  a:{id:'analysis',name:'Analysis Lab',role:'escape',purpose:'Three bays in an S; the sample guard reads the monitor station in the dead-end corner between inspections',hub:{x:16.9,y:4.5}},
  e:{id:'eastHall',name:'East Hall',role:'escape',purpose:'Way round to the exit lobby after lockdown: south of the test machine, out of the hall camera\'s view',hub:{x:16.9,y:12.2}},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit; its door from the Analysis Lab closes at lockdown',hub:{x:22,y:4.5}},
 },
 entry:{x:22.5,y:17.8},objective:{x:2,y:2.6},exit:{x:23.8,y:2.5},entryEdge:'bottom',exitEdge:'right',
 placement:['bottom-right','top-left','top-right'],
 edges:[
  {from:'reception',to:'westCorridor',role:'approach',via:[{x:3,y:17.25},{x:3,y:12.1},{x:6.1,y:12.1}]},
  {from:'westCorridor',to:'sampleRoom',role:'approach',via:[{x:6.1,y:8.9},{x:4.5,y:8.9}],door:{at:{x:4.5,y:7.5},orientation:'horizontal'}},
  {from:'reception',to:'openLab',role:'risk',via:[{x:14,y:17.25},{x:14,y:13.5}]},
  {from:'openLab',to:'westCorridor',role:'risk',via:[{x:7.5,y:9.75},{x:6.1,y:9.75}]},
  {from:'sampleRoom',to:'analysis',role:'alternateEscape',via:[{x:6,y:5.75},{x:6,y:4.5},{x:7.5,y:4.5},{x:9.5,y:4.5},{x:9.5,y:5.75},{x:13.5,y:5.75},{x:13.5,y:2},{x:16.9,y:2}],door:{at:{x:7.5,y:4.5},orientation:'vertical',type:'glass'}},
  {from:'analysis',to:'exitLobby',role:'quickEscape',door:{at:{x:19.5,y:4.5},orientation:'vertical',lockdown:true}},
  {from:'analysis',to:'eastHall',role:'alternateEscape',via:[{x:16.9,y:7.5}]},
  {from:'eastHall',to:'exitLobby',role:'alternateEscape',via:[{x:22,y:12.2},{x:22,y:7.5}]},
 ],
 approach:['reception','westCorridor','sampleRoom'],risk:['reception','openLab','westCorridor','sampleRoom'],
 quickEscape:['sampleRoom','analysis','exitLobby'],alternateEscape:['sampleRoom','analysis','eastHall','exitLobby'],
 cover:{safe:['Reception Console','Reception Mobile Screen','Lobby Specimen Tank','Corridor Console'],risk:['Reception Console','Lab Centrifuge Bench','Corridor Console'],escape:['Sample Pier','Analysis Stub West','Analysis Stub East','Hall Test Machine']},
 structures:[
  {name:'Reception Console',roles:['hiding','losBreak','divider'],kind:'labObservationConsole',asset:'lab_observation_console',x:18.5,y:16.3,scale:1.25},
  {name:'Reception Mobile Screen',roles:['hiding','losBreak'],kind:'labMobileScreen',asset:'lab_mobile_screen',x:9.5,y:15.5,scale:1.36},
  {name:'Lobby Specimen Tank',roles:['hiding','losBreak'],kind:'labSpecimenTank',asset:'lab_specimen_tank_low',x:6,y:16.1,scale:1.1},
  {name:'Lab Front Glass West',roles:['divider','sightline'],kind:'labGlassPartition',asset:'lab_glass_partition_front',x:9.25,y:13.5,scale:0.862},
  {name:'Lab Front Glass East',roles:['divider','sightline'],kind:'labGlassPartition',asset:'lab_glass_partition_front',x:11.75,y:13.5,scale:0.862},
  {name:'Lab Centrifuge Bench',roles:['hiding','losBreak','divider'],kind:'labCentrifugeBench',asset:'lab_centrifuge_bench',x:10.95,y:11.05,scale:1.3},
  {name:'Corridor Console',roles:['hiding','losBreak','divider'],kind:'labObservationConsole',asset:'lab_observation_console',x:3.95,y:10.5,scale:1},
  {name:'Hall Test Machine',roles:['hiding','losBreak','divider'],kind:'labExperimentMachine',asset:'lab_experiment_machine',x:19.5,y:10.9,scale:1.25},
  {name:'Sample Bench',roles:['divider'],kind:'labLargeTable',asset:'lab_large_table',x:5.5,y:1.61,scale:1.111},
  {name:'Sample Room Screen',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:1.9,y:1.6,scale:1.4},
  {name:'Analysis Screen',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:13.5,y:1.6,scale:1.4},
  {name:'Analysis Warning Sign',roles:['decor'],kind:'labWarningSign',asset:'lab_warning_sign',x:17.5,y:1.6,scale:1.3},
  {name:'Hall Screen',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:24,y:8.6,scale:1.4},
  {name:'Analysis Monitor Station',roles:['observation','losBreak'],kind:'labMonitorStation',asset:'lab_monitor_station',x:9.5,y:1.53,scale:1.25},
  {name:'Glass Gap Marker',roles:['decor'],kind:'labFloorMarker',asset:'lab_floor_marker',x:14,y:14.4,scale:1.2},
  {name:'Exit Door Marker',roles:['decor'],kind:'labFloorMarker',asset:'lab_floor_marker',x:17.9,y:4.5,scale:1.2},
  {name:'Lab Cable',roles:['decor'],kind:'labCable',asset:'lab_cable',x:12.2,y:12.6,scale:1.2},
 ],
 walls:[
  {name:'Sample Pier',roles:['losBreak','hiding','divider'],at:'pier closing the sample bay of the Sample Room'},
  {name:'Analysis Stub West',roles:['losBreak','divider'],at:'wall from the north side of the Analysis Lab, passed on its south end'},
  {name:'Analysis Stub East',roles:['losBreak','divider'],at:'wall from the south side of the Analysis Lab, passed on its north end'},
 ],
 guards:[
  {role:'lobby',zone:'openLab',watches:'The reception through the glass front from the west post; the gap in the glass from the east post',
   stops:[{x:8.9,y:12.3,look:{x:8.9,y:16},wait:4},{x:13.6,y:12.3,look:{x:14,y:15.5},wait:3}]},
  {role:'restricted',zone:'westCorridor',watches:'The west lane of the corridor: the sample room door from the north post, the reception opening from the south post',
   stops:[{x:1.8,y:8.9,look:{x:4.5,y:7.6},wait:3},{x:1.8,y:12.1,look:{x:3,y:13.6},wait:3}]},
  {role:'escape',zone:'exitLobby',watches:'The way out: the analysis lab door from the lobby post, then the analysis opening from the East Hall',
   stops:[{x:22.6,y:5.2,look:{x:20.2,y:4.5},wait:3},{x:22,y:7.5,look:{x:22,y:9},wait:0},{x:22,y:9.3,look:{x:17.5,y:9.3},wait:4}]},
  {role:'objective',zone:'sampleRoom',watches:'The sample case; between inspections reads the monitor station in the dead-end corner of the Analysis Lab',
   stops:[{x:2,y:5.6,look:{x:2,y:2.6},wait:2},{x:5.5,y:5.6,look:{x:7.5,y:4.5},wait:0},{x:9.5,y:4.5,look:{x:9.5,y:2},wait:0},{x:9.5,y:2.9,look:{x:9.5,y:1.5},wait:5}]},
 ],
 cameras:[{zone:'eastHall',at:{x:19.5,y:8.4},facing:1.5708,watches:'The East Hall between the Analysis Lab opening and the exit lobby opening'}],
 ...SAMPLE,
};

/**
 * 04-02 Observation Wing — round the glass core.
 * The core is glass on its west and east faces: the sample and its guard are in view from both galleries, and so is
 * the thief. In by the west gallery (guard circling the lane wall, camera on the glass-side lane), out by the north door.
 */
const M0402:V13Mission={
 id:'04-02',title:'Observation Wing',family:'Lab',topology:'Round the glass core',
 map:[
  '#########################',
  '#aaaaa#mmmmmmmmm#xxxxxxx#',
  '#aaaaa#mmmmmmmmmxxxxxxxx#',
  '#aaaaa#mmmmmmmmmxxxxxxxx#',
  '#aaaaa#mmmmmmmmmxxxxxxxx#',
  '#aaaaa#mmmmmmmmm#xxxxxxx#',
  '#www######ccc######fff###',
  '#wwwwwcccccccccccfffffff#',
  '#wwwwwcccccccccccfffffff#',
  '#ww#wwcccc####cccfffffff#',
  '#ww#wwcccc#cc#cccfffffff#',
  '#ww#wwcccc#cc#ccc####eee#',
  '#ww#wwcccc#cc#ccceeeeeee#',
  '#ww#wwccccccccccceeeeeee#',
  '#wwwwwccccccccccceeeeeee#',
  '#wwwwwccccccccccceeeeeee#',
  '##www##ccc###ccc###eee###',
  '#sssssssssssssssssssssss#',
  '#sssssssssssssssssssssss#',
  '#sssssssssssssssssssssss#',
  '#########################',
 ],
 zones:{
  a:{id:'arrival',name:'Arrival',role:'public',purpose:'Arrival above the west gallery',hub:{x:2.5,y:3.5}},
  w:{id:'westGallery',name:'West Gallery',role:'transition',purpose:'Two lanes round the lane wall: the outer lane out of sight, the inner lane along the core glass',hub:{x:2.5,y:8}},
  s:{id:'southGallery',name:'South Gallery',role:'restricted',purpose:'Corridor under the two south doors of the core, walked by the gallery guard',hub:{x:8,y:17.9}},
  c:{id:'core',name:'Observation Core',role:'objective',purpose:'Sample in the walled bay at the centre; glass to the west and east galleries',hub:{x:8,y:14}},
  m:{id:'monitoring',name:'Monitoring Room',role:'escape',purpose:'Quick way from the north door of the core to the exit lobby',hub:{x:11.5,y:3.5}},
  e:{id:'eastLab',name:'East Lab',role:'escape',purpose:'Way round after lockdown, in view of the core through its east glass',hub:{x:20,y:14}},
  f:{id:'eastStair',name:'East Stair',role:'escape',purpose:'Up to the exit lobby after lockdown',hub:{x:20,y:9}},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit; its door from the Monitoring Room closes at lockdown',hub:{x:20,y:3.5}},
 },
 entry:{x:2.5,y:2.2},objective:{x:12,y:10.6},exit:{x:22.8,y:3},entryEdge:'top',exitEdge:'right',
 placement:['top-left','centre','top-right'],
 edges:[
  {from:'arrival',to:'westGallery',role:'approach'},
  {from:'westGallery',to:'southGallery',role:'approach',via:[{x:1.75,y:8},{x:1.75,y:15},{x:3,y:15},{x:3,y:17.9}]},
  {from:'westGallery',to:'southGallery',role:'risk',via:[{x:4.75,y:8},{x:4.75,y:15},{x:3,y:15},{x:3,y:17.9}]},
  {from:'southGallery',to:'core',role:'approach',door:{at:{x:8,y:16.5},orientation:'horizontal'}},
  {from:'core',to:'monitoring',role:'quickEscape',via:[{x:8,y:7.75},{x:11.5,y:7.75}],door:{at:{x:11.5,y:6.5},orientation:'horizontal',type:'glass'}},
  {from:'monitoring',to:'exitLobby',role:'quickEscape',door:{at:{x:16.5,y:3.5},orientation:'vertical',lockdown:true}},
  {from:'core',to:'southGallery',role:'alternateEscape',via:[{x:14,y:14},{x:14,y:16.5},{x:14,y:17.9}],door:{at:{x:14,y:16.5},orientation:'horizontal'}},
  {from:'southGallery',to:'eastLab',role:'alternateEscape',via:[{x:20,y:17.9}]},
  {from:'eastLab',to:'eastStair',role:'alternateEscape',via:[{x:22,y:14},{x:22,y:9}]},
  {from:'eastStair',to:'exitLobby',role:'alternateEscape'},
 ],
 approach:['arrival','westGallery','southGallery','core'],risk:['arrival','westGallery','southGallery','core'],
 quickEscape:['core','monitoring','exitLobby'],alternateEscape:['core','southGallery','eastLab','eastStair','exitLobby'],
 cover:{safe:['Lane Wall','Sample Bay Wall'],risk:['Lane Wall'],escape:['Sample Bay Wall','Monitoring Station','East Test Machine']},
 structures:[
  {name:'Arrival Specimen Display',roles:['losBreak','divider'],kind:'labSpecimenTank',asset:'lab_specimen_tank_low',x:4.75,y:1.45,scale:1},
  {name:'Monitoring Station',roles:['hiding','losBreak','divider'],kind:'labMonitorStation',asset:'lab_monitor_station',x:8.14,y:3.5,scale:1.2},
  {name:'East Test Machine',roles:['hiding','losBreak','divider'],kind:'labExperimentMachine',asset:'lab_experiment_machine',x:18.25,y:12.563,scale:1.25},
  {name:'Gallery Stool',roles:['decor'],kind:'labStool',asset:'lab_stool',x:5.75,y:7.325,scale:1.3},
  {name:'Core Glass West A',roles:['divider','sightline'],kind:'galleryGlassPanelVertical',x:6.5,y:8.5,scale:2.143},
  {name:'Core Glass West B',roles:['divider','sightline'],kind:'galleryGlassPanelVertical',x:6.5,y:11.5,scale:2.143},
  {name:'Core Glass West C',roles:['divider','sightline'],kind:'galleryGlassPanelVertical',x:6.5,y:14.5,scale:2.143},
  {name:'Core Glass East A',roles:['divider','sightline'],kind:'galleryGlassPanelVertical',x:16.5,y:8.5,scale:2.143},
  {name:'Core Glass East B',roles:['divider','sightline'],kind:'galleryGlassPanelVertical',x:16.5,y:11.5,scale:2.143},
  {name:'Core Glass East C',roles:['divider','sightline'],kind:'galleryGlassPanelVertical',x:16.5,y:14.5,scale:2.143},
  {name:'Core Stool West',roles:['observation'],kind:'labStool',asset:'lab_stool',x:7.1,y:11.5,scale:1.3},
  {name:'Core Stool East',roles:['observation'],kind:'labStool',asset:'lab_stool',x:15.9,y:11.5,scale:1.3},
  {name:'Bay Warning Sign West',roles:['decor'],kind:'labWarningSign',asset:'lab_warning_sign',x:10.5,y:13.6,scale:1.3},
  {name:'Bay Warning Sign East',roles:['decor'],kind:'labWarningSign',asset:'lab_warning_sign',x:13.5,y:13.6,scale:1.3},
  {name:'Core Door Marker',roles:['decor'],kind:'labFloorMarker',asset:'lab_floor_marker',x:8,y:15.4,scale:1.2},
  {name:'Exit Door Marker',roles:['decor'],kind:'labFloorMarker',asset:'lab_floor_marker',x:15.8,y:3.5,scale:1.2},
  {name:'Monitoring Cable',roles:['decor'],kind:'labCable',asset:'lab_cable',x:11.5,y:2.2,scale:1.2},
  {name:'Monitoring Screen',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:11.5,y:1.6,scale:1.4},
  {name:'South Workstation',roles:['divider'],kind:'labWorkstation',asset:'lab_workstation',x:22.785,y:17.574,scale:1.35},
  {name:'South Screen',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:17.5,y:17.6,scale:1.4},
 ],
 walls:[
  {name:'Lane Wall',roles:['losBreak','hiding','divider'],at:'wall between the outer and inner lanes of the West Gallery'},
  {name:'Sample Bay Wall',roles:['losBreak','hiding','divider'],at:'three-sided wall round the sample at the centre of the Observation Core, open to the south'},
 ],
 guards:[
  {role:'lobby',zone:'westGallery',watches:'Both lanes of the West Gallery, circling the lane wall: down the outer lane, back up the inner lane',loop:true,
   stops:[{x:1.75,y:8.25,look:{x:1.75,y:12},wait:3},{x:1.75,y:14.75,look:{x:4.75,y:14.75},wait:2},{x:4.75,y:14.75,look:{x:4.75,y:11},wait:2},{x:4.75,y:8.25,look:{x:1.75,y:8.25},wait:2}]},
  {role:'restricted',zone:'southGallery',watches:'The two south doors of the core: the west door from the west post, the east door from the east post',
   stops:[{x:10.5,y:19.25,look:{x:8,y:16.8},wait:3},{x:16.5,y:19.25,look:{x:14,y:16.8},wait:3}]},
  {role:'escape',zone:'exitLobby',watches:'The way out: the monitoring room door from the lobby post, then the East Stair down to the east lab opening',
   stops:[{x:20,y:2.2,look:{x:17.2,y:3.5},wait:3},{x:20,y:6.5,look:{x:20,y:8.5},wait:0},{x:19.5,y:9.2,look:{x:22,y:11.4},wait:4}]},
  {role:'objective',zone:'core',watches:'The sample; between inspections stands at the east glass and watches the East Stair',
   stops:[{x:12,y:13.9,look:{x:12,y:10.6},wait:2},{x:14.9,y:13.9,look:{x:14.9,y:10},wait:0},{x:14.9,y:8,look:{x:19,y:8},wait:5}]},
 ],
 cameras:[{zone:'westGallery',at:{x:4.75,y:7.4},facing:1.5708,watches:'The inner lane of the West Gallery along the core glass'}],
 ...SAMPLE,
};

/**
 * 04-03 Glass Research — the guard next door.
 * One hall, cut along its length by a glass line: the lane guard on the north side sees the south side through it.
 * In by the west lock and up the north lane behind the lane screens, or through the gap in the glass by the cleanroom door.
 */
const M0403:V13Mission={
 id:'04-03',title:'Glass Research',family:'Lab',topology:'Two lanes and a glass line',
 map:[
  '##########################',
  '#xxxx#nnnnnnnnnnnn#ccc#cc#',
  '#xxxx#nnnnnnnnnnnn#ccc#cc#',
  '#xxxxxnnnnnnnnnnnncccc#cc#',
  '#xxxxxnnnnnnnnnnnncccc#cc#',
  '#xxxxxnnnnnnnnnnnnccccccc#',
  '#xxxx#nnnnnnnnnnnn#cccccc#',
  '#kkk##www###########ccc###',
  '#kkk#wwww#uuuuuuuuuuuuuuu#',
  '#kkk#wwwwuuuuuuuuuuuuuuuu#',
  '#kkkwwwwwuuuuuuuuuuuuuuuu#',
  '#kkkwwwwwuuuuuuuuuuuuuuuu#',
  '#kkkwwwww#lllllllllllllll#',
  '#kkk#wwww#lllllllllllllll#',
  '#kkk#wwww#lllllllllllllll#',
  '#kkk#wwww#lllllllllllllll#',
  '######www#######lll#######',
  '#rrrrrrrrrrrrrrrrrrrrrrrr#',
  '#rrrrrrrrrrrrrrrrrrrrrrrr#',
  '#rrrrrrrrrrrrrrrrrrrrrrrr#',
  '#rrrrrrrrrrrrrrrrrrrrrrrr#',
  '##########################',
 ],
 zones:{
  r:{id:'reception',name:'Reception',role:'public',purpose:'Arrival behind the reception screen; two openings up, each watched in turn by the reception guard',hub:{x:12,y:20.1}},
  w:{id:'westBay',name:'West Bay',role:'transition',purpose:'Lock between the reception and the North Lane; its lane door closes at lockdown',hub:{x:7,y:11.5}},
  l:{id:'southLane',name:'South Lane',role:'transition',purpose:'Short way: up to the gap in the glass, in view of the lane guard through it',hub:{x:17,y:14.75}},
  u:{id:'northLane',name:'North Lane',role:'restricted',purpose:'Behind the lane screens to the cleanroom door while the lane guard walks the glass side',hub:{x:21.5,y:8.8}},
  c:{id:'cleanroom',name:'Cleanroom',role:'objective',purpose:'Sample in the east bay behind the wall pier',hub:{x:21.5,y:5.75}},
  n:{id:'northLab',name:'North Lab',role:'escape',purpose:'Quick way west to the exit lobby, under the lab camera',hub:{x:12,y:4.5}},
  k:{id:'westStair',name:'West Stair',role:'escape',purpose:'Up to the exit lobby after lockdown',hub:{x:2.5,y:11.5}},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit; its door from the North Lab closes at lockdown',hub:{x:2.5,y:4.5}},
 },
 entry:{x:12,y:19.9},objective:{x:24,y:2.6},exit:{x:2.2,y:3.5},entryEdge:'bottom',exitEdge:'left',
 placement:['bottom-centre','top-right','top-left'],
 edges:[
  {from:'reception',to:'westBay',role:'approach',via:[{x:7,y:20.1}]},
  {from:'westBay',to:'northLane',role:'approach',via:[{x:9.5,y:10.5},{x:10.75,y:10.5},{x:10.75,y:8.8}],door:{at:{x:9.5,y:10.5},orientation:'vertical',type:'glass',lockdown:true}},
  {from:'northLane',to:'cleanroom',role:'approach',door:{at:{x:21.5,y:7.5},orientation:'horizontal'}},
  {from:'reception',to:'southLane',role:'risk',via:[{x:17,y:20.1}]},
  {from:'southLane',to:'northLane',role:'risk',via:[{x:19.25,y:14.75},{x:19.25,y:10.9},{x:21.5,y:10.9}]},
  {from:'cleanroom',to:'northLab',role:'alternateEscape',via:[{x:20,y:5.75},{x:20,y:4.5}],door:{at:{x:18.5,y:4.5},orientation:'vertical',type:'glass'}},
  {from:'northLab',to:'exitLobby',role:'quickEscape',door:{at:{x:5.5,y:4.5},orientation:'vertical',lockdown:true}},
  {from:'northLab',to:'westBay',role:'alternateEscape',via:[{x:7,y:4.5}]},
  {from:'westBay',to:'westStair',role:'alternateEscape'},
  {from:'westStair',to:'exitLobby',role:'alternateEscape'},
 ],
 approach:['reception','westBay','northLane','cleanroom'],risk:['reception','southLane','northLane','cleanroom'],
 quickEscape:['cleanroom','northLab','exitLobby'],alternateEscape:['cleanroom','northLab','westBay','westStair','exitLobby'],
 cover:{safe:['Reception Screen','Reception Specimen Display','Lane Mobile Screen','Lane Screen East'],risk:['Reception Screen','South Lane Screen West','South Lane Screen East'],escape:['Cleanroom Pier','North Lab Fridge A']},
 structures:[
  {name:'Reception Screen',roles:['hiding','losBreak'],kind:'labWall',asset:'lab_wall',x:12,y:19,scale:1},
  // Phase 4: second island on the safe lane, the last cover before the west-bay opening the lobby guard watches.
  {name:'Reception Specimen Display',roles:['hiding','losBreak','divider'],kind:'labSpecimenTank',asset:'lab_specimen_tank_low',x:4.6,y:19,scale:1},
  {name:'Bay Scanner',roles:['threshold','divider'],kind:'labObservationRoom',asset:'lab_observation_room',x:7,y:13.75,scale:1},
  {name:'Hall Glass A',roles:['divider','sightline'],kind:'labGlassPartition',asset:'lab_glass_partition_front',x:11.333,y:12.1,scale:0.92},
  {name:'Hall Glass B',roles:['divider','sightline'],kind:'labGlassPartition',asset:'lab_glass_partition_front',x:14,y:12.1,scale:0.92},
  {name:'Hall Glass C',roles:['divider','sightline'],kind:'labGlassPartition',asset:'lab_glass_partition_front',x:16.667,y:12.1,scale:0.92},
  {name:'Hall Glass E',roles:['divider','sightline'],kind:'labGlassPartition',asset:'lab_glass_partition_front',x:21.75,y:12.1,scale:0.862},
  {name:'Hall Glass F',roles:['divider','sightline'],kind:'labGlassPartition',asset:'lab_glass_partition_front',x:24,y:12.1,scale:0.69},
  {name:'Lane Mobile Screen',roles:['hiding','losBreak'],kind:'labMobileScreen',asset:'lab_mobile_screen',x:13,y:9.75,scale:1.36},
  {name:'Lane Screen East',roles:['hiding','losBreak'],kind:'labWall',asset:'lab_wall',x:18,y:9.75,scale:1},
  {name:'South Lane Screen West',roles:['hiding','losBreak'],kind:'labWall',asset:'lab_wall',x:12.5,y:14.1,scale:1},
  {name:'South Lane Screen East',roles:['hiding','losBreak'],kind:'labWall',asset:'lab_wall',x:22.75,y:14.1,scale:1},
  {name:'Cleanroom Bench',roles:['divider'],kind:'labLargeTable',asset:'lab_large_table',x:20.5,y:1.61,scale:1.111},
  {name:'Cleanroom Screen',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:24,y:1.6,scale:1.4},
  {name:'North Lab Fridge A',roles:['hiding','losBreak','divider'],kind:'labSampleFridge',asset:'lab_sample_fridge_front',x:13.545,y:2.725,scale:0.9},
  {name:'North Lab Fridge B',roles:['hiding','losBreak','divider'],kind:'labSampleFridge',asset:'lab_sample_fridge_front',x:15.255,y:2.725,scale:0.9},
  {name:'North Lab Workstation',roles:['losBreak','divider'],kind:'labWorkstation',asset:'lab_workstation',x:7.215,y:1.574,scale:1.35},
  {name:'Lane Status Screen',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:24,y:8.6,scale:1.4},
  {name:'Lock Door Marker',roles:['decor'],kind:'labFloorMarker',asset:'lab_floor_marker',x:8.6,y:10.5,scale:1.2},
  {name:'Glass Gap Marker',roles:['decor'],kind:'labFloorMarker',asset:'lab_floor_marker',x:19.25,y:13.3,scale:1.2},
  {name:'North Lab Cable',roles:['decor'],kind:'labCable',asset:'lab_cable',x:11.5,y:1.9,scale:1.2},
  {name:'Stair Warning Sign',roles:['decor'],kind:'labWarningSign',asset:'lab_warning_sign',x:2.5,y:8.6,scale:1.3},
 ],
 walls:[{name:'Cleanroom Pier',roles:['losBreak','hiding','divider'],at:'pier closing the sample bay of the Cleanroom'}],
 guards:[
  {role:'lobby',zone:'reception',watches:'The two openings up from the reception: the west one from the west post, the east one from the east post',
   stops:[{x:9,y:17.75,look:{x:7,y:16.9},wait:3},{x:15,y:17.75,look:{x:17,y:16.9},wait:3}]},
  {role:'crossing',zone:'northLane',watches:'The glass side of the North Lane, and the South Lane through the glass: the lane door from the west post, the gap from the east post',
   stops:[{x:12.5,y:10.9,look:{x:10.2,y:10.5},wait:3},{x:18,y:10.9,look:{x:19.5,y:11.6},wait:3}]},
  {role:'escape',zone:'exitLobby',watches:'The way out: the north lab door from the lobby post, then the west bay opening from the West Stair',
   stops:[{x:2.5,y:5.3,look:{x:5.4,y:4.5},wait:3},{x:2.5,y:11.5,look:{x:4.4,y:11.5},wait:4}]},
  {role:'objective',zone:'cleanroom',watches:'The sample; between inspections steps out of the hall door and reads the lane status screen, back to the lane',
   stops:[{x:24,y:5.6,look:{x:24,y:2.6},wait:2},{x:21.5,y:5.75,look:{x:21.5,y:8},wait:0},{x:21.5,y:8.9,look:{x:23.5,y:9.2},wait:0},{x:23.5,y:9.2,look:{x:24.6,y:8.3},wait:4}]},
 ],
 cameras:[{zone:'northLab',at:{x:9,y:1.4},facing:1.5708,watches:'The west end of the North Lab, across the run to the exit lobby door'}],
 ...SAMPLE,
};

/**
 * 04-04 Cryo Research — the S.
 * Intake hall west, cryo storage back east to the way down, prep lab west again to the vault. The short way drops
 * through the near opening under the intake camera and cuts the first bend.
 */
const M0404:V13Mission={
 id:'04-04',title:'Cryo Research',family:'Lab',topology:'S through three halls',
 map:[
  '########################',
  '#aaaaaaaaaaaaaaaaaaaaaa#',
  '#aaaaaaaaaaaaaaaaaaaaaa#',
  '#aaaaaaaaaaaaaaaaaaaaaa#',
  '#aaaaaaaaaaaaaaaaaaaaaa#',
  '#aaaaaaaaaaaaaaaaaaaaaa#',
  '##bbb##########bbb######',
  '#bbbb###bb####bbbbb#####',
  '#bbbbbbbbbbbbbbbbbbbbbb#',
  '#bbbbbbbbbbbbbbbbbbbbbb#',
  '#bbbbbbbbbbbbbbbbbbbbbb#',
  '#bbbbbbbbbbbbbbbbbbbbbb#',
  '##########ddd###########',
  '#ccccccc#ddddddddd#xxxx#',
  '#ccccccccdddddddddxxxxx#',
  '#ccccccccdddddddddxxxxx#',
  '#ccccccccdddddddddxxxxx#',
  '#cc#cccc############qqq#',
  '#cc#cccccpppppppppqqqqq#',
  '#cc#cccccpppppppppqqqqq#',
  '#cc#cccccpppppppppqqqqq#',
  '########################',
 ],
 zones:{
  a:{id:'intake',name:'Cryo Intake',role:'public',purpose:'Arrival; west to the far opening, or the near opening under the camera',hub:{x:12,y:5.1}},
  b:{id:'storage',name:'Cryo Storage',role:'transition',purpose:'One lane under the cryo banks, walked end to end by the storage guard; a pocket between the banks to wait in, beside the way down',hub:{x:11,y:10.6}},
  d:{id:'prepLab',name:'Prep Lab',role:'restricted',purpose:'Down by the vault door, which the prep guard watches from the south lane in turn with the exit lobby door',hub:{x:11,y:13.75}},
  c:{id:'cryoVault',name:'Cryo Vault',role:'objective',purpose:'Sample in the south-west bay behind the wall pier',hub:{x:6.5,y:14}},
  p:{id:'coolantPassage',name:'Coolant Passage',role:'escape',purpose:'Way out of the vault after lockdown; the vault guard checks it between inspections',hub:{x:13,y:19.5}},
  q:{id:'loadingBay',name:'Loading Bay',role:'escape',purpose:'Up to the exit lobby from the south',hub:{x:21,y:19.5}},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit; its door from the Prep Lab closes at lockdown',hub:{x:21,y:15.5}},
 },
 entry:{x:12,y:2.2},objective:{x:2,y:19.2},exit:{x:21.8,y:15.5},entryEdge:'top',exitEdge:'right',
 placement:['top-centre','bottom-left','bottom-right'],
 edges:[
  {from:'intake',to:'storage',role:'approach',via:[{x:3,y:5.1},{x:3,y:10.6}]},
  {from:'intake',to:'storage',role:'risk',via:[{x:16,y:5.1},{x:16,y:10.6}]},
  {from:'storage',to:'prepLab',role:'approach'},
  {from:'prepLab',to:'cryoVault',role:'approach',via:[{x:10.25,y:13.75},{x:10.25,y:15.5}],door:{at:{x:8.5,y:15.5},orientation:'vertical'}},
  {from:'prepLab',to:'exitLobby',role:'quickEscape',via:[{x:16.5,y:13.75},{x:16.5,y:15.5}],door:{at:{x:18.5,y:15.5},orientation:'vertical',lockdown:true}},
  {from:'cryoVault',to:'coolantPassage',role:'alternateEscape',via:[{x:6.5,y:19.5}],door:{at:{x:8.5,y:19.5},orientation:'vertical'}},
  {from:'coolantPassage',to:'loadingBay',role:'alternateEscape'},
  {from:'loadingBay',to:'exitLobby',role:'alternateEscape'},
 ],
 approach:['intake','storage','prepLab','cryoVault'],risk:['intake','storage','prepLab','cryoVault'],
 quickEscape:['cryoVault','prepLab','exitLobby'],alternateEscape:['cryoVault','coolantPassage','loadingBay','exitLobby'],
 cover:{safe:['Intake Cryo Chamber','Cryo Pier West','Prep Centrifuge Bench'],risk:['Intake Mobile Screen','Cryo Pier East','Prep Centrifuge Bench'],escape:['Vault Pier','Prep Centrifuge Bench','Passage Gas Rack']},
 structures:[
  {name:'Intake Cryo Chamber',roles:['losBreak','divider'],kind:'labCryoChamber',asset:'lab_cryo_chamber',x:2.05,y:3.25,scale:1},
  {name:'Intake Mobile Screen',roles:['hiding','losBreak','divider'],kind:'labMobileScreen',asset:'lab_mobile_screen',x:14.35,y:4.25,scale:1},
  {name:'Intake Fridge West',roles:['losBreak','divider'],kind:'labSampleFridge',asset:'lab_sample_fridge_front',x:20.435,y:3.4,scale:0.9},
  {name:'Intake Fridge East',roles:['losBreak','divider'],kind:'labSampleFridge',asset:'lab_sample_fridge_front',x:22.145,y:3.4,scale:0.9},
  {name:'Entrance Decon Arch',roles:['threshold'],kind:'labDeconArch',asset:'lab_decon_arch',x:12,y:4.15,scale:1},
  {name:'Vault Door Marker',roles:['decor'],kind:'labFloorMarker',asset:'lab_floor_marker',x:9.3,y:15.5,scale:1.2},
  {name:'Storage Cable',roles:['decor'],kind:'labCable',asset:'lab_cable',x:9,y:9.9,scale:1.2},
  {name:'Intake Screen Panel',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:8,y:1.6,scale:1.4},
  ...[5.75,7.25].map((x,i)=>({name:`Cryo Bank West ${i+1}`,roles:['losBreak','hiding','divider'] as ('losBreak'|'hiding'|'divider')[],kind:'labCryoUnit' as const,asset:'lab_cryo_unit' as const,x,y:8.635,scale:1.1538})),
  ...[10.667,12,13.333].map((x,i)=>({name:`Cryo Bank Mid ${i+1}`,roles:['losBreak','hiding','divider'] as ('losBreak'|'hiding'|'divider')[],kind:'labCryoUnit' as const,asset:'lab_cryo_unit' as const,x,y:8.564,scale:1.0256})),
  ...[19.667,21,22.333].map((x,i)=>({name:`Cryo Bank East ${i+1}`,roles:['losBreak','hiding','divider'] as ('losBreak'|'hiding'|'divider')[],kind:'labCryoUnit' as const,asset:'lab_cryo_unit' as const,x,y:8.564,scale:1.0256})),
  {name:'Prep Centrifuge Bench',roles:['hiding','losBreak','divider'],kind:'labCentrifugeBench',asset:'lab_centrifuge_bench',x:13,y:15,scale:0.92},
  // Phase 4: the coolant passage was a bare corridor; the rack hides a thief on its west side from the exit guard's post.
  {name:'Passage Gas Rack',roles:['hiding','losBreak'],kind:'labGasRack',asset:'lab_gas_rack',x:15.9,y:18.325,scale:1},
  {name:'Prep Warning Sign',roles:['decor'],kind:'labWarningSign',asset:'lab_warning_sign',x:11,y:13.6,scale:1.3},
  {name:'Vault Console',roles:['observation','losBreak'],kind:'labObservationConsole',asset:'lab_observation_console',x:2.688,y:13.562,scale:1.25},
  {name:'Vault Screen',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:6,y:13.6,scale:1.4},
 ],
 walls:[
  {name:'Vault Pier',roles:['losBreak','hiding','divider'],at:'pier closing the sample bay of the Cryo Vault'},
  {name:'Cryo Pier West',roles:['losBreak','divider'],at:'wall masses behind the west and middle cryo banks of Cryo Storage, with the waiting pocket between them'},
  {name:'Cryo Pier East',roles:['losBreak','divider'],at:'wall mass behind the east cryo bank of Cryo Storage'},
 ],
 guards:[
  {role:'crossing',zone:'storage',watches:'The storage lane end to end: the west opening from the west post, the near opening from the east post',
   stops:[{x:3,y:10.6,look:{x:3,y:7.5},wait:3},{x:20.5,y:10.6,look:{x:16,y:7.5},wait:4}]},
  {role:'restricted',zone:'prepLab',watches:'The south lane of the Prep Lab: the vault door from the west post, the exit lobby door from the east post',
   stops:[{x:10.25,y:16.25,look:{x:8.6,y:15.5},wait:3},{x:16.25,y:16.25,look:{x:18.4,y:15.5},wait:3}]},
  {role:'escape',zone:'exitLobby',watches:'The way out: the prep lab door from the lobby post, then the coolant passage opening from the Loading Bay',
   stops:[{x:20,y:14.7,look:{x:18.7,y:15.4},wait:3},{x:21,y:17.5,look:{x:21,y:19},wait:0},{x:21,y:19.3,look:{x:18.6,y:19.5},wait:4}]},
  {role:'objective',zone:'cryoVault',watches:'The sample; between inspections walks out to check the Coolant Passage',startDelay:18,
   stops:[{x:2,y:16.2,look:{x:2,y:19.2},wait:2},{x:4.9,y:16.4,look:{x:4.9,y:19.5},wait:0},{x:4.9,y:19.5,look:{x:12,y:19.5},wait:0},{x:12,y:19.5,look:{x:17,y:19.5},wait:8}]},
 ],
 cameras:[{zone:'intake',at:{x:16,y:1.4},facing:1.5708,watches:'The intake floor in front of the near opening'}],
 ...SAMPLE,
};

/**
 * 04-05 Prototype Heist — deep in, loop out.
 * Lobby, glass lab, security lock, prototype chamber, in a line. Out by the south service loop to the exit under the
 * lobby; when that and the lab door close, the way out is north through the control room and the archive.
 */
const M0405:V13Mission={
 id:'04-05',title:'Prototype Heist',family:'Lab',topology:'Deep in, loop out',
 map:[
  '############################',
  '#aaaaaaaaaaaa#nnnnnnnnnnnnn#',
  '#aaaaaaaaaaaannnnnnnnnnnnnn#',
  '#aaaaaaaaaaaannnnnnnnnnnnnn#',
  '#aaaaaaaaaaaannnnnnnnnnnnnn#',
  '#aaaaaaaaaaaa#nnnnnnnnnnnnn#',
  '##lll################ppp####',
  '#lllll#gggggggggkkkk#ppp#pp#',
  '#lllll#gggggggggkkkk#ppp#pp#',
  '#lllll#gggggggggkkkkpppp#pp#',
  '#lllllggggg#gggg#kkkpppp#pp#',
  '#lllllggggg#gggg#kkkppppppp#',
  '#lllllggggg#gggg#kkk#pppppp#',
  '#lllll#gggggggggkkkk#pppppp#',
  '#lllll#gggggggggkkkk#pppppp#',
  '#lllll#gggggggggkkkk#pppppp#',
  '##xxx################ttt####',
  '#xxxxx#ssssssssss#ttttttttt#',
  '#xxxxxxsssssssssstttttttttt#',
  '#xxxxxxsssssssssstttttttttt#',
  '#xxxxxxsssssssssstttttttttt#',
  '#xxxxx#ssssssssss#ttttttttt#',
  '############################',
 ],
 zones:{
  l:{id:'lobby',name:'Lobby',role:'public',purpose:'Arrival; the lab door ahead closes at lockdown',hub:{x:3,y:11.5}},
  g:{id:'glassLab',name:'Test Lab',role:'transition',purpose:'Cut in two by the pillar and its glass: south gap past the lab guard, north gap under the camera',hub:{x:8.25,y:11.5}},
  k:{id:'securityLock',name:'Security Lock',role:'restricted',purpose:'Narrow lock between the lab and the chamber, walked end to end by the lock guard',hub:{x:18,y:10.5}},
  p:{id:'chamber',name:'Prototype Chamber',role:'objective',purpose:'Prototype sample in the north-east bay behind the wall pier',hub:{x:23.5,y:11.75}},
  t:{id:'coolantPlant',name:'Coolant Plant',role:'escape',purpose:'First leg of the service loop out',hub:{x:22.5,y:18.6}},
  s:{id:'loadingPassage',name:'Loading Passage',role:'escape',purpose:'Long run west to the exit lobby door, which closes at lockdown',hub:{x:11.85,y:19.5}},
  n:{id:'controlRoom',name:'Control Room',role:'escape',purpose:'Way out after lockdown; the chamber guard stands here between inspections',hub:{x:22.5,y:5}},
  a:{id:'archive',name:'Archive',role:'escape',purpose:'Back west above the lab to the lobby, along the archive stacks',hub:{x:3,y:3.75}},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit under the lobby',hub:{x:3,y:19.5}},
 },
 entry:{x:2.2,y:11.5},objective:{x:26,y:8.6},exit:{x:3,y:20.8},entryEdge:'left',exitEdge:'bottom',
 placement:['left-centre','right-centre','bottom-left'],
 edges:[
  {from:'lobby',to:'glassLab',role:'approach',door:{at:{x:6.5,y:11.5},orientation:'vertical',type:'glass',lockdown:true}},
  {from:'glassLab',to:'securityLock',role:'approach',via:[{x:8.25,y:15},{x:14,y:15},{x:14,y:14.5},{x:16.5,y:14.5},{x:18,y:14.5}],door:{at:{x:16.5,y:14.5},orientation:'vertical'}},
  {from:'glassLab',to:'securityLock',role:'risk',via:[{x:8.25,y:8},{x:14,y:8},{x:14,y:8.5},{x:16.5,y:8.5},{x:18,y:8.5}],door:{at:{x:16.5,y:8.5},orientation:'vertical'}},
  {from:'securityLock',to:'chamber',role:'approach',via:[{x:20.5,y:10.5},{x:22,y:10.5},{x:22,y:11.75}],door:{at:{x:20.5,y:10.5},orientation:'vertical'}},
  {from:'chamber',to:'coolantPlant',role:'quickEscape',via:[{x:22.5,y:11.75}]},
  {from:'coolantPlant',to:'loadingPassage',role:'quickEscape',via:[{x:18.6,y:18.6},{x:18.6,y:19.5},{x:16.25,y:19.5},{x:16.25,y:20.9},{x:11.85,y:20.9}]},
  {from:'loadingPassage',to:'exitLobby',role:'quickEscape',via:[{x:11.85,y:18.1},{x:7.6,y:18.1},{x:7.6,y:19.5},{x:6.5,y:19.5}],door:{at:{x:6.5,y:19.5},orientation:'vertical',lockdown:true}},
  {from:'chamber',to:'controlRoom',role:'alternateEscape',via:[{x:22.5,y:11.75}]},
  {from:'controlRoom',to:'archive',role:'alternateEscape',via:[{x:14.75,y:5},{x:14.75,y:3.75}]},
  {from:'archive',to:'lobby',role:'alternateEscape'},
  {from:'lobby',to:'exitLobby',role:'alternateEscape'},
 ],
 approach:['lobby','glassLab','securityLock','chamber'],risk:['lobby','glassLab','securityLock','chamber'],
 quickEscape:['chamber','coolantPlant','loadingPassage','exitLobby'],alternateEscape:['chamber','controlRoom','archive','lobby','exitLobby'],
 cover:{safe:['Lab Pillar','Lab Workstation'],risk:['Lab Pillar'],escape:['Chamber Pier','Chamber Robot Cell','Control Fume Hood','Prototype Test Rig','Passage Cryo East','Passage Console']},
 structures:[
  {name:'Lobby Workstation',roles:['divider'],kind:'labWorkstation',asset:'lab_workstation',x:4.785,y:7.574,scale:1.35},
  {name:'Archive Server Rack A',roles:['hiding','losBreak','divider'],kind:'labServerRack',asset:'lab_server_rack_front',x:5.9,y:2.825,scale:1},
  {name:'Archive Server Rack B',roles:['losBreak','divider'],kind:'labServerRack',asset:'lab_server_rack_front',x:7.7,y:2.825,scale:1},
  {name:'Archive Server Rack C',roles:['losBreak','divider'],kind:'labServerRack',asset:'lab_server_rack_front',x:9.5,y:2.825,scale:1},
  {name:'Prototype Test Rig',roles:['hiding','losBreak','divider'],kind:'labPrototypeMachine',asset:'lab_prototype_machine',x:17.7,y:3.5,scale:1},
  // Phase 4: the east half of the control room was bare; an island beside the way up from the chamber.
  {name:'Control Fume Hood',roles:['hiding','losBreak','divider'],kind:'labFumeHood',asset:'lab_fume_hood',x:24.4,y:3.4,scale:1},
  {name:'Control Screen West',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:17,y:1.6,scale:1.4},
  {name:'Control Screen East',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:20.5,y:1.6,scale:1.4},
  {name:'Lab Glass North',roles:['divider','sightline'],kind:'galleryGlassPanelVertical',x:11.5,y:9.5,scale:0.7143},
  {name:'Lab Glass South',roles:['divider','sightline'],kind:'galleryGlassPanelVertical',x:11.5,y:13.5,scale:0.7143},
  {name:'Lab Workstation',roles:['divider'],kind:'labWorkstation',asset:'lab_workstation',x:10.1,y:11.03,scale:1},
  {name:'Lock Scanner',roles:['threshold','divider'],kind:'labObservationRoom',asset:'lab_observation_room',x:18.5,y:12.8,scale:0.75},
  {name:'Lock Warning Sign',roles:['decor'],kind:'labWarningSign',asset:'lab_warning_sign',x:18,y:7.6,scale:1.3},
  {name:'Chamber Robot Cell',roles:['hiding','losBreak','divider'],kind:'labRobotCell',asset:'lab_robot_cell',x:26,y:13.6,scale:1},
  {name:'Plant Console',roles:['losBreak','divider'],kind:'labObservationConsole',asset:'lab_observation_console',x:20.6,y:20,scale:1},
  {name:'Passage Cryo West',roles:['hiding','losBreak','divider'],kind:'labCryoUnit',asset:'lab_cryo_unit',x:13.5,y:19.3,scale:1},
  {name:'Passage Cryo East',roles:['hiding','losBreak','divider'],kind:'labCryoUnit',asset:'lab_cryo_unit',x:14.8,y:19.3,scale:1},
  {name:'Passage Console',roles:['hiding','losBreak','divider'],kind:'labObservationConsole',asset:'lab_observation_console',x:9.55,y:19.5,scale:1},
  {name:'Coolant Rig',roles:['losBreak','divider'],kind:'labCentralExperiment',asset:'lab_central_experiment',x:25.35,y:19.5,scale:1},
  {name:'Lab Door Marker',roles:['decor'],kind:'labFloorMarker',asset:'lab_floor_marker',x:5.7,y:11.5,scale:1.2},
  {name:'Exit Door Marker',roles:['decor'],kind:'labFloorMarker',asset:'lab_floor_marker',x:7.6,y:19.5,scale:1.2},
  {name:'Control Cable',roles:['decor'],kind:'labCable',asset:'lab_cable',x:21.2,y:2.6,scale:1.2},
  {name:'Plant Screen',roles:['decor'],kind:'labWallScreen',asset:'lab_wall_screen',x:25.5,y:17.6,scale:1.4},
 ],
 walls:[
  {name:'Lab Pillar',roles:['losBreak','hiding','divider'],at:'pillar in the middle of the Test Lab, between its two glass panels'},
  {name:'Chamber Pier',roles:['losBreak','hiding','divider'],at:'pier closing the sample bay of the Prototype Chamber'},
 ],
 guards:[
  {role:'lobby',zone:'glassLab',watches:'The west half of the Test Lab through the glass: from the north panel, then from the south panel',
   stops:[{x:13.25,y:9.5,look:{x:9,y:9.5},wait:4},{x:13.25,y:13.5,look:{x:9,y:13.5},wait:2}]},
  {role:'restricted',zone:'securityLock',watches:'The north door of the Security Lock from the north post, the chamber door from the middle post; the south door is behind him',
   stops:[{x:18,y:8.25,look:{x:16.6,y:8.5},wait:5},{x:18,y:12,look:{x:20.4,y:10.6},wait:2}]},
  {role:'escape',zone:'loadingPassage',watches:'The Loading Passage: the coolant plant opening from the north-east post, the exit lobby door from the south-west post',
   stops:[{x:16.2,y:17.9,look:{x:16.6,y:19.8},wait:3},{x:11.85,y:17.9,look:{x:11.85,y:19.5},wait:0},{x:11.85,y:20.9,look:{x:9.5,y:20.9},wait:0},{x:9.5,y:20.9,look:{x:7.4,y:19.6},wait:3}]},
  {role:'objective',zone:'chamber',watches:'The prototype sample; between inspections walks up to the Control Room and looks down its length',
   stops:[{x:26,y:11.6,look:{x:26,y:8.6},wait:2},{x:22.5,y:11.6,look:{x:22.5,y:7},wait:0},{x:22.5,y:4.9,look:{x:17,y:5},wait:7.5}]},
 ],
 cameras:[{zone:'glassLab',at:{x:11.5,y:7.4},facing:1.5708,watches:'The north gap of the Test Lab'}],
 ...SAMPLE,
};

/** The plans as first shipped, without the Phase 7 cover: Chapter 8 is built from these. */
export const V13_LAB_FROZEN:V13Mission[]=[M0401,M0402,M0403,M0404,M0405];
export const V13_LAB:V13Mission[]=V13_LAB_FROZEN.map(phase7);
