/** V13 Phase 1 — Chapter 1 Museum (EASY). Architecture first; guards are authored last. */
import type {V13Mission} from './v13Types';
import {phase7} from './v13Phase7';

/**
 * 01-01 Entrance Hall — L-shape.
 * Safe lane runs east along the Entrance Hall behind the desk, column and long case, then north behind the
 * Collection Wall. The risk lane cuts the corner through the Central Court, around the statue the hall guard walks past.
 */
const M0101:V13Mission={
 id:'01-01',title:'Entrance Hall',family:'Museum',topology:'L-shape',
 map:[
  '######################',
  '#ssssss#xxxxx#cc#cccc#',
  '#sssssssxxxxxxcc#cccc#',
  '#sssssssxxxxxxcc#cccc#',
  '#sssssssxxxxxxccccccc#',
  '#ssssss#xxxxx#ccccccc#',
  '##www###########ggg###',
  '#wwwwwwtt##tt#ggggggg#',
  '#wwwwwwtttttt#ggggggg#',
  '#wwwwwwtttttt#ggggggg#',
  '#wwwwwwttttttgggggggg#',
  '#wwwwwwttttttgggggggg#',
  '#wwwwwwttttttgggggggg#',
  '########hhh#####hhh###',
  '#lllllllhhhhhhhhhhhhh#',
  '#lllllllhhhhhhhhhhhhh#',
  '#lllllllhhhhhhhhhhhhh#',
  '#lllllllhhhhhhhhhhhhh#',
  '#lllllllhhhhhhhhhhhhh#',
  '######################',
 ],
 zones:{
  l:{id:'lobby',name:'Entrance Lobby',role:'public',purpose:'Arrival behind the security desk; first look at the hall guard'},
  h:{id:'hall',name:'Entrance Hall',role:'public',purpose:'Safe lane east along the south wall, covered by the column and the long case',hub:{x:9.5,y:18.25}},
  t:{id:'court',name:'Central Court',role:'transition',purpose:'Risk crossing around the statue: shortest line to the collection'},
  g:{id:'wallGallery',name:'Collection Wall Gallery',role:'restricted',purpose:'Last cover before the Collection Room door',hub:{x:17.5,y:11.5}},
  c:{id:'collection',name:'Collection Room',role:'objective',purpose:'Diamond bay behind a wall pier; the pier hides the thief from the returning guard',hub:{x:19,y:5.25}},
  x:{id:'foyer',name:'North Foyer',role:'escape',purpose:'Exit; the Collection Room door here closes at lockdown'},
  w:{id:'westGallery',name:'West Gallery',role:'escape',purpose:'Escape after lockdown behind the side wall',hub:{x:4,y:11.5}},
  s:{id:'sideGallery',name:'Side Wall Gallery',role:'escape',purpose:'Escape along the wall cases into the foyer'},
 },
 entry:{x:2.2,y:16.5},objective:{x:20,y:2.5},exit:{x:10.5,y:2.2},entryEdge:'left',exitEdge:'top',
 placement:['bottom-left','top-right','top-centre'],
 edges:[
  {from:'lobby',to:'hall',role:'approach'},
  {from:'hall',to:'wallGallery',role:'approach',via:[{x:17.5,y:13.5}]},
  {from:'wallGallery',to:'collection',role:'approach',door:{at:{x:17.5,y:6.5},orientation:'horizontal'}},
  {from:'hall',to:'court',role:'risk',via:[{x:9.5,y:13.5}]},
  {from:'court',to:'wallGallery',role:'risk',via:[{x:13.5,y:11.5}]},
  {from:'collection',to:'foyer',role:'quickEscape',door:{at:{x:13.5,y:3.5},orientation:'vertical',lockdown:true}},
  {from:'collection',to:'wallGallery',role:'alternateEscape',via:[{x:17.5,y:5.25},{x:17.5,y:6.5}]},
  {from:'wallGallery',to:'court',role:'alternateEscape',via:[{x:13.5,y:11.5}]},
  {from:'court',to:'westGallery',role:'alternateEscape'},
  {from:'westGallery',to:'sideGallery',role:'alternateEscape',via:[{x:4,y:6.5}]},
  {from:'sideGallery',to:'foyer',role:'alternateEscape',via:[{x:7.5,y:3.5}]},
 ],
 approach:['lobby','hall','wallGallery','collection'],risk:['lobby','hall','court','wallGallery','collection'],
 quickEscape:['collection','foyer'],alternateEscape:['collection','wallGallery','court','westGallery','sideGallery','foyer'],
 cover:{safe:['Lobby Security Desk','Hall Column','Long Display Case','Collection Wall','Collection Pier'],risk:['Lobby Security Desk','Court Statue','Collection Wall'],escape:['Court Statue','Side Wall','Side Wall Cases']},
 structures:[
  {name:'Lobby Security Desk',roles:['hiding','divider'],kind:'counter',asset:'museum_security_desk',x:6.2,y:16.2,scale:2.2},
  {name:'Hall Column',roles:['losBreak','hiding'],kind:'pillar',asset:'museum_column',x:12.2,y:16.7,scale:1.8},
  {name:'Long Display Case',roles:['hiding','sightline'],kind:'displayCase',asset:'museum_display_case_large',x:16,y:16.7,scale:2.2},
  {name:'Hall Bust',roles:['decor'],kind:'statuePedestal',asset:'museum_pedestal',x:20.36,y:14.48,scale:1.6},
  {name:'Court Statue',roles:['losBreak','divider','hiding'],kind:'statue',asset:'museum_statue_large',x:10,y:9.3,scale:3},
  {name:'Collection Wall',roles:['losBreak','hiding','divider'],kind:'partition',asset:'museum_partition',x:17.5,y:9.6,scale:2.6},
  {name:'Collection Low Display',roles:['decor'],kind:'table',asset:'museum_display_low',x:18.2,y:1.63,scale:1.8},
  {name:'Side Wall',roles:['losBreak','hiding','divider'],kind:'partition',asset:'museum_partition',x:4,y:9.6,scale:2.2},
  {name:'Side Wall Cases',roles:['hiding'],kind:'displayCase',asset:'museum_display_case_large',x:4,y:1.9,scale:2},
  {name:'Foyer Pedestal',roles:['decor'],kind:'statuePedestal',asset:'museum_pedestal',x:8.56,y:1.42,scale:1.4},
 ],
 walls:[{name:'Court Pier',roles:['losBreak'],at:'wall block behind the Court Statue'},{name:'Collection Pier',roles:['losBreak','hiding','divider'],at:'pier splitting the Collection Room into the foyer side and the diamond bay'}],
 guards:[
  {role:'lobby',zone:'court',watches:'The two public lanes in turn: the Collection Wall opening from the court post, the length of the hall from the hall post',
   stops:[{x:10.25,y:11.75,look:{x:14,y:11.5},wait:3},{x:13.5,y:15,look:{x:17.5,y:15},wait:3}]},
  {role:'objective',zone:'collection',watches:'The diamond; between inspections steps out to the west end of the Collection Wall and watches the court opening',
   stops:[{x:19.75,y:4.5,look:{x:20,y:2.5},wait:2},{x:17.5,y:6.5,look:{x:17.5,y:9},wait:0},{x:17.5,y:8.25,look:{x:14.75,y:8.5},wait:0},{x:14.75,y:8.5,look:{x:14.75,y:11},wait:0},{x:14.75,y:11,look:{x:12,y:11.25},wait:7}]},
 ],
 cameras:[],
};

/**
 * 01-02 Main Gallery — branching around the rotunda.
 * From the vestibule the thief goes left of the rotunda core either along the outer arcade, column to column
 * (longer, covered), or straight across the rotunda floor past the crossing guard (shorter, exposed).
 */
const M0102:V13Mission={
 id:'01-02',title:'Main Gallery',family:'Museum',topology:'Branching',
 map:[
  '########################',
  '#ppppppp#aaaaaaa#xxxxxx#',
  '#pppppppaaaaaaaa#xxxxxx#',
  '#ppp#pppaaaaaaaaxxxxxxx#',
  '#ppp#pppaaaaaaaaxxxxxxx#',
  '#ppp#ppp#aaaaaaaxxxxxxx#',
  '#####ttt##########eee###',
  '#ttttttt#nnnnnnnneeeeee#',
  '#tttttttnnnnnnnnneeeeee#',
  '#tttttttnnnnnnnnneeeeee#',
  '#wwwwwrrrrrrrrrrreeeeee#',
  '#wwwwwrrrrr###rrr#eeeee#',
  '#wwwwwrrrrr###rrr#eeeee#',
  '#wwwwwrrrrrrrrrrr#eeeee#',
  '#wwwwwrrrrrrrrrrreeeeee#',
  '#wwwwwrrrrrrrrrrreeeeee#',
  '#wwwwwrrrrrrrrrrreeeeee#',
  '#########vvvvvv#########',
  '#########vvvvvv#########',
  '#########vvvvvv#########',
  '########################',
 ],
 zones:{
  v:{id:'vestibule',name:'South Vestibule',role:'public',purpose:'Arrival below the rotunda; the branch is chosen here'},
  r:{id:'rotunda',name:'Rotunda Floor',role:'public',purpose:'Risk crossing: open floor around the rotunda core, walked by the crossing guard',hub:{x:8.5,y:14.5}},
  w:{id:'arcade',name:'West Arcade',role:'transition',purpose:'Safe lane along the outer wall behind the colonnade',hub:{x:2.75,y:13.5}},
  t:{id:'anteroom',name:'Exhibit Anteroom',role:'restricted',purpose:'Both lanes meet here in front of the Private Exhibit door',hub:{x:4.5,y:8.75}},
  p:{id:'private',name:'Private Exhibit',role:'objective',purpose:'Diamond in the bay behind the wall pier',hub:{x:6.5,y:4.5}},
  a:{id:'northGallery',name:'North Gallery',role:'escape',purpose:'Quick way to the exit hall; its door to the exhibit closes at lockdown'},
  n:{id:'ambulatory',name:'North Ambulatory',role:'escape',purpose:'Escape behind the rotunda core after lockdown',hub:{x:12.5,y:9.75}},
  e:{id:'eastWing',name:'East Wing',role:'escape',purpose:'Escape north to the exit hall behind the wing wall',hub:{x:19,y:9.5}},
  x:{id:'exitHall',name:'Exit Hall',role:'escape',purpose:'Exit'},
 },
 entry:{x:12,y:18.8},objective:{x:2.25,y:4.6},exit:{x:19.5,y:2.2},entryEdge:'bottom',exitEdge:'top',
 placement:['bottom-centre','top-left','top-right'],
 edges:[
  {from:'vestibule',to:'rotunda',role:'approach',via:[{x:12,y:16}]},
  {from:'rotunda',to:'arcade',role:'approach'},
  {from:'arcade',to:'anteroom',role:'approach'},
  {from:'anteroom',to:'private',role:'approach',door:{at:{x:6.5,y:6.5},orientation:'horizontal'}},
  {from:'rotunda',to:'anteroom',role:'risk',via:[{x:8.5,y:8.75}]},
  {from:'private',to:'northGallery',role:'quickEscape',door:{at:{x:8.5,y:3.5},orientation:'vertical',lockdown:true}},
  {from:'northGallery',to:'exitHall',role:'quickEscape',via:[{x:16.5,y:4.5}]},
  {from:'private',to:'anteroom',role:'alternateEscape',via:[{x:6.5,y:6.5}]},
  {from:'anteroom',to:'ambulatory',role:'alternateEscape',via:[{x:8.5,y:8.75}]},
  {from:'ambulatory',to:'eastWing',role:'alternateEscape'},
  {from:'eastWing',to:'exitHall',role:'alternateEscape',via:[{x:19.5,y:6.5}]},
 ],
 approach:['vestibule','rotunda','arcade','anteroom','private'],risk:['vestibule','rotunda','anteroom','private'],
 quickEscape:['private','northGallery','exitHall'],alternateEscape:['private','anteroom','ambulatory','eastWing','exitHall'],
 cover:{safe:['Arcade Column South','Arcade Column North','Anteroom Sculpture'],risk:['Rotunda Statue','Anteroom Sculpture'],escape:['Exhibit Pier','Ambulatory Case','East Wing Wall']},
 structures:[
  {name:'Rotunda Statue',roles:['losBreak','divider'],kind:'statue',asset:'museum_statue_large',x:12.5,y:13.98,scale:2.8},
  {name:'Arcade Column South',roles:['losBreak','hiding'],kind:'pillar',asset:'museum_column',x:5.6,y:15,scale:1.8},
  {name:'Arcade Column North',roles:['losBreak','hiding'],kind:'pillar',asset:'museum_column',x:5.6,y:11.8,scale:1.8},
  {name:'Anteroom Sculpture',roles:['hiding','losBreak'],kind:'statue',asset:'museum_statue_large',x:1.99,y:10.3,scale:2.2},
  {name:'Ambulatory Case',roles:['hiding','losBreak'],kind:'displayCase',asset:'museum_display_case_large',x:12.5,y:7.9,scale:2},
  {name:'East Wing Wall',roles:['losBreak','hiding'],kind:'partition',asset:'museum_partition',x:21.6,y:11,scale:2},
  {name:'East Wing Case',roles:['hiding'],kind:'displayCase',asset:'museum_display_case_large',x:21.8,y:7.9,scale:2},
  {name:'East Wing Low Display',roles:['divider'],kind:'table',asset:'museum_display_low',x:21.68,y:14.5,scale:2.2},
  {name:'North Gallery Low Display',roles:['divider'],kind:'table',asset:'museum_display_low',x:12.5,y:3.5,scale:2.4},
  {name:'Exhibit Bust',roles:['decor'],kind:'statuePedestal',asset:'museum_pedestal',x:7.36,y:1.48,scale:1.6},
  {name:'Exit Hall Bust',roles:['decor'],kind:'statuePedestal',asset:'museum_pedestal',x:22.36,y:1.48,scale:1.6},
 ],
 walls:[{name:'Rotunda Core',roles:['losBreak','divider'],at:'solid core in the middle of the rotunda floor'},{name:'Exhibit Pier',roles:['losBreak','hiding','divider'],at:'pier closing the diamond bay of the Private Exhibit'},{name:'East Wing Wall Stub',roles:['divider','losBreak'],at:'wall between the rotunda floor and the east wing'}],
 guards:[
  {role:'crossing',zone:'rotunda',watches:'The rotunda floor: the arcade from the west post, the anteroom opening from the north post, the east wing from the east post',
   stops:[{x:9.75,y:12.25,look:{x:6,y:12.25},wait:2.5},{x:12.5,y:10.25,look:{x:9,y:9},wait:2},{x:15.25,y:12.25,look:{x:18.5,y:9.5},wait:2.5}]},
  {role:'objective',zone:'private',watches:'The diamond; between inspections stands in the anteroom watching the arcade',
   stops:[{x:2.25,y:2.75,look:{x:2.25,y:4.6},wait:2},{x:6.5,y:8.25,look:{x:5,y:12},wait:4}]},
 ],
 cameras:[],
};

/**
 * 01-03 Archive — S-shape through small rooms.
 * Stacks (west) → Storage (north, between the racks) → Conservation Workspace (east) → Secure Archive.
 * The risk lane skips Storage through the workspace's own door, right under the archivist guard.
 */
const M0103:V13Mission={
 id:'01-03',title:'Archive',family:'Museum',topology:'S-shape',
 map:[
  '#######################',
  '#xxxxx#rrrrrrrrrrrrrrr#',
  '#xxxxxxrrrrrrrrrrrrrrr#',
  '#xxxxxxrrrrrrrrrrrrrrr#',
  '#xxxxxxrrrrrrrrrrrrrrr#',
  '#xxxxx#rrrrrrrrrrrrrrr#',
  '#############vvv##kkkk#',
  '#ssssccccc#vvvvvv#kkkk#',
  '#ssssccccc#vvvvvvkkkkk#',
  '#ssssccccc#vv#vvvkkkkk#',
  '#ssss#ccccvvv#vvvkkkkk#',
  '#ssss#ccccvvv#vvv#kkkk#',
  '#ssss#ccccvvv#vvv#kkkk#',
  '##sss##ccc#############',
  '#aaaaaaaaaaaaaaaaaaaaa#',
  '#aaaaaaaaaaaaaaaaaaaaa#',
  '#aaaaaaaaaaaaaaaaaaaaa#',
  '#aaaaaaaaaaaaaaaaaaaaa#',
  '#######################',
 ],
 zones:{
  a:{id:'stacks',name:'Archive Stacks',role:'public',purpose:'Long approach west along the south wall past the stack cases'},
  s:{id:'storage',name:'Storage',role:'transition',purpose:'Safe lane: slalom between two storage racks, out of every sightline',hub:{x:4.25,y:9.9}},
  c:{id:'workspace',name:'Conservation Workspace',role:'restricted',purpose:'Archivist guard room in front of the Secure Archive door',hub:{x:9,y:9.4}},
  v:{id:'secure',name:'Secure Archive',role:'objective',purpose:'Documents in the east bay behind the wall pier',hub:{x:12,y:8}},
  k:{id:'records',name:'Records Passage',role:'escape',purpose:'Way out after lockdown; the objective guard stands here between inspections'},
  r:{id:'reading',name:'Reading Room',role:'escape',purpose:'Escape west between the reading tables to the exit lobby',hub:{x:15.5,y:4.6}},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit'},
 },
 entry:{x:20.8,y:16},objective:{x:15,y:11.6},exit:{x:3.5,y:2.2},entryEdge:'right',exitEdge:'top',
 placement:['bottom-right','centre','top-left'],
 edges:[
  {from:'stacks',to:'storage',role:'approach',via:[{x:3.5,y:13.5}]},
  {from:'storage',to:'workspace',role:'approach',via:[{x:5.5,y:8.25}]},
  {from:'workspace',to:'secure',role:'approach',door:{at:{x:10.5,y:11.5},orientation:'vertical'}},
  {from:'stacks',to:'workspace',role:'risk',via:[{x:8.5,y:13.5}]},
  {from:'secure',to:'reading',role:'quickEscape',door:{at:{x:14.5,y:6.5},orientation:'horizontal',lockdown:true}},
  {from:'reading',to:'exitLobby',role:'quickEscape',via:[{x:6.5,y:3.5}]},
  {from:'secure',to:'records',role:'alternateEscape',via:[{x:17.5,y:9.5}]},
  {from:'records',to:'reading',role:'alternateEscape',via:[{x:20,y:6.5}]},
  {from:'reading',to:'exitLobby',role:'alternateEscape',via:[{x:6.5,y:3.5}]},
 ],
 approach:['stacks','storage','workspace','secure'],risk:['stacks','workspace','secure'],
 quickEscape:['secure','reading','exitLobby'],alternateEscape:['secure','records','reading','exitLobby'],
 cover:{safe:['Stack Case East','Stack Case West','Storage Rack South','Storage Rack North','Workspace Cabinet','Archive Pier'],risk:['Stack Case East','Stack Case West','Stacks Column'],escape:['Records Cabinet','Card Catalogue']},
 structures:[
  {name:'Stack Case East',roles:['losBreak','hiding'],kind:'displayCase',asset:'museum_display_case_large',x:17.5,y:14.9,scale:2},
  {name:'Stack Case West',roles:['losBreak','hiding'],kind:'displayCase',asset:'museum_display_case_large',x:12.5,y:14.9,scale:2},
  {name:'Stacks Column',roles:['losBreak','hiding'],kind:'pillar',asset:'museum_column',x:6,y:14.72,scale:1.8},
  {name:'Storage Rack South',roles:['losBreak','divider'],kind:'partition',asset:'museum_partition',x:3.81,y:11,scale:1.7},
  {name:'Storage Rack North',roles:['losBreak','divider'],kind:'partition',asset:'museum_partition',x:2.19,y:8.8,scale:1.7},
  {name:'Conservation Workbench',roles:['divider'],kind:'table',asset:'museum_display_low',x:7.08,y:10.83,scale:1.8},
  {name:'Workspace Cabinet',roles:['hiding','losBreak'],kind:'displayCase',asset:'museum_display_case_large',x:9.04,y:7.72,scale:1.6},
  {name:'Records Cabinet',roles:['hiding'],kind:'partition',asset:'museum_partition',x:20.88,y:10.9,scale:1.6},
  {name:'Card Catalogue',roles:['hiding','losBreak'],kind:'displayCase',asset:'museum_display_case_large',x:13.75,y:1.9,scale:2},
  {name:'Reading Table East',roles:['divider'],kind:'table',asset:'museum_display_low',x:18,y:3.6,scale:2.2},
  {name:'Reading Table West',roles:['divider'],kind:'table',asset:'museum_display_low',x:9.6,y:3.6,scale:2.2},
  {name:'Lobby Bust',roles:['decor'],kind:'statuePedestal',asset:'museum_pedestal',x:1.64,y:1.48,scale:1.6},
 ],
 walls:[{name:'Archive Pier',roles:['losBreak','hiding','divider'],at:'pier splitting the Secure Archive into the door bay and the document bay'}],
 guards:[
  {role:'restricted',zone:'workspace',watches:'The two ways into the workspace: the Storage opening from the north post, the stacks door from the south post',
   stops:[{x:7.25,y:9,look:{x:4,y:8.5},wait:3},{x:7.5,y:12.5,look:{x:8.5,y:16},wait:3}]},
  {role:'objective',zone:'secure',watches:'The documents; between inspections stands in the Records Passage',
   stops:[{x:16.25,y:10,look:{x:15,y:11.6},wait:2},{x:19.5,y:9.25,look:{x:19.5,y:12},wait:4}]},
 ],
 cameras:[],
};

/**
 * 01-04 Security Wing — U-shape with a loop.
 * The U runs down the Public Gallery, along the Staff Corridor and up through the Security Desk into the
 * Restricted Collection. The Central Gallery closes the loop as a short cut under the wing's only camera.
 */
const M0104:V13Mission={
 id:'01-04',title:'Security Wing',family:'Museum',topology:'U-shape loop',
 map:[
  '########################',
  '#gggggg#################',
  '#gggggg#################',
  '#gggggg#mmmmmm##########',
  '#gggggg#mmmmmm#cccccccc#',
  '#ggggggmmmmmmmccccccccc#',
  '#gg##ggmmmmmmmccccc#ccc#',
  '#ggggggmmmmmmmccccc#ccc#',
  '#gggggg#mmmmmm#cccc#ccc#',
  '#gggggg########cccccccc#',
  '#gggggg########cccccccc#',
  '##ggg##########ccc##ccc#',
  '#ffffffffffddddddd#xxxx#',
  '#ffffffffffddddddd#xxxx#',
  '#ffffffffffddddddd#xxxx#',
  '#fffffffff#ddddddd#xxxx#',
  '############kkk####xxxx#',
  '###########kkkkkkkkxxxx#',
  '###########kkkkkkkkxxxx#',
  '###########kkkkkkkkxxxx#',
  '########################',
 ],
 zones:{
  g:{id:'gallery',name:'Public Gallery',role:'public',purpose:'Arrival; the statue splits the way to the Central Gallery and the staff door',hub:{x:1.75,y:9.75}},
  m:{id:'central',name:'Central Gallery',role:'restricted',purpose:'Risk short cut under the camera, covered only by the gallery partition',hub:{x:12.75,y:7.25}},
  f:{id:'staff',name:'Staff Corridor',role:'transition',purpose:'Safe lane along the bottom of the U'},
  d:{id:'desk',name:'Security Desk',role:'restricted',purpose:'Desk guard room; the desk hides the lane to the Restricted Collection door',hub:{x:16.5,y:12.9}},
  c:{id:'restricted',name:'Restricted Collection',role:'objective',purpose:'Artifact in the east bay behind the free-standing pier',hub:{x:21,y:9.5}},
  k:{id:'passage',name:'Staff Passage',role:'escape',purpose:'Way round to the exit lobby after lockdown'},
  x:{id:'exitLobby',name:'Exit Lobby',role:'escape',purpose:'Exit; the Restricted Collection door here closes at lockdown',hub:{x:21.5,y:14}},
 },
 entry:{x:2.2,y:2.5},objective:{x:21.5,y:7.5},exit:{x:21,y:18.8},entryEdge:'left',exitEdge:'bottom',
 placement:['top-left','right-centre','bottom-right'],
 edges:[
  {from:'gallery',to:'staff',role:'approach',via:[{x:3.5,y:11.5}]},
  {from:'staff',to:'desk',role:'approach',via:[{x:10.5,y:12.9}]},
  {from:'desk',to:'restricted',role:'approach',door:{at:{x:16.5,y:11.5},orientation:'horizontal'}},
  {from:'gallery',to:'central',role:'risk',via:[{x:7.5,y:7.25}]},
  {from:'central',to:'restricted',role:'risk',via:[{x:14.5,y:7.25}]},
  {from:'restricted',to:'exitLobby',role:'quickEscape',door:{at:{x:21.5,y:11.5},orientation:'horizontal',lockdown:true}},
  {from:'restricted',to:'desk',role:'alternateEscape',via:[{x:16.5,y:9.5},{x:16.5,y:11.5}]},
  {from:'desk',to:'passage',role:'alternateEscape',via:[{x:13.5,y:15.4},{x:13.5,y:16.5}]},
  {from:'passage',to:'exitLobby',role:'alternateEscape',via:[{x:18.5,y:18.5}]},
 ],
 approach:['gallery','staff','desk','restricted'],risk:['gallery','central','restricted'],
 quickEscape:['restricted','exitLobby'],alternateEscape:['restricted','desk','passage','exitLobby'],
 cover:{safe:['Gallery Statue','Staff Lockers','Security Desk'],risk:['Gallery Statue','Gallery Partition'],escape:['Collection Pier','Lobby Screen','Passage Lockers']},
 structures:[
  {name:'Gallery Statue',roles:['divider','losBreak'],kind:'statue',asset:'museum_statue_large',x:4,y:7.91,scale:2.6},
  {name:'Gallery Case',roles:['hiding'],kind:'displayCase',asset:'museum_display_case_large',x:5.8,y:1.9,scale:2},
  {name:'Gallery Partition',roles:['losBreak','hiding'],kind:'partition',asset:'museum_partition',x:9.68,y:5.9,scale:2.4},
  {name:'Staff Lockers',roles:['hiding','sightline'],kind:'partition',asset:'museum_partition',x:7.3,y:12.42,scale:2.4},
  {name:'Security Desk',roles:['losBreak','divider','hiding'],kind:'counter',asset:'museum_security_desk',x:14.5,y:14,scale:1.6},
  {name:'Collection Wall Display',roles:['decor'],kind:'table',asset:'museum_display_low',x:16.08,y:4.63,scale:1.8},
  {name:'Passage Lockers',roles:['hiding'],kind:'partition',asset:'museum_partition',x:16.4,y:17.35,scale:2},
  {name:'Lobby Screen',roles:['losBreak','hiding'],kind:'partition',asset:'museum_partition',x:20.12,y:15.6,scale:1.6},
 ],
 walls:[{name:'Gallery Pier',roles:['losBreak'],at:'wall block behind the Gallery Statue'},{name:'Collection Pier',roles:['losBreak','hiding','divider'],at:'free-standing pier in front of the artifact bay'}],
 guards:[
  {role:'restricted',zone:'desk',watches:'The Security Desk room: the staff corridor opening from the north-west post, the staff passage door from the south-east post',
   stops:[{x:12.25,y:12.75,look:{x:9.5,y:13},wait:3},{x:12.25,y:15.25,look:{x:16,y:15.25},wait:0},{x:16.75,y:15.25,look:{x:13.5,y:16.75},wait:4}]},
  {role:'objective',zone:'restricted',watches:'The artifact; between inspections stands in the exit lobby watching the staff passage',
   stops:[{x:20.75,y:6,look:{x:21.5,y:7.5},wait:2},{x:20.5,y:13.5,look:{x:20.5,y:17},wait:4}]},
 ],
 cameras:[{zone:'central',at:{x:10.5,y:3.4},facing:1.5708,watches:'The Central Gallery short cut north of the partition and the gap to the Restricted Collection opening'}],
};

/**
 * 01-05 Grand Heist — deep in along the top, out along the bottom.
 * Grand Lobby → Main Exhibition → Security Threshold → Private Collection → Diamond Chamber.
 * After lockdown the way out is the Display Wall, the Side Exhibition and the Service Corridor to the side exit.
 */
const M0105:V13Mission={
 id:'01-05',title:'Grand Heist',family:'Museum',topology:'Asymmetric loop: deep in, alternate out',
 map:[
  '#########################',
  '#tttt#mmmmm##mmmmm#lllll#',
  '#ttttmmmmmmmmmmmmmllllll#',
  '#ttttmmmmmmmmmmmmmllllll#',
  '#ttttmmmmmmmmmmmmmllllll#',
  '#tttt#mmmmmmmmmmmm#lllll#',
  '#tttt#mmmmmmmmmmmm#lllll#',
  '##vvv##ppp###############',
  '#vvvvvpppppp#############',
  '#vvvvvpppppp#ssssss######',
  '#vvvvvppp#pp#ssssss######',
  '######ppp#pp#ssssss######',
  '#dddd#ppp#ppsssssss######',
  '#dddddppp#ppsssssss######',
  '#dddddppppppsssssss######',
  '#dddddpppppp#ssssss######',
  '#xxx##########kkk########',
  '#xxxxxkkkkkkkkkkkkk######',
  '#xxxxxkkkkkkkkkkkkk######',
  '#xxxxxkkkkkkkkkkkkk######',
  '#########################',
 ],
 zones:{
  l:{id:'lobby',name:'Grand Lobby',role:'public',purpose:'Arrival behind the lobby desk'},
  m:{id:'main',name:'Main Exhibition',role:'public',purpose:'Long hall past the Grand Statue, column to column behind the hall guard',hub:{x:17,y:3.5}},
  t:{id:'threshold',name:'Security Threshold',role:'transition',purpose:'Safe lane: the checkpoint room that leads round to the Private Collection',hub:{x:4.25,y:3.5}},
  v:{id:'vestibule',name:'Collection Vestibule',role:'transition',purpose:'Out of range of the collection guard; the thief watches the Display Wall from here'},
  p:{id:'private',name:'Private Collection',role:'restricted',purpose:'Display Wall splits the room; the chamber guard walks out along its south side',hub:{x:7.75,y:11.5}},
  d:{id:'chamber',name:'Diamond Chamber',role:'objective',purpose:'Diamond in the far corner of the chamber',hub:{x:3,y:14.5}},
  s:{id:'side',name:'Side Exhibition',role:'escape',purpose:'Escape after lockdown behind the side wall',hub:{x:14.5,y:13.5}},
  k:{id:'service',name:'Service Corridor',role:'escape',purpose:'Escape west to the side exit, walked by the exit guard'},
  x:{id:'exitLobby',name:'Side Exit',role:'escape',purpose:'Exit; the chamber door here closes at lockdown'},
 },
 entry:{x:22.8,y:3.5},objective:{x:1.75,y:12.75},exit:{x:2.2,y:18.5},entryEdge:'right',exitEdge:'left',
 placement:['top-right','left-centre','bottom-left'],
 edges:[
  {from:'lobby',to:'main',role:'approach',via:[{x:18.5,y:3.5}]},
  {from:'main',to:'threshold',role:'approach',via:[{x:5.5,y:3.5}]},
  {from:'threshold',to:'vestibule',role:'approach',via:[{x:3.5,y:7.5}]},
  {from:'vestibule',to:'private',role:'approach'},
  {from:'private',to:'chamber',role:'approach',door:{at:{x:5.5,y:14.5},orientation:'vertical'}},
  {from:'main',to:'private',role:'risk',via:[{x:10,y:5.75},{x:8.5,y:5.75},{x:8.5,y:7.5},{x:8.5,y:9}]},
  {from:'chamber',to:'exitLobby',role:'quickEscape',door:{at:{x:2.5,y:16.5},orientation:'horizontal',lockdown:true}},
  {from:'chamber',to:'private',role:'alternateEscape',via:[{x:5.5,y:14.5}]},
  {from:'private',to:'side',role:'alternateEscape',via:[{x:12.5,y:13.5}]},
  {from:'side',to:'service',role:'alternateEscape',via:[{x:15.5,y:16.5}]},
  {from:'service',to:'exitLobby',role:'alternateEscape',via:[{x:6.5,y:18.5}]},
 ],
 approach:['lobby','main','threshold','vestibule','private','chamber'],risk:['lobby','main','private','chamber'],
 quickEscape:['chamber','exitLobby'],alternateEscape:['chamber','private','side','service','exitLobby'],
 cover:{safe:['Lobby Desk','Exhibition Column East','Grand Statue','Exhibition Column West','Threshold Desk','Display Wall'],risk:['Exhibition Column East','Grand Statue','Exhibition Column West','Display Wall'],escape:['Display Wall','Side Exhibition Wall','Service Cabinet']},
 structures:[
  {name:'Lobby Desk',roles:['hiding','divider'],kind:'counter',asset:'museum_security_desk',x:22.6,y:4.9,scale:2},
  {name:'Grand Statue',roles:['losBreak','hiding'],kind:'statue',asset:'museum_statue_large',x:12,y:2.98,scale:2.8},
  {name:'Exhibition Column East',roles:['losBreak','hiding'],kind:'pillar',asset:'museum_column',x:15.5,y:4.2,scale:1.8},
  {name:'Exhibition Column West',roles:['losBreak','hiding'],kind:'pillar',asset:'museum_column',x:8.5,y:4.2,scale:1.8},
  {name:'Threshold Desk',roles:['threshold','hiding'],kind:'counter',asset:'museum_security_desk',x:2.12,y:3.2,scale:1.6},
  {name:'Vestibule Bust',roles:['decor'],kind:'statuePedestal',asset:'museum_pedestal',x:1.64,y:8.48,scale:1.6},
  {name:'Side Exhibition Statue',roles:['losBreak','hiding'],kind:'statue',asset:'museum_statue_large',x:15.5,y:9.91,scale:2.6},
  {name:'Side Exhibition Wall',roles:['losBreak','hiding'],kind:'partition',asset:'museum_partition',x:17.6,y:13.1,scale:2},
  {name:'Service Cabinet',roles:['hiding'],kind:'partition',asset:'museum_partition',x:10.5,y:17.35,scale:2},
 ],
 walls:[{name:'Display Wall',roles:['losBreak','divider','hiding'],at:'wall down the middle of the Private Collection'},{name:'Statue Pier',roles:['losBreak'],at:'wall block behind the Grand Statue'}],
 guards:[
  {role:'crossing',zone:'main',watches:'The Main Exhibition: the lobby opening from the east post, the Security Threshold opening and the collection door from the west post',
   stops:[{x:16.5,y:5.75,look:{x:19.5,y:3.5},wait:3},{x:7,y:5.75,look:{x:5.5,y:3.5},wait:3}]},
  {role:'escape',zone:'service',watches:'The way out: the chamber door from the side exit post, the Side Exhibition door from the corridor post',
   stops:[{x:4.25,y:18.25,look:{x:2.5,y:16.5},wait:3},{x:15.5,y:18.5,look:{x:15.5,y:16},wait:3}]},
  {role:'objective',zone:'chamber',watches:'The diamond; between inspections walks the south passage to check the Side Exhibition',
   stops:[{x:3.25,y:13.75,look:{x:1.75,y:12.75},wait:2},{x:13.75,y:13.5,look:{x:17,y:13.5},wait:4}]},
 ],
 cameras:[],
};
/** The plans as first shipped, without the Phase 7 cover: Chapter 7 is built from these. */
export const V13_MUSEUM_FROZEN:V13Mission[]=[M0101,M0102,M0103,M0104,M0105];
export const V13_MUSEUM:V13Mission[]=V13_MUSEUM_FROZEN.map(phase7);
