/** Security/geometry acceptance on actual engine; does not establish human Tilt fairness. */
import fs from 'node:fs';
import {BANK_PRODUCTION,BANK_PLANS} from './bankProductionDesign';
import {compileStage,TILE} from '../../src/game/world/compileStage';
import {buildNavigation,clearSegment,findPath} from '../../src/game/world/navigation';
import {BODY} from '../../src/game/guards/guardTuning';
import {createPlaygroundState} from '../../src/game/playground/playgroundState';
import {stepGuards} from '../../src/game/guards/guardSystem';

import {narrowGap,MIN_COMFORT_GAP} from './museumCentralCoverQA';
import {runV5BankMission} from './v5BankReplay';
import {createHash} from 'node:crypto';
export function v5BankQA(){return BANK_PRODUCTION.map((def,index)=>{
 const stage=compileStage(def),nav=buildNavigation(stage,BODY.guardRadius);
 const paths=[...def.testRoutes!,...def.escapeRoutes!].map(r=>({name:r.name,length:r.points.slice(1).reduce((n,b,i)=>n+Math.hypot(b.x-r.points[i].x,b.y-r.points[i].y),0),segments:r.points.slice(1).map((b,i)=>({a:r.points[i],b,body:clearSegment(r.points[i].x*TILE,r.points[i].y*TILE,b.x*TILE,b.y*TILE,stage.movementBlockers,BODY.playerRadius),margin:clearSegment(r.points[i].x*TILE,r.points[i].y*TILE,b.x*TILE,b.y*TILE,stage.movementBlockers,MIN_COMFORT_GAP/2)}))}));
 const boxes=[];for(let i=0;i<stage.movementBlockers.length;i+=4)boxes.push({id:`blocker-${i/4}`,l:stage.movementBlockers[i],t:stage.movementBlockers[i+1],r:stage.movementBlockers[i+2],b:stage.movementBlockers[i+3]});
 const reachable=(p:{x:number;y:number})=>{const path=findPath(nav,stage.playerSpawn.x,stage.playerSpawn.y,p.x,p.y);return path.length>=2&&Math.hypot(path.at(-2)!-p.x,path.at(-1)!-p.y)<.01;};
 const gaps=[];for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)for(const gap of narrowGap(boxes[i],boxes[j])){if(!clearSegment(gap.from.x,gap.from.y,gap.to.x,gap.to.y,stage.movementBlockers,0))continue;if(![gap.from,gap.to].some(p=>clearSegment(p.x,p.y,p.x,p.y,stage.movementBlockers,BODY.playerRadius)&&reachable(p)))continue;gaps.push({...gap,a:boxes[i].id,b:boxes[j].id});}
 const state=createPlaygroundState(stage),collisionSamples=state.guards.map(()=>0),visited=state.guards.map(()=>new Set<number>()),coverage=new Set<string>(),zoneCoverage=new Set<string>();
 let t=0;const hidden={x:-1000,y:-1000,gait:0};
 for(let f=0;f<120*60;f++){t+=1/60;stepGuards(state.guards,hidden,stage.visionBlockers,nav,1/60,state.events,t,true,1,state.theft);state.guards.forEach((g,i)=>{if(!clearSegment(g.x,g.y,g.x,g.y,stage.movementBlockers,BODY.guardRadius))collisionSamples[i]++;g.route.forEach((p,j)=>{if(Math.hypot(p.x-g.x,p.y-g.y)<8)visited[i].add(j);});});
  if(f%30===0)for(let y=1;y<stage.rows;y++)for(let x=1;x<stage.cols;x++){const wx=(x+.5)*TILE,wy=(y+.5)*TILE;if(!clearSegment(wx,wy,wx,wy,stage.movementBlockers,BODY.playerRadius))continue;for(const g of state.guards){const dx=wx-g.x,dy=wy-g.y,angle=Math.atan2(dy,dx)-g.facing;if(Math.hypot(dx,dy)<=g.visionRange&&Math.abs(Math.atan2(Math.sin(angle),Math.cos(angle)))<=g.visionHalfAngle&&clearSegment(g.x,g.y,wx,wy,stage.visionBlockers)){coverage.add(`${x},${y}`);for(const r of BANK_PLANS[index].rooms)if(x>=r.x&&x<r.x+r.w&&y>=r.y&&y<r.y+r.h)zoneCoverage.add(r.name);break;}}
  }
 }
 const patrol=state.guards.map((g,i)=>({id:g.id,visited:visited[i].size,total:g.route.length,recoveries:g.patrolRecoveries,collisionSamples:collisionSamples[i]}));
 const replays=def.testRoutes!.map((r,route)=>{const attempts=[];let witness:null|ReturnType<typeof runV5BankMission>=null;outer:for(const mode of[1,2,3])for(const delay of[0,2,4,6,9,12,16,20,24]){const result=runV5BankMission(def,{route,escape:0,mode,delay});attempts.push(result);if(result.clear){witness=result;break outer;}}if(!witness&&def.mission===10){outer:for(const mode of[1,2,3])for(const delay of[0,2,4,6,9,12])for(const seconds of[2,4,8,12,16]){const result=runV5BankMission(def,{route,escape:0,mode,delay,zoneWait:{zone:'East Cash Service',seconds}});attempts.push(result);if(result.clear){witness=result;break outer;}}}return{name:r.name,witness,attempts};});
 const coveredAt=(x:number,y:number)=>coverage.has(`${Math.floor(x)},${Math.floor(y)}`);
 const objectiveCoverage=coveredAt(def.objective!.x,def.objective!.y),exitCoverage=coveredAt(def.exit!.x+.5,def.exit!.y+.5);
 const uncoveredMajorZones=BANK_PLANS[index].rooms.filter(r=>!zoneCoverage.has(r.name)).map(r=>r.name);
 let maxUncoveredTravel=0,run=0;for(const route of def.testRoutes!)for(const [i,p] of route.points.entries()){if(!i){run=0;continue;}const a=route.points[i-1],distance=Math.hypot(p.x-a.x,p.y-a.y),steps=Math.ceil(distance*4);for(let j=1;j<=steps;j++){const q={x:a.x+(p.x-a.x)*j/steps,y:a.y+(p.y-a.y)*j/steps};run=coveredAt(q.x,q.y)?0:run+distance/steps;maxUncoveredTravel=Math.max(maxUncoveredTravel,run);}}
 const hideWitnesses=BANK_PLANS[index].rooms.map(r=>{const candidates=[];for(let y=r.y+.5;y<r.y+r.h;y+=.5)for(let x=r.x+.5;x<r.x+r.w;x+=.5){const wx=x*TILE,wy=y*TILE;if(!clearSegment(wx,wy,wx,wy,stage.movementBlockers,18)||!reachable({x:wx,y:wy}))continue;const observer={x:(r.x+r.w-.55)*TILE,y:(r.y+4)*TILE};if(clearSegment(observer.x,observer.y,wx,wy,stage.visionBlockers))continue;candidates.push({x,y,observer:{x:observer.x/TILE,y:observer.y/TILE}});}return{zone:r.name,reachableOccludedPoints:candidates.length,witness:candidates[0]??null};});
 const area=stage.grid.filter(c=>c===1).length;
 return{id:def.id,sourceSha256:createHash('sha256').update(JSON.stringify(def)).digest('hex'),zoneCount:BANK_PLANS[index].rooms.length,guards:def.guards.length,cameras:def.cameras?.length??0,area,identity:def.structurePlan,paths,gaps,patrol,replays,coverage:{method:'Actual 120s moving Guard vision at0.5s sampling on navigable1tile grid; no CCTV coverage included yet',guardTiles:coverage.size,areaFraction:coverage.size/area,objectiveCoverage,exitCoverage,uncoveredMajorZones,maxUncoveredTravel,junctionCoverage:BANK_PLANS[index].rooms.filter(r=>/Junction|Security/.test(r.name)).map(r=>({zone:r.name,seen:zoneCoverage.has(r.name)})),warnings:[...(uncoveredMajorZones.length?[`Patrol intentionally leaves ${uncoveredMajorZones.join(', ')} unguarded; evaluate camera/entry fairness`]:[]),...(maxUncoveredTravel>12?[`Maximum uncovered route run ${maxUncoveredTravel.toFixed(1)}tiles: review rather than auto-add guards`]:[])]},hideability:{method:'Radius18 reachable half-tile samples hidden by actual LOS blockers from authored room right-lane patrol viewpoint; witnesses are static geometry, not guaranteed perpetual invisibility',hideWitnesses,fullCover:def.props.filter(p=>['bankMainVault','bankSecurityCheckpoint','bankDepositBoxWall','bankFilingCabinet','bankTellerCounter'].includes(p.kind)).length,pockets:def.safeZones!.length,alternateRoutes:def.testRoutes!.length},native:false};
});}
if(process.argv[1]?.endsWith('v5BankQA.ts')){const report=v5BankQA();fs.mkdirSync('Reports/LevelDesignV5',{recursive:true});fs.writeFileSync('Reports/LevelDesignV5/bank-qa.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.map(r=>({id:r.id,gaps:r.gaps.length,patrol:r.patrol,replays:r.replays.map(w=>!!w.witness),badSegments:r.paths.flatMap(p=>p.segments.filter(s=>!s.margin))}))));}
