export type Language = 'en' | 'ko';
const en = {
 chapters:'CHAPTER SELECT', missions:'MISSION SELECT', missionLabel:'MISSION', legacy:'PREVIOUS VERSION RECORD',
 home:'HOME', continue:'CONTINUE', start:'START GAME', stages:'STAGE SELECT', settings:'SETTINGS',
 language:'Language', sfx:'Sound Effects', music:'Background Music', intro:'Play Intro',
 adsSection:'Ads', removeAds:'Remove Ads', removeAdsDetail:'Buy once to remove all in-game ads permanently.\nYou will never be charged again.',
 removeAdsOwned:'Purchased ✓', removeAdsOwnedDetail:'Ads are not shown on this device.', removeAdsBuy:'Buy Remove Ads', restorePurchases:'Restore Purchases', purchasing:'Processing purchase...',
 restoring:'Checking your purchases...',
 storeLoading:'Loading price...', storeUnavailable:'Could not load store information.', storePending:'Purchases are not available yet.', storeRetry:'Retry store connection', storeTryAgain:'Try Again',
 purchased:'Ads have been removed.', restored:'Your purchase has been restored.', restoreEmpty:'There are no purchases to restore.', cancelled:'Purchase cancelled.', alreadyOwned:'You already own this item.',
 purchaseFailed:'The purchase could not be completed.\nPlease try again in a moment.', restoreFailed:'Your purchases could not be restored.\nPlease try again in a moment.', productUnavailable:'This product is unavailable. Please retry later.', pendingApproval:'Purchase awaiting approval.', finishFailed:'Purchase confirmation failed. Please restore purchases.',
 clear:'CLEAR', locked:'LOCKED', play:'PLAY', mission:'MISSION COMPLETE', chapter:'CHAPTER COMPLETE',
 caught:'CAUGHT', retry:'RETRY', next:'NEXT STAGE', back:'BACK', stage:'STAGE',
 nextChapter:'NEXT CHAPTER', replay:'PLAY AGAIN',
 controlMode:'Controls', controlTilt:'Tilt (recommended)', controlTouch:'Touch',
 controlFallback:'Tilt sensor unavailable. Playing with touch.', touchHint:'Hold and drag to move',
 paused:'PAUSED', resume:'RESUME', recenter:'RECENTER', restart:'RESTART', again:'PLAY AGAIN',
 time:'CLEAR TIME', best:'BEST TIME', alerts:'ALERTS', choose:'CHOOSE YOUR NEXT MISSION',
 preparing:'PREPARING…', retryLoading:'RETRY LOADING', secured:'OBJECTIVE SECURED',
 diamond:'DIAMOND SECURED', acquired:'OBJECTIVE ACQUIRED', diamondAcquired:'DIAMOND ACQUIRED',
 escape:'ESCAPE TO THE EXIT', target:'TARGET', centerReset:'CENTER RESET',
 hold:'HOLD COMFORTABLY', ready:'READY', sensorPaused:'SENSOR PAUSED', sensorRetry:'RETRY SENSOR',
 calibration:'Hold still briefly in a comfortable position.', saveError:'Unable to save. Your session is still available; try again.',
 skip:'Skip intro', tagline:'A STEALTH GAME\nIN YOUR HANDS', silence:'SILENCE IS A SKILL',
 artError:'Artwork could not load.', assetError:'CHARACTER ASSETS INCOMPLETE', assetDetail:'Player / Guard animation sheets are missing or failed validation.',
 updateApplying:'Applying update', updateApplied:'Update applied',
 searching:'SEARCH', returning:'RETURN', lockdownIn:'LOCKDOWN IN', lockdownActive:'LOCKDOWN ACTIVE',
 theft:'THEFT ALERT', spotted:'PLAYER SPOTTED', touch:'TOUCH CONTROL ACTIVE',
 valuableDiamond:'Diamond', painting:'Rare Painting', vaultGem:'Vault Gem', prototype:'Prototype', jewel:'High-value Jewel', artifact:'Artifact', contraband:'Contraband Case', data:'Data Device', classified:'Classified Prototype', master:'Master Diamond',
 stage01:'MUSEUM', stage02:'ART GALLERY', stage03:'BANK', stage04:'LAB', stage05:'CASINO',
 stage06:'MANSION', stage07:'WAREHOUSE', stage08:'SECURITY HQ', stage09:'BLACK SITE', stage10:'HIGH SECURITY VAULT',
 currentMission:'CURRENT MISSION', guards:'GUARDS', goals:'OBJECTIVE', clearedCount:'CLEARED', bestShort:'BEST',
 lockedHint:'Complete the previous mission', devUnlocked:'QA', qaUnlockAll:'QA: ALL MISSIONS UNLOCKED', heist:'A GREATER HEIST AWAITS', chapterLabel:'CHAPTER',
 chapterIntro01:'Among sleeping relics,\nthe first quiet step begins.', chapterIntro02:'Where art still breathes,\nthe quietest infiltration begins.',
 chapterIntro03:'Beyond the steel door,\nbe quieter than the ledgers.', chapterIntro04:'Under cold light,\nevery movement is recorded.',
 chapterIntro05:'While everyone watches the tables,\nyou watch the guards.', chapterIntro06:'On a night of creaking stairs,\nthe heirloom waits deepest inside.',
 chapterIntro07:'The shadows of stacked cargo\nare your only cover.', chapterIntro08:'Where every screen is watching,\nfind the blind spot.',
 chapterIntro09:'The final seal.\nThe greatest heist awaits.',
};
export type TextKey = keyof typeof en;
const ko: Record<TextKey,string> = {
 chapters:'챕터 선택', missions:'미션 선택', missionLabel:'미션', legacy:'이전 버전 기록',
 home:'홈', continue:'계속하기', start:'게임 시작', stages:'스테이지 선택', settings:'설정',
 language:'언어', sfx:'효과음', music:'배경 음악', intro:'인트로 다시 보기',
 adsSection:'광고', removeAds:'광고 제거', removeAdsDetail:'한 번 구매하면 게임 내 광고가 영구적으로 제거됩니다.\n다시 결제할 필요가 없습니다.',
 removeAdsOwned:'구매 완료 ✓', removeAdsOwnedDetail:'이 기기에서 광고가 표시되지 않습니다.', removeAdsBuy:'광고 제거 구매', restorePurchases:'구매 복원', purchasing:'구매 처리 중...',
 restoring:'구매 내역 확인 중...',
 storeLoading:'가격 불러오는 중...', storeUnavailable:'스토어 정보를 불러오지 못했습니다.', storePending:'아직 구매할 수 없는 상품입니다.', storeRetry:'스토어 다시 연결', storeTryAgain:'다시 시도',
 purchased:'광고가 제거되었습니다.', restored:'구매 내역을 복원했습니다.', restoreEmpty:'복원할 구매 내역이 없습니다.', cancelled:'구매가 취소되었습니다.', alreadyOwned:'이미 구매한 상품입니다.',
 purchaseFailed:'구매를 완료하지 못했습니다.\n잠시 후 다시 시도해 주세요.', restoreFailed:'구매 내역을 복원하지 못했습니다.\n잠시 후 다시 시도해 주세요.', productUnavailable:'상품 정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.', pendingApproval:'구매 승인을 기다리고 있습니다.', finishFailed:'구매 확인을 완료하지 못했습니다. 구매 복원을 시도해 주세요.',
 clear:'완료', locked:'잠김', play:'플레이', mission:'미션 완료', chapter:'챕터 완료',
 caught:'붙잡혔습니다', retry:'다시 도전', next:'다음 스테이지', back:'뒤로', stage:'스테이지',
 nextChapter:'다음 챕터', replay:'다시 하기',
 controlMode:'조작 방식', controlTilt:'기울이기 (추천)', controlTouch:'터치',
 controlFallback:'기울기 센서를 사용할 수 없어 터치로 조작합니다.', touchHint:'화면을 누른 채 끌어서 이동',
 paused:'일시 정지', resume:'계속하기', recenter:'중심 재설정', restart:'다시 시작', again:'다시 플레이',
 time:'완료 시간', best:'최고 기록', alerts:'경보', choose:'다음 임무를 선택하세요',
 preparing:'준비 중…', retryLoading:'다시 불러오기', secured:'목표물 확보',
 diamond:'다이아몬드 확보', acquired:'목표물 획득', diamondAcquired:'다이아몬드 획득',
 escape:'출구로 탈출하세요', target:'목표', centerReset:'중심이 재설정되었습니다',
 hold:'편하게 들어 주세요', ready:'준비 완료', sensorPaused:'센서 일시 정지', sensorRetry:'센서 다시 연결',
 calibration:'편하게 든 자세에서 잠시 멈춰 주세요.', saveError:'저장하지 못했습니다. 현재 진행은 유지됩니다. 다시 시도해 주세요.',
 skip:'인트로 건너뛰기', tagline:'당신의 손안에서\n펼쳐지는 잠입', silence:'침묵도 실력이다',
 artError:'이미지를 불러오지 못했습니다.', assetError:'캐릭터 에셋 미완성', assetDetail:'Player / Guard 애니메이션 시트가 없거나 검증을 통과하지 못했습니다.',
 updateApplying:'업데이트 적용중', updateApplied:'업데이트 적용 완료',
 searching:'수색 중', returning:'복귀 중', lockdownIn:'봉쇄까지', lockdownActive:'봉쇄 가동',
 theft:'도난 경보', spotted:'플레이어 발견', touch:'터치 조작 사용 중',
 valuableDiamond:'다이아몬드', painting:'희귀 그림', vaultGem:'금고 보석', prototype:'시제품', jewel:'고가 보석', artifact:'유물', contraband:'밀수품 가방', data:'데이터 장치', classified:'기밀 시제품', master:'마스터 다이아몬드',
 stage01:'박물관', stage02:'미술관', stage03:'은행', stage04:'연구소', stage05:'카지노',
 stage06:'저택', stage07:'창고', stage08:'보안 본부', stage09:'비밀 시설', stage10:'최고 보안 금고',
 currentMission:'현재 미션', guards:'경비', goals:'목표', clearedCount:'완료', bestShort:'BEST',
 lockedHint:'이전 미션을 완료하세요', devUnlocked:'QA', qaUnlockAll:'QA: ALL MISSIONS UNLOCKED', heist:'A GREATER HEIST AWAITS', chapterLabel:'CHAPTER',
 chapterIntro01:'잠든 유물 사이로,\n첫 번째 발걸음을 내딛는다.', chapterIntro02:'예술이 숨 쉬는 곳,\n가장 조용한 침투가 시작된다.',
 chapterIntro03:'두꺼운 금고문 너머,\n장부보다 조용해야 한다.', chapterIntro04:'차가운 빛 아래,\n모든 움직임이 기록된다.',
 chapterIntro05:'모두가 테이블을 볼 때,\n당신은 경비를 본다.', chapterIntro06:'계단이 삐걱이는 밤,\n가보는 가장 깊은 곳에 있다.',
 chapterIntro07:'쌓인 화물의 그림자가\n유일한 은신처다.', chapterIntro08:'모든 화면이 지켜보는 곳,\n사각지대를 찾아라.',
 chapterIntro09:'마지막 봉인.\n가장 위대한 한탕이 기다린다.',
};
export const translations = { en, ko };
export const translate = (language:Language, key:TextKey) => translations[language][key];
export const stageKey = (index:number):TextKey => `stage${String(index+1).padStart(2,'0')}` as TextKey;
const feedbackKeys:Record<string,TextKey>={
 'OBJECTIVE SECURED':'secured',
 'DIAMOND ACQUIRED':'diamondAcquired','OBJECTIVE ACQUIRED':'acquired','ESCAPE TO THE EXIT':'escape',
 'THEFT ALERT':'theft','PLAYER SPOTTED':'spotted','CENTER RESET':'centerReset','TOUCH CONTROL ACTIVE':'touch',
};
export const feedbackKey=(message:string)=>feedbackKeys[message];
export const valuableKey:Record<string,TextKey>={diamond:'valuableDiamond',painting:'painting',vaultGem:'vaultGem',prototype:'prototype',jewel:'jewel',artifact:'artifact',case:'contraband',data:'data',classified:'classified',masterDiamond:'master'};
export const chapterIntroKey=(chapter:number):TextKey=>`chapterIntro${String(chapter+1).padStart(2,'0')}` as TextKey;
